### ISSUE TITLE
Practice App: Creating Serializers

### ISSUE THREAD

**Issue by KarahanS** [bounswe/bounswe2022group8#100]
### What's up?

We have designed our ER Diagrams as documented in #94. Models are designed in #96. One way of returning our models in JSON format is to implement [Serializers](https://www.django-rest-framework.org/api-guide/serializers/). Please keep in mind that scope of this work is limited, and aimed to give you a starting point. You can add new serializers in your branches if necessary.

### To Do

Following actions must be taken:
- [x] Create serializers: 
   - [x] Create ```user``` serializer.
   - [x] Create ```comment``` serializer.
   - [x] Create ```tag``` serializer.
   - [x] Create ```art item``` serializer.
   - [x] Create ```follow``` serializer.

### Deadline

_Deadline: 14.05.2022 @22.00_

### Additional Information

**Contributors**: 
* @BElifb 
* @KarahanS

**Comment by KarahanS** [comment]
* In #93, serializers for **ArtItem** and **Tag** are created by @BElifb. Then I've added serializers for **Comment** and **myUser** before merging.
* In #99, modified existing serializers to reflect the changes in the model, added **Follow** and **SimpleUser** serializers.

**Comment by KarahanS** [comment]
* Updated the **ArtItemSerializer** to return more information about its tags by this [commit]( https://github.com/bounswe/bounswe2022group8/commits/feature/artitem). It used to return only the ID of the tag, now it returns all the fields including the name of the tag.

**Comment by KarahanS** [comment]
* Updated the **ArtItemSerializer** to return more information aobut the owner by this [commit](https://github.com/bounswe/bounswe2022group8/commit/35af255a7da2e13fd3f67a9adeb92fd38b1b9a48). It used to return only the ID of the owner, not it returns username, name and surname as well.

**Comment by serdarakol** [comment]
Serilizers of our practice app seems to have all the functionality we needed to accomplish our endpoint tasks. one can open an issue if it is needed. It is finalized for milestone 2 report for now.
