### ISSUE TITLE
Practice App Research: Research on Django

### ISSUE THREAD

**Issue by kostanya** [bounswe/bounswe2022group8#103]
### What's up?

Since we've chosen Django and the Django REST framework, it's a good idea to collect the resources we researched while learning Django so everyone on the team can benefit. 

For starters, I've added 5 text tutorials that I like.

### To Do

Under ["Research on Django"](https://github.com/bounswe/bounswe2022group8/wiki/Research-on-Django), you can collect text or video materials that you find useful.

### Deadline

_Deadline: 20.05.2022 @20.00_

### Additional Information

Those who want to contribute can assign themselves.

### Reviewers

@KarahanS

**Comment by KarahanS** [comment]
* Added some video sources I've used for #92.

**Comment by serdarakol** [comment]
Along with the other members you guys did great job by guiding us to learn django and even tutoring us. closing the issue
