### ISSUE TITLE
Practice App: API Endpoints

### ISSUE THREAD

**Issue by KarahanS** [bounswe/bounswe2022group8#104]
### What's up?

Please add the APIs you are responsible for and make a reference to this issue from the specific sub-issue.

### To Do

| Assignee |  API   |  API Method  | API Description | 
 |  :----:        |  :----:   |  :----: | :----: |
| @KarahanS |  ```api/v1/artitems```   |  ```GET``` | Return all of the art items in the system | 
| @KarahanS  |    ```api/v1/artitems```     |  ```POST```  | Create an art item | 
| @KarahanS  |  ```api/v1/artitems/<id>```     | ```GET```  | Return an art item with the given ID | 
| @KarahanS  |  ```api/v1/artitems/users/<id>```    |  ```GET```   | Get all of the art items of the specific user (by id) | 
| @KarahanS  |    ```api/v1/artitems/users/<username> ```    |  ```GET``` |  Get all of the art items of the specific user (by username) | 
| @sinemKocoglu |   ```api/v1/comments/artitem/<int:id>```   |  ```GET```  | Get all of the comments of the specific art item (by id) | 
| @sinemKocoglu |   ```api/v1/comments/artitem/<int:id>```   |  ```POST```   | Post  comment for the specific art item (by id) | 
| @sinemKocoglu |   ```api/v1/users/<int:id>/comment/<int:commentid>```   |  ```DELETE```   | Delete the comment by commentid posted by the user having id | 
| @BElifb  |  ```api/searchbytag/<str:tag>``` |  ```GET```  | Get all of the art items with the given tag name. | 
| @KarahanS & @kostanya  |   ```api/v1/searchbytagkeyword/<str:tag>``` |   ```GET```  | Get all of the art items with the given key word. | 
| @mumcusena  |   ```api/v1/tags```  |   ```GET```  | Return all of the art items in the system. | 
| @mumcusena  |  ```api/v1/tags```    |  ```POST```    | Create a new tag | 
| @mumcusena  |  ```api/v1/tags/<int:id>```  |  ```DELETE```  | Delete an existing tag by its id. | 
|@hebunsimsek| ```api/v1/artitems/users/username/<str:username> ```| ```GET``` |  Get all information on that specific user by username |
| - |  -  |  -  | - | 

## External APIs

| Assignee | API   |  External API |API Method  | API Description | 
 |  :----:        |  :----:   |  :----: |  :----: | :----: |
| @KarahanS  | ```api/v1/episodes/<str:series>```   |  [tvmaze.com/api](https://www.tvmaze.com/api) |  ```GET```  | Return episodes of the given TV series | 
| @BElifb  |  ```api/questions/<str:tag>``` | [api.stackexchange.com](https://api.stackexchange.com/docs/unanswered-questions#order=desc&sort=activity&filter=default&site=stackoverflow&run=true) |```GET```  | Get all of the unanswered stackexchange questions with the given tag name. | 
| @BElifb  |  ```api/searchbytag/all``` | [api.stackexchange.com](https://api.stackexchange.com/docs/unanswered-questions#order=desc&sort=activity&filter=default&site=stackoverflow&run=true) | ```GET```  | Get all of the unanswered stackexchange questions. | 

### Deadline

_Deadline:_ _20.05.22 @12.00_

### Additional Information

Both route of the APIs and contents are tentative, meaning that we may change them
based on the discussions we do in the meetings.

* There are two places we can insert our views in the project.
   * ```django_app/views.py```: This should include all the front-end related views.
   * ```api/views/```: This is a folder that will include all the REST API views.
* There are two places we can insert our urls in the project.
   * ```django_app/urls.py```: This should include:
      * ```path('', include('api.urls'))```
      *  ```path('admin/', admin.site.urls)```
      * All frontend related urls.
   * ```api/urls.py```: This should include all the API related urls. API related urls must be in the form of: ```http://127.0.0.1:8000/api/v1/<specific route>```. Fill in the route accordingly, you can of course add more branches like: ```http://127.0.0.1:8000/api/v1/artitems/users/<int:id>```

Please try to comply with the REST API naming conventions like using nouns and not using underscores etc. You can refer to them from [here](https://restfulapi.net/resource-naming/)

Please revise&update accordingly before the pull requests @everyone.

### Reviewers

Everyone must fill in the table and also check the corresponding box.
- [ ] @ooodogodogodogo 
- [ ] @serdarakol 
- [ ] @kostanya 
- [x] @BElifb 
- [x] @simsekhebun 
- [x] @KarahanS 
- [x] @sinemKocoglu 
- [x] @mumcusena 
- [ ] @mustafa-cihan 
- [ ] @dundarmete

**Comment by sinemKocoglu** [comment]
#102

**Comment by uskudarli** [comment]
In practice, it can be quite difficult to get everyone to respond to such issues. But this is really a centrally constrained one. 

After the table is constructed then each person's tasks should be transformed to separate issues. Everyone can create their own issues and assign them to themselves. 

@serdarakol @ooodogodogodogo @kostanya @simsekhebun @BElifb @mumcusena @mustafa-cihan @dundarmete

**Comment by KarahanS** [comment]
Practice App Implementation is over. No action is taken, closing the issue.
