### ISSUE TITLE
Practice App: Feature- Search by tag API

### ISSUE THREAD

**Issue by BElifb** [bounswe/bounswe2022group8#107]
### What's up?

As discussed in [meeting notes #14](https://github.com/bounswe/bounswe2022group8/wiki/Week-10-Meeting-%2314) I will create the API for search by tag. Given a tag name this API will return a list of all of the art items tagged with that tag (in json format).
 |  API  endpoint |  API Method  | API Description | 
  |  :----:   |  :----: | :----: |
 |  ```api/searchbytag/<str:tag>```   |  ```GET``` | Return all of the art items with the given tag name | 

### To Do

* [x] Create new branch feature/search_by_tag off of practice_app.
* [x] Add the URL for the endpoint.
* [x] Create the corresponding view.
* [x] Use api decorators.
* [x] Write unittests for the API.
* [x] Test them out.
* [x] Create Pull request and assign to @KarahanS   as reviewer as stated in [meeting notes #14](https://github.com/bounswe/bounswe2022group8/wiki/Week-10-Meeting-%2314)

### Deadline

Creation: 15.05.2022 @21.00
Testing: 17.05.2022 @21.00
Review: 18.05.2022 @21.00

### Reviewers

@KarahanS

**Comment by BElifb** [comment]
* url works with the name of the tag not the id.  If you're having trouble with tag names make sure it is encoded in the url format. Such as # -> %23. For reference https://www.w3schools.com/tags/ref_urlencode.asp
* Added `urlpatterns = format_suffix_patterns(urlpatterns, allowed=['json', 'html'])`  to urls.py in order to give us the option to choose between default Response template and regular json
* Extend the url with <`?format=json`> to get json
* If you're having any trouble with your views make sure you added `format=None` to the arguments

**Comment by BElifb** [comment]
* Added tests folder to api.
* Created unit tests for search_by_tag.
* Ran the test.
* Created fake data for the test.
* Test compares the result status and the data to make sure they are equal as expected.
* Use `py manage.py test api` to run the test.

**Comment by BElifb** [comment]
* Implemented a frontend page, to get the requested tag name with user interface. Please refer to [#111 ](https://github.com/bounswe/bounswe2022group8/issues/111#issue-1236979030)

**Comment by BElifb** [comment]
* Created pull request [#114](https://github.com/bounswe/bounswe2022group8/pull/114#issue-1237522210)

**Comment by KarahanS** [comment]
With PR #128, another **tag** related functionality is added: ```api/v1/searchbytagkeyword/<str:tag>```.
It's inspired by the API endpoint given above. It returns all of the art items including the given keyword.

**Comment by BElifb** [comment]
* Changed/added some error messages for the API.
* In accordance with that added some more tests and ran them.
* Related commit [here](https://github.com/bounswe/bounswe2022group8/pull/141/commits/ce51b59e0194ec4ddf3bcf24d633ad015e8ff9a9).

**Comment by KarahanS** [comment]
Practice App Implementation is over. No action is taken, closing the issue.
