### ISSUE TITLE
Practice App: Frontend- API homepage

### ISSUE THREAD

**Issue by BElifb** [bounswe/bounswe2022group8#109]
### What's up?

As discussed in the meetings I will create a template for the homepage.

### To Do

* [x] Create the html template for homepage.
* [x] Include links for pages that will have input forms for API endpoints.
* [x] Update urls.py.

### Deadline

18.05.2022 @23.59

### Reviewers

@KarahanS  @kostanya

**Comment by BElifb** [comment]
* Created a basic template for homepage (not merged to practice_app yet).
* Waiting till I implement base template.
* **Question:** Do we want separate pages for different methods of the same endpoint?  One page per endpoint makes sense but considering some different methods are implemented by different people, might be hard to execute. (I don't mean the urls for API's themselves, for extra user interface functionalities). @KarahanS @kostanya @sinemKocoglu

**Comment by BElifb** [comment]
* All the links redirect to about page till we decide.

**Comment by KarahanS** [comment]
* For the question, It seems reasonable to separate pages for different methods of the same endpoint. For example, for different ```GET``` requests based on the **Art Items**, I will be developing different pages. Although it's not best practice obviously, I believe it makes the work easier. However, one may find implementing all the endpoints in the same page easier as well. Therefore all are allowed to implement their html pages in the way they want.
* Merged the code in ```feature/search_by_tag``` to my local. I believe listing all the url's at the beginning seems ok for now. I'll be adding my routes and push to the ```feature/artitem```.

**Comment by BElifb** [comment]
* Created pull request [#114](https://github.com/bounswe/bounswe2022group8/pull/114#issue-1237522210)

**Comment by KarahanS** [comment]
Practice App Implementation is over. No action is taken, closing the issue.
