### ISSUE TITLE
Wiki: Create Markdown Guide

### ISSUE THREAD

**Issue by KarahanS** [bounswe/bounswe2022group8#11]
**To-Do**: Create a markdown guide page that includes examples of different Markdown tricks such as creating a table, embedding an image, adding code snippets etc.

**Comment by KarahanS** [comment]
Initial markdown guide page is created. Syntax of the features will be written explicitly and new features will be added.

**Comment by KarahanS** [comment]
Collapsible Section syntax is added.

**Comment by KarahanS** [comment]
Syntax of the features are added with the last [revision](https://github.com/bounswe/bounswe2022group8/wiki/Markdown-Guide/15934118416121ea8bf540ad00e4b49282830044).

**Comment by serdarakol** [comment]
It has been reviewed, there is no further need for this issue to stay open
