### ISSUE TITLE
Practice App: Frontend- Base template

### ISSUE THREAD

**Issue by BElifb** [bounswe/bounswe2022group8#110]
### What's up?

As discussed in [meeting#16](https://github.com/bounswe/bounswe2022group8/wiki/Week-11-Meeting-Notes-16%F0%9F%97%92%EF%B8%8F), I will create a basic html base template to be extended by other templates.

### To Do

* [x] Create a base template in templates folder.
* [x] Modify any existing templates accordingly.

### Deadline

18.05.2022 @23.59

### Additional Information

Anyone volunteering to help with the frontend may get in touch through comments in this issue.

### Reviewers

@KarahanS  @mumcusena @kostanya

**Comment by BElifb** [comment]
* Created base template.
* Modified existing templates accordingly.
* Reorganized urls with respect to new convention.
* To use the base template:
    * Add  `{% extends "main/base.html" %}` in the beginning of your template.
    * Add the title inbetween `{% block title %}   right here    {% endblock %}`  (this is optional).
    * Add the contents of your page inbetween `{% block content %}   right here    {% endblock %}` .
    * That's all.

**Comment by KarahanS** [comment]
* Reviewed the templates with @kostanya, updated my HTMLs to extend the ```base.html``` and restructured the ```templates``` folder.  Templates are pulled to the repository in #114, restructured slightly in #117. New templates are added in #118.

**Comment by KarahanS** [comment]
Practice App Implementation is over. No action is taken, closing the issue.
