### ISSUE TITLE
Practice App: Frontend- Search by tag interface

### ISSUE THREAD

**Issue by BElifb** [bounswe/bounswe2022group8#111]
### What's up?

I will be creating a basic web page that uses django forms to take the tag name from the user and redirects to the related API endpoint. Hopefully setting an example for upcoming similar functionalities.

### To Do

* [x] Add the url for the page to urls.py
* [x] Create the form.
* [x] Create the view.
* [x] Create the template.
* [x] Figure out right way to redirect.

### Deadline

18.05.2022 @23.59

### Reviewers

@sinemKocoglu @KarahanS

**Comment by BElifb** [comment]
* Created `TagForm` for getting name of the tag.
* Created a url for displaying the form `searchbytag/form`.
* Created a template that uses the form (`tagform.html`).
* Created the view for the page. (`formview`).
* There were some errors with allowed methods, so I put the page in django_app rather than api, which I think is the best considering the functionalities.
* I was url encoding the tag name explicitly, turns out redirect already does that for you.
* I was having trouble with the forms (and how to use them in the views and templates), tried many variations. In the end a slightly modified version of the first one from django documentation worked.
* I put my view in the views.py in django_app, you may want to open a separate file in the same folder or perhaps in api (although I wouldn't recommend)

**Comment by KarahanS** [comment]
* There are two places we can insert our views in the project.
   * ```django_app/views.py```: This should include all the front-end related views.
   * ```api/views/```: This is a folder that will include all the REST API views.
* There are two places we can insert our urls in the project.
   * ```django_app/urls.py```: This should include:
      * ```path('', include('api.urls'))```
      *  ```path('admin/', admin.site.urls)```
      * All frontend related urls.
   * ```api/urls.py```: This should include all the API related urls. API related urls must be in the form of: ```http://127.0.0.1:8000/api/v1/<specific route>```. Fill in the route accordingly, you can of course add more branches like: ```http://127.0.0.1:8000/api/v1/artitems/users/<int:id>```

Please revise&update accordingly before the pull requests @everyone.

**Comment by BElifb** [comment]
* Created pull request [#114](https://github.com/bounswe/bounswe2022group8/pull/114#issue-1237522210)

**Comment by KarahanS** [comment]
Practice App Implementation is over. No action is taken, closing the issue.
