### ISSUE TITLE
Practice App: Feature - Delete & Edit Art Item

### ISSUE THREAD

**Issue by kostanya** [bounswe/bounswe2022group8#112]
### What's up?

Some of the endpoints for **Art Item** will be covered in this sub-issue. Please refer to #104  for list of all endpoints that will be implemented.

 |  API   |  API Method  | API Description | 
 |  :----:   |  :----: | :----: |
 |    ```api/v1/artitems/<int:id>```     |  ```DELETE```  | Delete an art item with the given ID | 

### To Do

- [x] Implement listed functionalities and corresponding APIs:
    - [x] Edit an art item with the given ID.
    - [x] Delete an art item with the given ID.
- [x] Write unittests for the APIs. Use [Faker](https://faker.readthedocs.io/en/master/) to generate mock data.
 - [x] Create Pull request and assign @sinemKocoglu as reviewer as stated in [meeting notes #14](https://github.com/bounswe/bounswe2022group8/wiki/Week-10-Meeting-%2314)

### Deadline

_18.05.2022 @23.59_

### Reviewers

@sinemKocoglu

**Comment by KarahanS** [comment]
Practice App Implementation is over. No action is taken, closing the issue.
