### ISSUE TITLE
Practice App: Feature- Users

### ISSUE THREAD

**Issue by kostanya** [bounswe/bounswe2022group8#113]
### What's up?

Some of the endpoints for **Users** will be covered in this sub-issue. Please refer to #104  for list of all endpoints that will be implemented.

 |  API   |  API Method  | API Description | 
 |  :----:   |  :----: | :----: |
 |    ```api/v1/users```   |  ```GET``` | Return all of the (non-admin) users | 
 |    ```api/v1/users```   |  ```POST``` | Create a user| 
 |    ```api/v1/users/<int:id> ```     |  ```GET```  | Return a user with the given ID | 
 |    ```api/v1/users/<int:id> ```     |  ```DELETE```  | Delete a user with the given ID | 

### To Do
- [x] Create new branch ```feature/users``` based on ```practice_app```.
- [x] Implement listed functionalities and corresponding APIs:
    - [x] Return all of the (non-admin) users.
    - [x] Return a user with the given ID.
    - [x] Edit a user with the given ID.
    - [x] Delete a user with the given ID
- [x] Write unittests for the APIs. Use [Faker](https://faker.readthedocs.io/en/master/) to generate mock data.
- [x] Create Pull request and assign @sinemKocoglu as reviewer as stated in [meeting notes #14](https://github.com/bounswe/bounswe2022group8/wiki/Week-10-Meeting-%2314)

### Deadline

_18.05.2022 @23.59_

### Reviewers

@sinemKocoglu

**Comment by KarahanS** [comment]
Merged PR [#117](https://github.com/bounswe/bounswe2022group8/pull/117), which is related to this issue.

**Comment by KarahanS** [comment]
Practice App Implementation is over. No action is taken, closing the issue.
