### ISSUE TITLE
Practice App: API Documentation

### ISSUE THREAD

**Issue by kostanya** [bounswe/bounswe2022group8#116]
### What's up?

One of our Milestone 2 deliverable is to document our API. Therefore we decided to create a documentation page in [meeting 16](https://github.com/bounswe/bounswe2022group8/wiki/Week-11-Meeting-Notes-16%F0%9F%97%92%EF%B8%8F) and work there collaboratively. 

### To Do

* Document your endpoints in accordance with the structure of the [Practice App: API Documentation](https://github.com/bounswe/bounswe2022group8/wiki/Practice-App---API-Documentation) page.

### Checklist

- [x] Elif Bayraktar
- [x] Serdar Akol
- [x] Sena Mumcu
- [x] Karahan Sarıtaş
- [ ] Mustafa Cihan
- [x] Serhat Hebun Şimşek
- [x] Doğukan Türksoy
- [x] Furkan Keskin
- [ ] Metehan Dündar
- [x] Sinem Koçoğlu

### Deadline

_18.05.2022 @23.59_

**Comment by KarahanS** [comment]
Added documentation for:
* ```GET api/v1/artitems/```
* ```GET api/v1/artitems/users/<int:id>```
* ```GET api/v1/artitems/users/username/<str:username>```
* ```GET api/v1/artitems/<int:id>```
* ```POST api/v1/artitems/```
* ```GET api/v1/episodes/<str:series>```

**Comment by sinemKocoglu** [comment]
Added documentation for:
* ```GET api/v1/comments/artitem/<int:id>```
* ```POST api/v1/comments/artitem/<int:id>```
* ```DELETE api/v1/user/<int:id>/comment/<int:commentid>```

**Comment by kostanya** [comment]
Added documentation for:
*  ``` DELETE api/v1/artitems/<int:id>``` 
*  ```GET api/v1/users``` 
*  ```POST api/v1/users```
*  ```GET api/v1/users/<int:id> ```
*  ```DELETE api/v1/users/<int:id> ``` 
*  ```GET api/v1/searchbytagkeyword/<str:tag>```

**Comment by ooodogodogodogo** [comment]
Added documentation for
GET api/v1/user/<str:username>/<str:password>

**Comment by serdarakol** [comment]
Added documentation for:
*  ``` POST api/v1/follow_user/``` 
*  ```GET api/v1/get_followers/<int:id> ```
*  ```GET api/v1/get_followers/<int:id> ```

**Comment by simsekhebun** [comment]
Added documentation for:
*  ``` GET api/v1/users/username/<str:username>```

**Comment by BElifb** [comment]
Added documentation for:
* `GET api/v1/searchbytag/<str: tag>`
*  `GET api/v1/questions/all`
*  `GET api/v1/questions/<str: tag>`

**Comment by mumcusena** [comment]
Added documentation for:
* GET api/v1/tags
* POST api/v1/tags
* DELETE api/v1/tags/<int:id>

**Comment by KarahanS** [comment]
Practice App Implementation is over. No action is taken, closing the issue.
