### ISSUE TITLE
Practice App: Requirements

### ISSUE THREAD

**Issue by mumcusena** [bounswe/bounswe2022group8#121]
### What's up?

The requirements for our Practice App must be written. I will open a Requirements page for Practice App and add it to the sidebar so we can collaboratively add requirements for the practice app.

### To Do

- [x]  Create a Requirements page for Practice App and add it to the sidebar for availability purposes. 

* Add requirements as we discussed during our meetings.

- [x] @mumcusena 
- [x] @KarahanS 
- [x] @BElifb 
- [x] @sinemKocoglu 
- [ ] @mustafa-cihan 
- [ ] @dundarmete 
- [ ] @ooodogodogodogo 
- [ ] @serdarakol 
- [ ] @simsekhebun 
- [ ] @kostanya 

### Deadline

20.05.2022 @23.59

**Comment by mumcusena** [comment]
Created the [Requirements page](https://github.com/bounswe/bounswe2022group8/wiki/Practice-App:-Requirements) for the practice app.

**Comment by mumcusena** [comment]
* Added "Tag" to the glossary.
* Added *tag* related functional requirements under user requirements. (1.1.2)

_reviewer: @sinemKocoglu_

**Comment by sinemKocoglu** [comment]
* Added comment related functional requirements.(1.1.3)
* Added a nonfunctional requirement regarding the posting comment.(1.2.2)

**Comment by BElifb** [comment]
* Added Search by tag endpoint related functional requirements (1.1.2.4.)
* Questions endpoint related functional requirements (1.1.x.2.) and (1.1.x.3.)

**Comment by KarahanS** [comment]
Practice App Implementation is over. No action is taken, closing the issue.
