### ISSUE TITLE
Milestone 2: Creating the PDF for submission

### ISSUE THREAD

**Issue by mumcusena** [bounswe/bounswe2022group8#124]
### What's up?

A pdf must be created and submitted for Milestone 2. The pdf file should include the deliverables stated in the Group Submission Document:
- [x] Group Milestone report
- [x] Requirements
- [x] Design
- [x]  URI of the Tag of your project
- [x] Code

### To Do

* Create a pdf by merging the deliverables for Milestone 2 and submit it through moodle.

### Deadline

20.05.2022 @23.59

**Comment by KarahanS** [comment]
Practice App Implementation is over. No action is taken, closing the issue.
