### ISSUE TITLE
Use Case diagram for Practice App

### ISSUE THREAD

**Issue by simsekhebun** [bounswe/bounswe2022group8#125]
### What's up?

For milestone 2 group deliverables we need to create our use case diagram for the 'Design' part. 

### To Do

* Add your API's functionality to the use case diagram [here](https://lucid.app/lucidchart/25151e69-c742-40e4-aabf-46ddd61d4c2a/edit?beaconFlowId=A801A517ADA7F714&page=.Q4MUjXso07N&invitationId=inv_203ceeda-91c1-4d54-a83b-18671bdd42cc#).

### Checklist

- [x] Elif Bayraktar
- [ ] Serdar Akol
- [x] Sena Mumcu
- [x] Karahan Sarıtaş
- [ ] Mustafa Cihan
- [x] Serhat Hebun Şimşek
- [ ] Doğukan Türksoy
- [x] Furkan Keskin
- [ ] Metehan Dündar
- [x] Sinem Koçoğlu

### Deadline

_20.05.2022 @23.59_

**Comment by KarahanS** [comment]
* Created a _Miscellaneous_ block for our external APIs.
* Created an _Art Item Management_ block for **art item** related endpoints.
* Added following actions:
   * Get information about a TV Series and list of the episodes.
   * View All art items in the System
   * View an art item by ID
   * View art items of a user by user ID 
   * View art items of a User by Username
   * Create an Art Item (for any user)
 * Established ```<<extends>>``` and ```<<includes>>``` relationships.

**Comment by sinemKocoglu** [comment]
* Created an _Comment Management_ block.
* Added following actions:
   * View comments of an art item
   * Delete comment of a user
   * Post an comment on an art item

**Comment by mumcusena** [comment]
* Created a Tag Management block for tag related endpoints.
* Added following actions:
   * List all tags.
   * Delete an existing tag.
   * Create a new tag.
   * Established <<includes>> relationships.

**Comment by simsekhebun** [comment]
*Added view a user by username

**Comment by BElifb** [comment]
Added following actions:
* Get a list of all art items that have the given tag. (includes Enter the name of the tag).
* Get a list of all unanswered stackexchange questions.
* Get a list of all unanswered stackexchange questions with the given tag. (includes Enter the name of the tag)

**Comment by KarahanS** [comment]
Practice App Implementation is over. No action is taken, closing the issue.
