### ISSUE TITLE
Sequence diagram for Practice App

### ISSUE THREAD

**Issue by simsekhebun** [bounswe/bounswe2022group8#126]
### What's up?

For milestone 2 group deliverables we need to create our sequence diagram for the 'Design' part.

### To Do

* Add your API's functionality to the sequence diagram [here](https://lucid.app/lucidchart/15b1329c-d255-4dc4-8712-a74151cd196d/edit?beaconFlowId=72E58A130D6B97D1&invitationId=inv_a8fc6663-eea2-4da7-84ea-70e6744cdbf2&page=0_0#).

### Checklist

- [x] Elif Bayraktar
- [ ] Serdar Akol
- [x] Sena Mumcu
- [x] Karahan Sarıtaş
- [ ] Mustafa Cihan
- [x] Serhat Hebun Şimşek
- [ ] Doğukan Türksoy
- [x] Furkan Keskin
- [ ] Metehan Dündar
- [x] Sinem Koçoğlu

### Deadline

_20.05.2022 @23.59_

**Comment by KarahanS** [comment]
* Created the [Sequence Diagram wiki page](https://github.com/bounswe/bounswe2022group8/wiki/Practice-App:-Sequence-Diagram).
* Added **Sequence Diagram 1: Getting list of episodes using an external API**.

**Comment by simsekhebun** [comment]
* Added **Sequence Diagram 5: Get user with an username.**

**Comment by mumcusena** [comment]
* Added **Sequence Diagram 6: List all of the available tags.**
* Added **Sequence Diagram 7: Create a new tag.**
* Added **Sequence Diagram 8: Delete an existing tag.**

**Comment by kostanya** [comment]
* Added **Sequence Diagram 9: List all users.**
* Added **Sequence Diagram 10: Get user by user ID.**
* Added **Sequence Diagram 11: Delete user by user ID.**
* Added **Sequence Diagram 12: Delete art item by art item ID.**

**Comment by BElifb** [comment]
* Added **Sequence Diagram 13: Getting a list of unanswered stackexchange questions with given tag using an external API**
*  Added **Sequence Diagram 14: Getting a list of all unanswered stackexchange questions  using an external API**

**Comment by KarahanS** [comment]
Practice App Implementation is over. No action is taken, closing the issue.
