### ISSUE TITLE
Practice App: Feature- HTML for Users

### ISSUE THREAD

**Issue by kostanya** [bounswe/bounswe2022group8#129]
### What's up?

We need to implement a simple interface for our practice_app. Therefore, User related HTML pages shall be implemented. 

### To Do

- [x] Create new branch for the implementation of _HTML for Users_ based on ```practice_app```.
- [x] Implement corresponding HTML pages.
- [x] Create Pull request and assign @sinemKocoglu as reviewer as stated in [meeting notes #14](https://github.com/bounswe/bounswe2022group8/wiki/Week-10-Meeting-%2314)

### Deadline

19.05.2022 _@17.00_

**Comment by KarahanS** [comment]
Practice App Implementation is over. No action is taken, closing the issue.
