### ISSUE TITLE
Practice App - Project Plan

### ISSUE THREAD

**Issue by sinemKocoglu** [bounswe/bounswe2022group8#132]
### What's up?

One of our Milestone 2 deliverable is project plan. Therefore we decided to create a project plan as we discussed in ps and work there collaboratively.

### To Do

* Create project plan by using project libre.

### Deadline

20.05.2022 @20.00

**Comment by mumcusena** [comment]
@sinemKocoglu has created the project plan file and added tasks and resource names. I am responsible for adding the start and finish dates of the tasks.

**To Do** : 
- [ ] Add the start and finish dates for the tasks.

**Comment by mumcusena** [comment]
I shared the project plan document with @kostanya. He will review and add final tasks.

**Comment by sinemKocoglu** [comment]
#137

**Comment by kostanya** [comment]
I added the final tasks and corresponding resources and deadlines to the project plan and created the PDF file. 
Here is the project plan for the Milesone 2: [cmpe352_milestone2.pdf](https://github.com/bounswe/bounswe2022group8/files/8741287/cmpe352_milestone2.pdf)

**Comment by kostanya** [comment]
I added the final tasks and corresponding resources and deadlines to the project plan and created the PDF file. 
Here is the project plan for the Milesone 2: [cmpe352_milestone2.pdf](https://github.com/bounswe/bounswe2022group8/files/8741509/cmpe352_milestone2.pdf)

**Comment by KarahanS** [comment]
Practice App Implementation is over. No action is taken, closing the issue.
