### ISSUE TITLE
Practice App: Feature- Search User

### ISSUE THREAD

**Issue by simsekhebun** [bounswe/bounswe2022group8#134]
### What's up?

As discussed in [meeting #14](https://github.com/bounswe/bounswe2022group8/wiki/Week-10-Meeting-%2314) I will create the API for searching users by username

### To Do

- [x] Create new branch feature/search_user off of practice app.
- [x] Add the URL for the endpoint.
- [x] Create the corresponding view.
- [x] Write unittest for the API.
- [x] Test them out.
- [x] Create Pull Request. 

### Deadline

_19.05.2022 @23.59_

### Reviewers

@mustafa-cihan

**Comment by KarahanS** [comment]
Practice App Implementation is over. No action is taken, closing the issue.
