### ISSUE TITLE
Practice App: Feature- Stackexchange Questions

### ISSUE THREAD

**Issue by BElifb** [bounswe/bounswe2022group8#139]
### What's up?

* We have decided in the previous meetings to write some functionalities that would consume external API's. I chose stackexchange API. Here the function uses the external API to get unanswered questions, then selects the ones with 0 answer count. Then returns the titles, links and tags of the questions with the given tag. There is also an option to select all unanswered questions.

### To Do

* [x] Create new branch feature/questions off of practice_app.
* [x] Add the URL for the endpoint.
* [x] Create the corresponding view.
* [x] Use api decorators.
* [x] Create a form for interface.
* [x] Create a view for interface.
* [x] Create a template for interface.
* [x] Create Pull request and assign to someone.

### Deadline

19.05.2022 @23.59

### Reviewers

@mumcusena @KarahanS

**Comment by BElifb** [comment]
* The main api is located at `api/v1/questions/<str:tag>`
* There you can directly type the name of the tag (url encoded version), and get the list of unanswered questions.
* type **all** in tag if you want to get all unanswered questions.
* Extend thr url with `?format=json` to get pure json.
* You can also use the interface that takes the tag name from the user via a django form.
* Which can be reached  here `questions/form` , or through the link in the homepage.

**Comment by BElifb** [comment]
* Implemented & used tests for questions API.

**Comment by KarahanS** [comment]
Practice App Implementation is over. No action is taken, closing the issue.
