### ISSUE TITLE
Milestone 2 Documentation: Evaluation of the tools and processes

### ISSUE THREAD

**Issue by kostanya** [bounswe/bounswe2022group8#140]
### What's up?

As stated in #137, we need to document what we have done so far in practice application. In [meeting 16](https://github.com/bounswe/bounswe2022group8/wiki/Week-11-Meeting-Notes-16%F0%9F%97%92%EF%B8%8F) we distributed tasks within the group.

### To Do

- [x] Prepare the necessary documentation for the **Milestone 2 - Group Deliverable** on the _Evaluation of Tools and Processes_ we have used to manage our team project under Google Docs available in our Discord channel.

### Deadline

19.05.2022 _@23.59_

**Comment by KarahanS** [comment]
Practice App Implementation is over. No action is taken, closing the issue.
