### ISSUE TITLE
Practice App: Dockerization

### ISSUE THREAD

**Issue by kostanya** [bounswe/bounswe2022group8#143]
### What's up?

Docker is a tool that is used to automate the deployment of applications in lightweight containers so that applications can work efficiently in different environments. Therefore, in order for our application to be more versatile we need to dockerize it before the deployment.
 
**Note:** More information related to docker can be found in our related [research page](https://github.com/bounswe/bounswe2022group8/wiki/Research-On-Docker).

### To Do

- [x] Figure out how to dockerize our practice application.
- [x] Document how dockerization is done so that other group members can benefit.

### Deadline

20.05.2022 _@12.00_

### Additional Information

* In order to dockerize our application one should perform the following steps:
   1) Download Docker. (You can download it from [here](https://www.docker.com/).) It may require you to download WSL 2, so just follow the instructions. If asked, download Ubuntu as linux distributor.
   2) Create a file named **Dockerfile** under the project folder and paste the code snippet below into the file:
    ```javascript
    FROM python:3.8-slim-buster

    WORKDIR /app

    COPY requirements.txt requirements.txt
    RUN pip3 install -r requirements.txt
    RUN apt-get update && apt-get -y install tk-dev

    COPY . .
    CMD ["python3", "manage.py", "runserver", "0.0.0.0:8000"] 
     ``` 
     * This file contains the code that is necessary to create our docker image. You can choose your python version as you wish. It better be at least 3.8 to avoid compatibility problems.
    
    3) Create a file named **.dockerignore** as we do not want our environment related files to be included. Add ``` */env ``` into the file. (Assuming that your virtual environment name is _env_. If not add that name in the format mentioned above. )
    4) Now we are going to build our docker image. Enter the following command in the terminal:
    ```javascript
    docker build --tag python-django .
    ```
    * python-django is the name of the image so you can name it however you want. 
    * Don't forget that images are immutable so in order to change it, you need to recreate it. I know that it is a quite large file but don't worry about recreating as necessary files are backed up in the cache.
    5) It is time to create our container. Enter the following command in the terminal to run your image inside a container. 
    ```javascript
    docker run --publish 8000:8000 python-django
    ```
    6) Open the Docker app you downloaded at first, click containers, move the cursor over the container you just created and click _open in browser_. **Boom.** Our application now works on linux as well.

**Comment by BElifb** [comment]
* I think it is a good idea to include 
```javascript
venv
.venv
#Ignore the git and cache folders
.git
.cache
```
in the **.dockerignore** file as well.
* This might also help with reducing the image size.
* [For more information](https://codefresh.io/blog/not-ignore-dockerignore-2/)

**Comment by KarahanS** [comment]
Practice App Implementation is over. No action is taken, closing the issue.
