### ISSUE TITLE
Practice App: Release

### ISSUE THREAD

**Issue by KarahanS** [bounswe/bounswe2022group8#149]
### What's up?

As the implementation for Practice Application is completed. Last actions must be performed for release.

### To Do

Following tasks should be handled:
- [x] Make a Github Release as described [here](https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository).
- [x] Create a tag for the application.
- [x] Provide a brief description of our application along with any major comments about the release.

### Deadline

_Deadline: 20.12.22 @23.59_

### Reviewers

@sinemKocoglu

**Comment by KarahanS** [comment]
Tag for the application is created. Please refer to [here](https://github.com/bounswe/bounswe2022group8/releases/tag/v1.1.0). A description is provided and auto-generation is utilized for additional information.

**Comment by sinemKocoglu** [comment]
I have reviewed. All seem fine. I couldn't see any error, mistake etc. Thanks for your effort!
