### ISSUE TITLE
Practice Application: Webpage Not Displaying Art Items by Username 

### ISSUE THREAD

**Issue by KarahanS** [bounswe/bounswe2022group8#150]
#### Issue description

End user is not able to get the art items using username of the owner.

#### Steps to reproduce the issue

1.  Open the application and navigate to _get art items by username_.
2.  Search for the art items of a user by username. Make sure that a user with the given username exists.
3.  It will display an error stating that user cannot be found although user exists in the database.

#### What's the expected result?

- Art items of the user

#### What's the actual result?

- Error text: Any user with the given username doesn't exist.

### To Do

- [x] Spot the bug and resolve.
- [x] Document the steps performed.

### Deadline

_Deadline: 25.05.22 @23.59_

### Reviewers

@ooodogodogodogo

**Comment by KarahanS** [comment]
## Actions taken to identify the problem:
* Run the unittests and check if there is a problem with the REST API: Successful
* Test the REST API with Postman: Successful
* Checked the HTML page to make sure it makes a request to the backend properly: Problem identified.

## Problem
In [Practice App/api/templates/artitems/list_artimes_by_username.html](https://github.com/bounswe/bounswe2022group8/blob/master/Practice%20App/api/templates/artitems/list_artimes_by_username.html), frontend was not properly making a request to the associated REST API. There was a typo in the provided url. Problem has occurred after the PR #142.
Changed the following expression:
```html
`${host}/artitems/users/username/${par}`
```
to this:
```
`${host}/api/v1/artitems/users/username/${par}`
```


Related [commit](https://github.com/bounswe/bounswe2022group8/commit/a246785bf3382154040466cee564ea966c28e470#diff-b970f8ff27409d7ed6da1b6ac2118abfca04cface81e00114115e200527bff96).
All branches are updated accordingly.

**Comment by ooodogodogodogo** [comment]
Reviewed, deployed the app with the update. Error was solved.
