### ISSUE TITLE
Time Sheet Filling

### ISSUE THREAD

**Issue by dundarmete** [bounswe/bounswe2022group8#151]
### To Do

Kindly request to fulfill weekly time sheet.

### Checklist

- [x] Elif Bayraktar
- [ ] Serdar Akol
- [ ] Sena Mumcu
- [x] Karahan Sarıtaş
- [ ] Mustafa Cihan
- [ ] Serhat Hebun Şimşek
- [x] Doğukan Türksoy
- [x] Furkan Keskin
- [ ] Metehan Dündar
- [x] Sinem Koçoğlu

### Deadline

29.05.2022 @23.59

**Comment by KarahanS** [comment]
As our work for CmpE352 finished, there is no point keeping this issue open. No further action is taken, closing the issue.
