### ISSUE TITLE
Practice App: Prevent Detection of HTML Files

### ISSUE THREAD

**Issue by KarahanS** [bounswe/bounswe2022group8#152]
### What's up?

Due to our [templates](https://github.com/bounswe/bounswe2022group8/tree/master/Practice%20App/api/templates), majority of our code in the Practice Application consists of ```HTML``` files. As a result, Github marks the most commonly used language in our repository as ```HTML```. Although it doesn't introduce any kind of problem and completely ignorable - it may be misleading for the visitors since majority of our Practice Application was implemented in Python using Django. It can be solved with an easy trick and this is also a good example for the usage of ```.gitattributes```.

### To Do

- [x] Create a ```.gitattributes``` file and add it to repository within the ```master``` branch.
- [x] Set ```linguist-detectable=false``` for ```*.html``` files. 

### Deadline

_Deadline: 09.06.22 @14.00_

### Reviewers

Reviewer: @BElifb

**Comment by KarahanS** [comment]
* Necessary actions are taken. Now our most commonly used language is marked as ```Python```.

**Comment by BElifb** [comment]
* I did't foresee, everyone using the same template example. We could've avoided this by keeping the common (css etc.) parts in the base template. But this way's definitely faster. 👍
