### ISSUE TITLE
GEN-1: New Group Member and Timesheet pages for the newcomer

### ISSUE THREAD

**Issue by MustafaEmreErengul** [bounswe/bounswe2022group8#153]
### What's up?

The new [Group Member](https://github.com/bounswe/bounswe2022group8/wiki/Mustafa-Emre-Erengül) and [Timesheet](https://github.com/bounswe/bounswe2022group8/wiki/Timesheet-Mustafa-Emre) Wiki pages were created by Mustafa Emre Erengül as a fresh group member.

### To Do

A review of a group member is required.

### Deadline

11.10.2022 @14.00

### Additional Information

The purpose of the issue is letting the team members know.

### Reviewers

@KarahanS

**Comment by KarahanS** [comment]
* [Personal wikipage](https://github.com/bounswe/bounswe2022group8/wiki/Mustafa-Emre-Ereng%C3%BCl) looks great. You can have a look at other timesheets for the general layout (table, column names and so on). Also, changed the title of the issue to use capitalized abbreviation for "GENERAL" and index of the issue. Thanks for your efforts.
