### ISSUE TITLE
GEN-2: Clean the Discord Channel

### ISSUE THREAD

**Issue by KarahanS** [bounswe/bounswe2022group8#154]
### What's up?

For this semester, we decided to continue using Discord as our main communication plan. Throughout the previous semester, our channel got a little bit messy with lots of new subchannels and various folders/images. To make our channel look less complicated, it's time to do some "spring cleaning".

### To Do

- [x] Delete the redundant subchannels.
- [x] Send invitation to the new comer(s).
- [x] If necessary, create a different subchannel for storage purposes of previous folders - which we may want to revise at some point.

### Deadline

Wednesday 12.10.22 @19.00

### Reviewers

@kostanya

**Comment by KarahanS** [comment]
Actions taken:
* Cleared out the messages in all of our text channels.
* Renamed some of the text channels.
* Removed the category

**Comment by mustafa-cihan** [comment]
We may need to add more channels We may need to add new channels as we will be divided into teams such as backend, frontend and mobile. But for now, it's good and enough. Thank you.

**Comment by KarahanS** [comment]
Added three additional categories for backend, frontend and mobile teams. Created text channels and voice channels for meetings. Looks good for now, we can add new subchannels in need as time goes by. Thanks for the reminder.

**Comment by kostanya** [comment]
Great job. It looks neat.
