### ISSUE TITLE
GEN-3: Week #1 Meeting #1 Notes

### ISSUE THREAD

**Issue by KarahanS** [bounswe/bounswe2022group8#155]
### What's up?

General issue for meeting notes documentation.

### To Do

- [x] Document the details of our first meeting for CmpE 451, what we have discussed and action items.
- [x] Add the notes to wiki homepage menu. We have to create a new subtitle called CmpE451 and put our meeting notes there.
- [x] Add the notes to the sidebar. We may divide the meeting notes category into two parts: CmpE352 and CmpE451 to avoid confusions.

### Deadline

Tuesday 11.10.2022 @19.00

### Reviewers

@sinemKocoglu

**Comment by mustafa-cihan** [comment]
Created meeting note and added it to the sidebar. Created a subcategory for CMPE451.

**Comment by sinemKocoglu** [comment]
Reviewed. No action taken. Thanks.
