### ISSUE TITLE
GEN-4: Updating Wiki pages related to the former group members

### ISSUE THREAD

**Issue by MustafaEmreErengul** [bounswe/bounswe2022group8#156]
### What's up?

Since the group members list has changed this semester, the content of some Wiki pages and the [README.md](https://github.com/bounswe/bounswe2022group8/blob/master/README.md) file have to be changed. 

### To Do

- [x] Updating [Group Members](https://github.com/bounswe/bounswe2022group8/wiki#group-members-) on the Wiki page
- [x] Updating [Timesheets](https://github.com/bounswe/bounswe2022group8/wiki#timesheets-) on the Wiki page
- [x] Updating Group Members on [README.md](https://github.com/bounswe/bounswe2022group8/blob/master/README.md)

### Deadline

11.10.2022 @14.00

### Additional Information

* A "Former Group Members" section should be added on these pages.

### Reviewers

@simsekhebun

**Comment by MustafaEmreErengul** [comment]
All necessary updates are done. Now, a review of a team member is requested.

**Comment by mustafa-cihan** [comment]
It is complete. No further action required.
