### ISSUE TITLE
GEN-5: Adding CmpE451 section to the personal Timesheet pages

### ISSUE THREAD

**Issue by MustafaEmreErengul** [bounswe/bounswe2022group8#157]
### What's up?

Since a brand new semester has started, Timesheets have to have two sections which differentiate CmpE352 and CmpE451.

### To Do

* "CmpE451" section should be added for the new semester.
* The meetings of the last semester should be gathered as "CmpE352" section.

### Checklist

- [x] Elif Bayraktar
- [ ] Serdar Akol
- [ ] Sena Mumcu
- [X] Karahan Sarıtaş
- [x] Mustafa Cihan
- [x] Serhat Hebun Şimşek
- [x] Doğukan Türksoy
- [x] Furkan Keskin
- [x] Sinem Koçoğlu
- [x] Metehan Dündar
- [X] Mustafa Emre Erengül

### Deadline

11.10.2022 @14.00

### Additional Information

* After the changes are done, please mark the checklist.

### Reviewers

@ooodogodogodogo

**Comment by mustafa-cihan** [comment]
I added the CMPE352 Meeting Notes and CMPE451 Meeting Notes categories to the sidebar.

**Comment by BElifb** [comment]
* Moved CMPE451 Meeting Notes earlier in the sidebar as it will be more relevant. I recommend the same for the personal timesheet pages as well.
* Unrelated, we might wanna reconsider the whole ordering of the sidebar, turn some things into dropdown etc.

**Comment by KarahanS** [comment]
Deadline is already passed. May I kindly remind you to take the necessary actions and mark the checkbox from the list @serdarakol, @mumcusena, @simsekhebun, @ooodogodogodogo, @dundarmete ? Thanks.

**Comment by KarahanS** [comment]
Deadline has passed. No further action is taken. Closed the issue.
