### ISSUE TITLE
GEN-6: A new group photo for the new semester

### ISSUE THREAD

**Issue by MustafaEmreErengul** [bounswe/bounswe2022group8#158]
### What's up?

* A new version of the group photo is needed for CmpE451.

### To Do

* During a group meeting (either online or in-class) a photo or screenshot could be taken. 

### Deadline

18.10.22 @14.00

### Additional Information

* It can be done during next week's meeting.

### Reviewers

@mumcusena

**Comment by dundarmete** [comment]
To make a great photo, it is highly recommended to attend Sunday's meeting.

**Comment by MustafaEmreErengul** [comment]
The group photo is created artificially due to extreme circumstances. No further action is required, closing the issue.
