### ISSUE TITLE
GEN-7: Update the Communication Plan

### ISSUE THREAD

**Issue by KarahanS** [bounswe/bounswe2022group8#159]
### What's up?

Communication plan must be updated in accordance with the decisions we have taken in our first meeting. Since we are not divided into technical teams (backend-frontend-mobile) yet, time of the meeting for individual teams will be left empty for now. Please refer to the communication plan from [here](https://github.com/bounswe/bounswe2022group8/wiki/Communication-Plan).

### To Do

- [x] Update the general meeting hours and communication medium.
- [x] Add new layers for team-only meetings.

### Deadline

22.10.2022 @19.00

### Reviewers

@MustafaEmreErengul

**Comment by KarahanS** [comment]
Updated the [communication plan](https://github.com/bounswe/bounswe2022group8/wiki/Communication-Plan).

**Comment by mustafa-cihan** [comment]
I think we should make team meeting hours flexible like one week it starts at Wed 17.00 the other week it starts Tuesday 20.00.

**Comment by MustafaEmreErengul** [comment]
Each team is expected to enter their weekly meeting time to the chart, if necessary it could be changed by the team but one tentative time/date makes the meetings more robust.

**Comment by KarahanS** [comment]
Updated the deadline since teams haven't decided their own meeting dates yet.

**Comment by dundarmete** [comment]
Slack should be replaced with another platform to communicate with the professor easily.

**Comment by KarahanS** [comment]
Removed _Slack_ from the table.

**Comment by MustafaEmreErengul** [comment]
Let us ask the professor whether we can use Piazza to communicate with her or not

**Comment by suzan-uskudarli** [comment]
Piazza has a fee now right?
Used to be free.

**Comment by MustafaEmreErengul** [comment]
Since the Piazza platform has a fee now, it is better to use free alternatives. We can also use GitHub to communicate with professor by mentioning her.

**Comment by MustafaEmreErengul** [comment]
Tentative weekly meeting schedule for Mobile team is added now.

**Comment by KarahanS** [comment]
Frontend is left folk @kostanya @sinemKocoglu @simsekhebun

**Comment by kostanya** [comment]
Added tentative date for the Frontend team.

**Comment by KarahanS** [comment]
Closed the issue.
