### ISSUE TITLE
Submit HW 1 : Infrastructure Setup on Moodle

### ISSUE THREAD

**Issue by ooodogodogodogo** [bounswe/bounswe2022group8#16]
**To Do:** Submit HW 1 on moodle according to its description **(DEADLINE: 08.03.2022 10:00 AM)** : 

"Upload a document that summarizes the actions you took for this homework, including (but, not limited to):

* URLs to the issues you created
* URLs to the research items
* Time tracking"

- [x] Serdar Akol
- [x] Karahan Sarıtaş
- [x] Sena Mumcu
- [x] Mustafa Cihan
- [x] Serhat Hebun Şimşek
- [x] Elif Bayraktar
- [x] Doğukan Türksoy
- [ ] Furkan Keskin
- [ ] Metehan Dündar
- [x] Sinem Koçoğlu

**Comment by KarahanS** [comment]
The deadline stated in the description expired.
