### ISSUE TITLE
GEN-8: Week #2 Meeting #2 Notes

### ISSUE THREAD

**Issue by KarahanS** [bounswe/bounswe2022group8#160]
### To Do

* Take notes during the meeting.
* Create the wiki page.
* Add links to [Sidebar](https://github.com/bounswe/bounswe2022group8/wiki/_Sidebar/_edit) and [Homepage](https://github.com/bounswe/bounswe2022group8/wiki).

### Deadline

16.01.2022 @18.00

### Reviewer
@sinemKocoglu

**Comment by KarahanS** [comment]
* Added [Week #2 Meeting Notes #2](https://github.com/bounswe/bounswe2022group8/wiki/Week-2-Meeting-%232) to wiki. Assigned a reviewer but any team member is encouraged to have a look and confirm or make additions in case of anything missing in the notes.

**Comment by kostanya** [comment]
It was a quite intense kick-off meeting. As far as I could see, it covers everything necessary. Thank you very much for the detailed notes and explanations. The only thing I can add is to remind the people concerned not to forget to open the issues we discussed during the meeting.

**Comment by KarahanS** [comment]
Thanks. Btw, forgot to mention about the addition of our project planning to sidebar. Added that to the meeting notes as a task assigned to you.

**Comment by BElifb** [comment]
Added questions and answers update as an action item.

**Comment by KarahanS** [comment]
No further action is taken.
