### ISSUE TITLE
GEN-12: Update Issue Template

### ISSUE THREAD

**Issue by BElifb** [bounswe/bounswe2022group8#164]
### What's up?

With the addition of our new member, group checklist issue template needs to be updated.

### To Do

* Update group checklist issue template to include our new member.

### Deadline

15.10.2022 @24.00

### Reviewers

@MustafaEmreErengul

**Comment by BElifb** [comment]
* Template updated. Checked by trying to create new group checklist issue. Can you also test it out @MustafaEmreErengul ?

**Comment by MustafaEmreErengul** [comment]
The template has all members of the group now. Since the problem is fixed, the issue is going to be closed.
