### ISSUE TITLE
GEN-13: Update Questions and Answers

### ISSUE THREAD

**Issue by BElifb** [bounswe/bounswe2022group8#165]
### What's up?

Questions and answers page is where we will be gathering our questions about the project, to ask the instructor and/or the assistant. The page needs to be updated to meet CMPE451 needs.

### To Do

* Update questions and answers page to meet CMPE451 needs.

### Deadline

16.10.2022 @18.00

### Reviewers

@KarahanS

**Comment by BElifb** [comment]
* Questions and answers page is updated to have CMPE352 and CMPE451 sections.
* Also added an agenda section to collect topics to be discussed in the next group meeting.
* Updated the sidebar accordingly.
* New page can be found under the name [Agenda & Questions](https://github.com/bounswe/bounswe2022group8/wiki/Agenda-&-Questions-&-Answers)

**Comment by KarahanS** [comment]
That's a great idea to leave some space for agenda. This way, we can note down some of the things we have in mind to discuss in the meetings. Page looks great, let's keep the issue open for a while in case anyone makes some addition to the questions.

**Comment by KarahanS** [comment]
No further action is taken. Closing the issue. Of course, everyone is welcomed to add any question in mind to the section [Questions & Answers](https://github.com/bounswe/bounswe2022group8/wiki/Agenda-&-Questions-&-Answers)
