### ISSUE TITLE
GEN-14: Revise the Bidding System

### ISSUE THREAD

**Issue by KarahanS** [bounswe/bounswe2022group8#166]
### What's up?

Within the scope of #162, we are expected to revise the _Bidding System_ subtitle under the System Requirements and develop possible improvements.

### To Do

- [x] Revise the _Bidding System_ related System Requirements.
- [x] Share your ideas with other team members in the next meeting on 16.10.22 @18.00.

### Deadline

16.10.22 @18.00

### Reviewers

@kostanya

**Comment by BElifb** [comment]
* Reqirements are unclear about whether a bidder can see the offer amount of the other bids.
* Related to the issue above, we currently do not require a new bid to exceed current maximum bid. It could be wise to add this requirement. (1.2.4.10)
* I also don't think that it is absolutely necessary to provide the bidder with the ability to specify duration for the bid. (1.2.4.10, 1.2.4.11)
* Changes postphoned until other assignees revisions.

**Comment by KarahanS** [comment]
* I think there should be a price attached to the art item on sale, which is the highest price given. It must be visible by other registered users. Should it be visible to guest users as well? Btw, I don't think a bidder should be able to see all bids. It's enough to see the highest one.
* Agreed.
* Agreed. I think we should just discard it. Seller already determines a period of time for his art item to be on sale. No need to adjust another timer for the bids. (Although, I don't think that would be something hard to implement.)

Additionally,
* On 1.2.4.16, we mentioned about sorting according to the price while listing the art items. Which price is this? The highest price? Should we able to list the art items that are not saled yet, or art items that were never put on sale in the first place? This article seems very vague to me.
* 1.2.4.18, Do we refer to normal chat here? Additionally, we can convert the sections related to chat to _should_. I can't really estimate the difficulty of implementing a chat system.

**Comment by BElifb** [comment]
* 1.2.4.16 Refers to sellers being able to see (& sort) the previous bids on a specific art item that is (or was) on sale. Since we did not have bids exceeding max current bid requirement before sorting according to price and date could have given different results. But it won't matter now. Updating 1.2.4.16 accordingly.
* Judging by the reference to 1.1.4 I think private messages refers to regular private messages (aka chat) that we have. The chat part in this article is already written with _should_.

**Comment by BElifb** [comment]
* Updated the bidding system in accordance with the last general meeting's decisions.
* Some of the items about notifications might be repeats of the notification section, should we remove them ?
* Could you please review the updated version @KarahanS @mumcusena

**Comment by KarahanS** [comment]
* Can a bidder bid a smaller amount of money than the current highest bid on an art item? According to here, he can:
> Registered users shall have the option to bid (make an offer) on art items, via specifying amount, provided that the item is open for sale and that the amount matches or exceeds the minimum price set by the seller.
What did we talk about this?
* In addition, what was our decision as to the visibility of the highest bid on the art item? I feel like we determined that the highest price must be visible to the bidders and they are allowed to bid more than the current maximum. We talked a lot about this stuff and it became a little bit of "çorba". My suggestion is to take note of these questions somewhere (maybe in [Question & Agenda](https://github.com/bounswe/bounswe2022group8/wiki/Agenda-&-Questions-&-Answers) section) and talk about them later. Or we can talk about them again. 
* Waiting for a response, not closing the issue for now.

**Comment by BElifb** [comment]
> * Can a bidder bid a smaller amount of money than the current highest bid on an art item? According to here, he can:
> 
> > Registered users shall have the option to bid (make an offer) on art items, via specifying amount, provided that the item is open for sale and that the amount matches or exceeds the minimum price set by the seller.
> > What did we talk about this?
> 
* As far as I remember the last decision was that bidders had the option to bid smaller amounts than the current max. This was related to the fact that max bid amount was not visible. That's why I didn't change that part.

> * In addition, what was our decision as to the visibility of the highest bid on the art item? I feel like we determined that the highest price must be visible to the bidders and they are allowed to bid more than the current maximum. We talked a lot about this stuff and it became a little bit of "çorba". My suggestion is to take note of these questions somewhere (maybe in [Question & Agenda](https://github.com/bounswe/bounswe2022group8/wiki/Agenda-&-Questions-&-Answers) section) and talk about them later. Or we can talk about them again.
> * Waiting for a response, not closing the issue for now.
* I am having to agree with the "çorba" comment. Again I remembered that we decided not to show the max bid and hence the ability to bid below it. I think discussing this further won't get us anywhere as I believe there are no original points left to be made. So we should make an executive decision and say that it stays as is?

**Comment by KarahanS** [comment]
Probably I'm mistaken. We can leave it as it is. Closing the issue.
