### ISSUE TITLE
GEN-16: Revise Profile Management 

### ISSUE THREAD

**Issue by sinemKocoglu** [bounswe/bounswe2022group8#168]
### What's up?

Refer to #162, revise the _Profile Management_ subtitle under the User Requirements and come up with improvements.

### To Do

- [x] Revise the _Profile Management_ related User Requirements.
- [x] Share your ideas with other team members in the next meeting on 16.10.22 @18.00.

### Deadline

16.10.22 @18.00

**Comment by sinemKocoglu** [comment]
I revised the indexes to categorize the requirements for better understanding and clear view, that means I put requirements under 4 main requirements such as personal info, personal attributes, settings, and advanced operations.

**Comment by KarahanS** [comment]
Thanks for the effort, we may need to update indices of the requirements in our mockups as well. Referencing #171 as a reminder.

**Comment by kostanya** [comment]
Removed _1.1.3.1. Registered users shall have a profile page with some functionalities provided below_ as there were nothing below it, and reorganized and rewrote some parts of the items without causing a profound effect on the meaning. In short, I left Sinem's categorisation as it is, since I think that the current items are necessary and sufficient.

**Comment by KarahanS** [comment]
Hey folk, It appears that we didn't mention about the _gallery_ section of a profile in our platform. This is simply a page that keeps the collection of all art items posted by that user. I remember talking about this a lot but I'm surprised that we didn't note it down. Could you please add a couple of articles about that? I think, one can _filter_ or _sort_ his art items in the gallery but I don't know whether or not we should keep it as _should_ or _shall_. One can _filter_ his art items by _copyright situation_, _tag_, _type_, _title_ and so on. He can _sort_ them according to number of _comments_ received, _likes_ received etc. I think if we properly provide a generic communication between frontend and backend at this point, it becomes very easy to sort or filter according to any parameter.

**Comment by kostanya** [comment]
We should discuss this in more detail during the meeting and then we can take the necessary actions.

**Comment by KarahanS** [comment]
* Removed `1.1.3.3.2.` (which was about art item visibility)

**Comment by sinemKocoglu** [comment]
No further action taken.
