### ISSUE TITLE
GEN-17: Revise Exhibition

### ISSUE THREAD

**Issue by sinemKocoglu** [bounswe/bounswe2022group8#169]
### What's up?

Refer to #162, revise the _Exhibition_ subtitle under the User Requirements and come up with improvements.

### To Do

- [x] Revise the _Exhibition_ related User Requirements.
- [x] Share your ideas with other team members in the next meeting on 16.10.22 @18.00.

### Deadline

16.10.22 @18.00

**Comment by sinemKocoglu** [comment]
Requirements under _Exhibition_  organized in terms of exhibition organizer, collaborator, and attendee. Indexes fixed accordingly. No requirements added.

**Comment by kostanya** [comment]
I reviewed our project description and I think we overcomplicated the exhibition system. The description mentions the following about the exhibitions: 
* In this project, users can ... and make exhibitions **solo** or **collaboratively**. 
* In addition to **online galleries**, artists can also open **physical exhibitions**, and **notify its followers** via this platform as an event.
* People can attend these exhibitions, and mark their geographic locations via the platform using geotagging.
* The platform should recommend any other events of the users’ interests based on their geotag history.
* The popularity will be measured by the number of ... and art exhibitions.

Last three are mainly related to geotagging, recommendation system and popularity. Just the first two items are directly related to the exhibiton system. 

In my opinion, there are two fundemental unnecessities in our requirements related to exhibition system:
* In the case of a collaborative exhibition, when an artist organises an exhibition, other people should not be able to say that they also want to collaborate. If an exhibition is to be organised, it is much more logical for the organisers to agree in advance.
* There is no need to distinguish between the collaborator and the exhibition organiser. There should be just organisers and attendees. 

In accordance with what I have written above, I suggest removing:
* _1.1.6.1.1. Exhibition organizers shall be able to add other users to the exhibition as collaborators or exhibition organizers._
* _1.1.6.1.7. Exhibition organizers shall be able to approve/reject art items added to the exhibition by participants._
* _1.1.6.2. Registered users shall colloborate on an exhibition by the consent of the exhibition organizer._

**Comment by sinemKocoglu** [comment]
- _1.1.6.1.1. Exhibition organizers shall be able to add other users to the exhibition as collaborators or exhibition organizers._
- _1.1.6.2. Registered users shall colloborate on an exhibition by the consent of exhibition organizers._

revised as below by concerning not to contradict use case diagram.

- _1.1.6.1.1. Exhibition organizers shall be able to add other users to the exhibition as collaborators._
- _1.1.6.2. Registered users shall colloborate on an exhibition by accepting the invitation of exhibition organizers._

What's more, in all senarios indexes of exhibition-related requirements fixed.

**Comment by sinemKocoglu** [comment]
Necessary updates made.
