### ISSUE TITLE
GEN-19: Revise Mockups

### ISSUE THREAD

**Issue by kostanya** [bounswe/bounswe2022group8#171]
### What's up?

As mentioned in the Kickoff Assignment, we need to revise and update our mock-ups after the revision of the requirements. 

### To Do

* Review the mock up scenarios, preferably those in which you were least involved. 
* Compare the requirements of the scenarios with the updated requirements. 
* Look critically at which features of the scenarios we can implement and to what extent.

### Scenarios and Mockups

- [x] Art Follower
- [x] Artist
- [x] Collaboration

### Deadline

20.10.2022 _@23.59_ 

### Reviewers

@BElifb

**Comment by sinemKocoglu** [comment]
Collaboration updated according to latest situation of the requirements. If you make any change in requirements, please update scenarios&mockups as well.

**Comment by sinemKocoglu** [comment]
Anyone is encouraged to revise the rest of the mockups. @dundarmete @ooodogodogodogo @serdarakol @BElifb @KarahanS @mustafa-cihan @MustafaEmreErengul @mumcusena @simsekhebun

**Comment by KarahanS** [comment]
@serdarakol is assigned for the revision of rest of the mockups. Added him as an assignee.

**Comment by serdarakol** [comment]
I ve checked and revised all of the mockup scenarios. All of them are updated

**Comment by KarahanS** [comment]
Hi @serdarakol, in [Art Follower User](https://github.com/bounswe/bounswe2022group8/wiki/Scenario:-Art-Follower-User) scenario, I found an inconsistency. In the scenario we show `login` functionality but in the requirements we mention about `register` rather than `login`. Could you check and make the necessary corrections?

**Comment by serdarakol** [comment]
> Hi @serdarakol, in [Art Follower User](https://github.com/bounswe/bounswe2022group8/wiki/Scenario:-Art-Follower-User) scenario, I found an inconsistency. In the scenario we show `login` functionality but in the requirements we mention about `register` rather than `login`. Could you check and make the necessary corrections?

Thank you for the review. Necessary change is done

**Comment by KarahanS** [comment]
A similar inconsistency can be observed in [Artist](https://github.com/bounswe/bounswe2022group8/wiki/Scenario-2). FYI @serdarakol

**Comment by BElifb** [comment]
* There are also the parts about art item visibility and the offer deadlines in the mockup visuals for Artist scenario.
* Since we got rid of those parts in the requirements, I am just going to cover those parts in the visuals.

**Comment by serdarakol** [comment]
Am I missing something, they look fine now @KarahanS @BElifb

**Comment by BElifb** [comment]
> Am I missing something, they look fine now @KarahanS @BElifb

I made the changes I mentioned to the visuals. I didn't check what Karahan was mentioning about the requirement items though.

**Comment by KarahanS** [comment]
Seems ok now.

**Comment by BElifb** [comment]
With the last checks done, closing the issue.
