### ISSUE TITLE
GEN-20: Revise User Interaction and Guest Users

### ISSUE THREAD

**Issue by kostanya** [bounswe/bounswe2022group8#172]
### What's up?

As mentioned in #162, revise the _User Intereaction_ and _Guest Users_ subtitles under the User Requirements and come up with improvements.

### To Do

- [x] Revise the _User Interaction_ related User Requirements.
- [x] Revise the _Guest Users_ related User Requirements.
- [x] Share your ideas with other team members in the next meeting on 16.10.22 @18.00.

### Deadline

16.10.2022 _@18.00_

**Comment by kostanya** [comment]
Reviewed _1.1.2 Guest Users_, no actions are taken. All requirements are clearly explained and seem necessary to me.

**Comment by kostanya** [comment]
Reviwed _1.1.4 User Interaction_. Following points are noted for discussion at the next meeting:
* **Comment editing feature:** (_1.1.4.8. Registered users shall be able to edit their comments. Same functionality applies for replies.)_
* **Chatting feature:** (_1.1.4.10. Registered users shall be able to chat with other users. They shall be able to send and receive private messages._) We may want to elaborate on the chatting feature.

Other than these, I think all the requirements related to _1.1.4. User Interaction_ are necessary and sufficient.

**Comment by serdarakol** [comment]
I ve also reviewed the requirements, @kostanya you have pointed goof points. I aggree all of you mentioned except the chatting feature. It should stay, I think. 

Plus, 
* Comment replying feature: (11.1.4.7. Registered users shall be able to reply to a comment. Reply is also considered as a comment.)

we can discuss it in our weekly meeting and take the necessary action

**Comment by KarahanS** [comment]
* Removed the private visibility feature mentioned in the definition of the _follower_.
* Removed `1.1.4.3.2.` (t was rielated to setting the art item visibility while uploading an image)

**Comment by sinemKocoglu** [comment]
Thanks for your effort.
