### ISSUE TITLE
GEN-21: Create a Wikipage for Conventions

### ISSUE THREAD

**Issue by KarahanS** [bounswe/bounswe2022group8#173]
### What's up?

We've been using some conventions for issues (namings, contents and so on) for a while although we didn't really feel the necessity to document them in detail. Since the number of conventions we have to comply with increases, it's important to create a separate wiki page to document them.

### To Do

- [x] Create a wikipage for general conventions and development practices.
- [x] Attach the wikipage to the proper subtitle in sidebar (_Project_ subtitle seems to be the correct position)
- [x]  Content of this page may include but not is limited to:
   * Issue conventions (naming, content of the issues, reviewer policies etc.)
   * Code conventions (formatting and so on - this part will be filled by the development teams throughout the implementation)
   * Git conventions (branch naming conventions etc. - haven't talked yet, but we'll talk about this in the next meeting)

### Deadline

16.10.2022 @18.00

### Reviewers

@MustafaEmreErengul

**Comment by KarahanS** [comment]
Deadline has passed. Can I kindly remind you take necessary actions?

**Comment by MustafaEmreErengul** [comment]
Since all conventions mentioned above are written in the Wiki page now, no further action is required. Revision is done, closing the issue.
