### ISSUE TITLE
GEN-22: Revise Search

### ISSUE THREAD

**Issue by dundarmete** [bounswe/bounswe2022group8#174]
### What's up?

Refer to #162, revise the _Search_ subtitle under the System Requirements and come up with improvements.

### To Do

- [x] Revise the _Search_ related System Requirements.
- [x] Share your ideas with other team members in the next meeting on 16.10.22 @18.00.

### Deadline

22.10.22 @19.00

### Reviewers

@KarahanS

**Comment by KarahanS** [comment]
In our meeting on 16.10.2022, we haven't make any change on requirements related to _Search_. For now, we'll continue with it as it is. Closing the issue.
