### ISSUE TITLE
GEN-23: Revise Location

### ISSUE THREAD

**Issue by dundarmete** [bounswe/bounswe2022group8#175]
### What's up?

Refer to #162, revise the _Location_ subtitle under the System Requirements and come up with improvements.

### To Do

- [x] Revise the _Location_ related System Requirements.
- [x] Share your ideas with other team members in the next meeting on 16.10.22 @18.00.

### Deadline

22.10.22 @19.00

### Reviewers

@KarahanS

**Comment by sinemKocoglu** [comment]
Requirement 1.2.6.1 is updated as

-  _1.2.6.1. The system shall be able to keep a record of users' locations when they share by using geotagging._

to remove ambiguity.

**Comment by MustafaEmreErengul** [comment]
The Location part of the Requirements is revised in the team meeting, and the related section is updated by @sinemKocoglu. Now a review of a team member is needed. @BElifb

**Comment by KarahanS** [comment]
We have updated one of the requirements to remove the ambiguity. No further action is taken, closing the issue.
