### ISSUE TITLE
GEN-25:Revise the Copyright Infringement Requirement

### ISSUE THREAD

**Issue by ooodogodogodogo** [bounswe/bounswe2022group8#178]
### What's up?

As mentioned in #162, we revised the Copyright Infringement requirement subtitle under the User Requirements and came up with improvements. We shared our ideas with the team and made some changes.

### To Do

 - [x] Revise the Copyright Requirement under the User Requirements (1.1.5)
 - [x] Share your ideas with other team members in the next meeting on 16.10.22 @18.00.
 - [x] Made the revisions of Copyright Requirement under the User Requirements (1.1.5)

### Deadline

18.10.2022 @ 14.00

### Reviewers

@kostanya

**Comment by ooodogodogodogo** [comment]
As we discussed at [Week2 - Meeting #3 (16.10.2022 )](https://github.com/bounswe/bounswe2022group8/wiki#:~:text=Week2%20%2D%20Meeting%20%233%20(16.10.2022) Copyright Infringement requirements are changed such as a moderator can remove an art item directly. Modified status of requirements are here : 

- 1.1.5.4. A moderator shall be able to ban a user if moderator(s) decided that a user constantly uploads art items that infringe copyrights or constantly uploads art items that are labeled as inappropriate content.
- 1.1.5.5. A moderator shall be able to remove an art item that was mentioned in the copyright ticket.

This issue is ready for revision.

**Comment by KarahanS** [comment]
No further action is taken, closing the issue.
