### ISSUE TITLE
FE-1: Meeting Notes: Week#3 Frontend Meeting#1

### ISSUE THREAD

**Issue by sinemKocoglu** [bounswe/bounswe2022group8#184]
### To Do

* Take notes during the meeting.
* Create the wiki page.
* Add links to Sidebar and Homepage.

### Deadline

25.10.2022 @15.00

### Additional Information

Reviewer
@simsekhebun

**Comment by kostanya** [comment]
Finally I was able to put my notes on the wiki. Week 3 Frontend Meeting Notes can be found [here.](https://github.com/bounswe/bounswe2022group8/wiki/Week-3-Frontend-Meeting-Notes-1)
