### ISSUE TITLE
FE-2: Research on Frontend Tools

### ISSUE THREAD

**Issue by sinemKocoglu** [bounswe/bounswe2022group8#185]
### What's up?

As discussed in the first frontend meeting , to create the frontend of the project and the first design of login, signup, and homepage do research on tools for design and other helpful tools compatible with React,js.

### To Do

- React.js
- Design Templates
- Tools to format files
- Css and bootstrap

### Deadline

23.10.2022 @18.00

**Comment by sinemKocoglu** [comment]
Some useful links for the beginning:
* https://blog.openreplay.com/using-css-modules-in-react/
* https://www.freecodecamp.org/news/how-to-style-react-apps-with-css/
* https://getbootstrap.com/docs/5.0/getting-started/introduction/
* https://prettier.io/
* https://reactjs.org/docs/create-a-new-react-app.html

**Comment by kostanya** [comment]
Created a research page for frontend tools and added it to the sidebar and the home page. As a starter, added the above links to the page.
