### ISSUE TITLE
BE-4: Setting up initial models

### ISSUE THREAD

**Issue by BElifb** [bounswe/bounswe2022group8#187]
### What's up?

In the last general meeting we decided to implement the most essential models, so that we can get started with API implementations and other necessary features of the app. We discussed and decided to further research ways of implementing the user class(es). 

### To Do

* Research different ways of implementing the user class to make maximum use of django's authentication & autharization systems while achieving the level of customization we need.
* Compare with last year's practice app models and see what kinds of updates we need.
* Install PostgreSQL and set up database as in #182 
* Implement the User class(model) with additional fields.
* Implement any other classes that are necessary in the initial stages.

### Deadline

23.10.2022 @12.00

### Reviewers

@KarahanS @mumcusena @dundarmete

**Comment by BElifb** [comment]
* Here are a few useful resources I found while researching:
  * https://simpleisbetterthancomplex.com/tutorial/2016/07/22/how-to-extend-django-user-model.html#onetoone
  * https://docs.djangoproject.com/en/4.1/topics/auth/customizing/
  * https://simpleisbetterthancomplex.com/tutorial/2018/01/18/how-to-implement-multiple-user-types-with-django.html
* Created User class by extending AbstractUser, also created Tag, ArtItem and Comment classes.
* Added AUTH_USER_MODEL to settings.py. Also, prefer to create foreign keys to the User model importing the settings from django.conf import settings and referring to the settings.AUTH_USER_MODEL instead of referring directly to the custom User model. 
* Installed Pillow package for the media files and updated requirements.txt with the latest additions.
* Configured MEDIA_ROOT in settings.py and added MEDIA folder with default images.

**Comment by KarahanS** [comment]
> Configured MEDIA_ROOT in settings.py and added MEDIA folder with default images.
I'm not sure but this change may lead to conflict with the [PR](https://github.com/bounswe/bounswe2022group8/pull/189) because I also made some changes on settings. Could you please apply those changes and make sure that it's working on your local working environment? (To simply put, I created a settings folder and put two different database configurations for development (local) and production (docker & aws))

**Comment by BElifb** [comment]
* Created serializers for the models.
* Created a decorator to check whether the user is active_user or not.  There are some things to keep in mind here:
  *  Current redirection path for the decorator is 'login', but we can configure this later as the project structure is more defined.
  * is_active and is_active_user are two seperate concepts. First refers to user's account not being blocked (we'll use this when there are complaints about the account and the admin/moderator decides to ban the user), second (is_active_user) refers to user having a level 2 acoount.
* Created and configured the admin site.
* Tested creating users via admin site, fixed media root.

**Comment by BElifb** [comment]
> > Configured MEDIA_ROOT in settings.py and added MEDIA folder with default images.
> 
> I'm not sure but this change may lead to conflict with the [PR](https://github.com/bounswe/bounswe2022group8/pull/189) because I also made some changes on settings. Could you please apply those changes and make sure that it's working on your local working environment? (To simply put, I created a settings folder and put two different database configurations for development (local) and production (docker & aws)). Take the change in `manage.py` and `python manage.py runserver` should work as usual.

* I don't think the media settings are very cruicial at the moment. We can fix them later if there are any problems.
* But my concern is there more references to settings.py in other places, would they still work with the changed structure?
* Also i am done with the initial version of the models, I didn't add follow etc. as I recall we scheduled it for a later time. I was thinking maybe it would be better to merge BE-4 first, so that we can get going with the API implementations. I am going to go through your instructions for docker, but looks like it is going to take me a while.

**Comment by KarahanS** [comment]
* Ok
* ```Settings.py``` is referenced from ```manage.py``` only once. ```feature/BE-5``` is working on my machine, but we can deal with problems if we encounter any in the future.
* Ok, I'll be reviewing BE-4 very quickly.

**Comment by BElifb** [comment]
* Created basic homepage.
* Added base and index templates to newly created folder in API app.
* Added redirection to admin site.

**Comment by BElifb** [comment]
* Don't forget to clean your database and delete any previous migrations you may have, since extending the AbstractUser will change the whole database schema.
* Don't forget to install Pillow. (You can just run `pip install -r requirements.txt`)

**Comment by KarahanS** [comment]
PR is merged, no further action is taken.
