### ISSUE TITLE
BE-5: Dockerize the Django Application with PostgreSql

### ISSUE THREAD

**Issue by KarahanS** [bounswe/bounswe2022group8#188]
### What's up?

Docker is a tool that is used to automate the deployment of applications in lightweight containers so that applications can work efficiently in different environments. Therefore, in order for our application to be more versatile we need to dockerize it before the deployment.
 
**Note:** More information related to docker can be found in our related [research page](https://github.com/bounswe/bounswe2022group8/wiki/Research-On-Docker).

In contrast to the [Practice App](https://github.com/bounswe/bounswe2022group8/tree/master/Practice%20App), this time we also have to dockerize our PostgreSql database - which requires us to use `docker-compose.yml` file in addition to a `Dockerfile`.

### To Do

- [x] Dockerize the Django application with a persistent PostgreSql database.
- [x] Enrich the [README] to include the steps to follow in order to Dockerize the application.
- [x] Explain some of the important changes (development/production settings) in the issue description as well as in PR.

### Deadline

25.02.2022 @18.00

## How to Dockerize
Let me share the steps below to dockerize the application:
`Dockerfile` and `docker-compose.yml` files are alread provided for you. Dockerizing our project is important for the deployment stage where we want our database to be stable and consistent between different runs for each use. To dockerize the application, use the following commands:
* First of all, you must install the Docker Desktop from [here](https://www.docker.com/). It may require you to download WSL 2, so just follow the instructions. If asked, download Ubuntu as linux distributor.
* I strongly suggest you to install the Docker extension for VS Code. It makes visualizing what's going on with the containers much more easier.
* Firstly, build the `Dockerfile`. Let's give it a name with the `--tag` flag:
   ```cmd
   docker build --tag python-django .
   ```
   If you don't give it a name, its name will be some random gibberish. As a result of the build, a container will be created. A container simply corresponds to a Linux environment where a copy of our application resides.
* Now, we should proceed with running our `docker-compose.yml` file. `docker-compose.yml` file helps us to define the services we want to run in our container. We have two services in our application: `web` and `db`. We also use `volume` to persist data even if service is interrupted (which is extremely important for production). You can both **build** and **run** the `docker-compose.yml` with the following command:
   ```cmd
   docker-compose up -d --build
   ```
   `-d` flag runs the services in detach mode so that they don't block the terminal. You can open their own terminal from the VS Code Docker extension. `--build` flag builds the project from scratch. It's important to use this flag if you make any changes on the code and want them to be reflected on your dockerized application.
* Open the shell of the web service and apply migrations:
   ```cmd
   python manage.py makemigrations
   python manage.py migrate
   ```
* When you are done with the container, run the following command to stop the services:
   ```cmd
   docker-compose stop
   ```

Reference I mainly used while preparing the Docker files: [How to Configure Django/PostgreSQL Environment Using Docker](https://selectfrom.dev/how-to-configure-django-postgresql-environment-using-docker-8d5bb2db447c)
## Development and Production
As you may notice, I updated the structure of the settings. Let me first provide the changes and then the reasoning behind:
* Under the `backend` directory, created a new folder named `settings`.
* Moved `.env` file to the settings folder (this change is ignored - please don't forget to do it in your local environment)
* Moved `settings.py` file to the settings folder and renamed it as `base.py`.
* Created a new file called `development.py`.
* Created a new file called `production.py`.
---
* Notice that, we use a different database while testing our application locally, and use another database while running it on Docker. But the thing is that there is only one `DATABASES` variable in `settings.py`. So how can we configure it for both of the cases? Well, we have to create different files for development and production environments.
* Our `base.py` file includes the common settings for both of the environments.
* In `development.py`, we use our local PostgreSql database.
* In `production.py` we use the PostgreSql database in Docker container.
* From `manage.py`, you can set the default settings (development) with the following part:
```python
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'backend.settings.development') 
```
By doing so, we can run our code using ```python manage.py runserver``` without any additional parameter.
* Ok, how about running the `docker-compose.yml` file? Well, we give the settings in the command run by the `web` service:
```cmd
python /project/manage.py runserver 0.0.0.0:8000 --settings=backend.settings.production
```

Reference I mainly used during the setting configuration: [Configuring Django Settings For Production](https://thinkster.io/tutorials/configuring-django-settings-for-production)

* One important thing: We have to set `DEBUG=False` for production but not yet (we want it to be visible for now).

### Reviewers

@mumcusena @BElifb 

### Extra

In the following tasks, we will try to implement CI/CD system for our project. In order to automate the "creating dockerfile and building services" procedure, we can add these commands:
* ```docker build --tag python-django .```
* ```docker-compose up -d --build```

I'm not so sure if they'll be enough, though. Just a recommendation.

**Comment by KarahanS** [comment]
Resolved the merge conflicts caused by [BE-4](https://github.com/bounswe/bounswe2022group8/issues/187). Open to review again.

**Comment by mumcusena** [comment]
Thank you for the detailed explanation. I went through it and there isn't any issue with the 'dockerization'.

**Comment by KarahanS** [comment]
PR is merged, reviewed, closing the issue.
