### ISSUE TITLE
Research: Find Similar Websites for the Project

### ISSUE THREAD

**Issue by KarahanS** [bounswe/bounswe2022group8#19]
**To Do**: Examine similar websites for the project "Art Community Platform" and share your findings [here](https://github.com/bounswe/bounswe2022group8/wiki/Research-on-Art-Community-Platforms). You may keep notes of noteworthy features and share them in the same page.

- [x] Serdar Akol
- [x] Karahan Sarıtaş
- [x] Sena Mumcu
- [ ] Mustafa Cihan
- [x] Serhat Hebun Şimşek
- [x] Elif Bayraktar
- [x] Doğukan Türksoy
- [x] Furkan Keskin
- [x] Metehan Dündar
- [x] Sinem Koçoğlu

Deadline: 13.03.2022 @17.00

**Comment by serdarakol** [comment]
I guess for this moment we have searched quite enough similar projects, for further research and report can be issued individually and report on the research tab
