### ISSUE TITLE
BE-8: [API] Implementation of Register Endpoint

### ISSUE THREAD

**Issue by KarahanS** [bounswe/bounswe2022group8#194]
### What's up?

We should start implementing our API endpoints related to [Registration/Login](https://github.com/bounswe/bounswe2022group8/wiki/Requirements#11-user-requirements) System. We'll be using [Postman](https://www.postman.com/) to test our endpoints and then provide the necessary details to the Frontend team via Google Docs.

### To Do

- [ ] Implement the API endpoint: `http://{host}/api/v1/auth/register/`
- [ ]  Document it in the Google Docs (created in #193) in detail.
- [ ] Write unit tests for the helper functions (if any)

### Deadline

25.10.2022 @17.00

### Reviewers

@BElifb @mumcusena

**Comment by mumcusena** [comment]
Closing this issue as the implementation is completed and tested.
