### ISSUE TITLE
BE-9: [API] Implementation of Login Endpoint

### ISSUE THREAD

**Issue by mumcusena** [bounswe/bounswe2022group8#195]
### What's up?

We should start implementing our API endpoints related to [Registration/Login](https://github.com/bounswe/bounswe2022group8/wiki/Requirements#11-user-requirements) System. We'll be using [Postman](https://www.postman.com/) to test our endpoints and then provide the necessary details to the Frontend team via Google Docs.

### To Do

- [x]  Implement the API endpoint: http://{host}/api/v1/auth/login/
- [x] Document it in the Google Docs (created in BE-7 API Documentation with FE team  #193) in detail.
- [x] Write unit tests for the helper functions (if any)

### Deadline

25.10.2022 @10.00

### Reviewers

@KarahanS @BElifb

**Comment by mumcusena** [comment]
* Implemented Login and Logout API endpoints in [Feature 9](https://github.com/bounswe/bounswe2022group8/pull/200)
_Please review and close this issue @KarahanS @BElifb._

**Comment by KarahanS** [comment]
PR is merged, no further action is taken.
