### ISSUE TITLE
MOB-1: Design and Code Flutter Files for Login and Sign-Up

### ISSUE THREAD

**Issue by ooodogodogodogo** [bounswe/bounswe2022group8#198]
### What's up?

Every member in Mobile Team have installed Flutter properly and ran a simple Flutter project. Now we are starting implement login and sign-up pages for mobile.

### To Do

- [x] Research about how to implement login and sign-up pages with Flutter.
- [x] Create home page.
- [x] Create sign-up page.
- [x] Create login page.

### Deadline

30.10.2022 @12.00

### Reviewers

@serdarakol @MustafaEmreErengul

**Comment by mustafa-cihan** [comment]
Designed and implemented the initial landing page, login page and signup page. Committed the final version to feature/MOB-1 branch.

**Comment by MustafaEmreErengul** [comment]
The initial landing page, login page and the signup page work well as expected. No further action required closing the issue.
