### ISSUE TITLE
BE-10: [API] Implementation of Logout Endpoint #199

### ISSUE THREAD

**Issue by dundarmete** [bounswe/bounswe2022group8#199]
### What's up?

We should start implementing our API endpoints related to [Registration/Login](https://github.com/bounswe/bounswe2022group8/wiki/Requirements#11-user-requirements) System. We'll be using [Postman](https://www.postman.com/) to test our endpoints and then provide the necessary details to the Frontend team via Google Docs.

### To Do

- [ ] Implement the API endpoint: `http://{host}/api/v1/auth/register/`
- [ ] Document it in the Google Docs (created in BE-7 API Documentation with FE team  #193) in detail.
- [ ] Write unit tests for the helper functions (if any)

### Deadline

25.10.2022 @17.00

### Reviewers

@KarahanS

**Comment by mumcusena** [comment]
* Implemented Logout API with know_views and documented it on the API documentation doc.
* PR for the implementation is reviewed and merged.
