### ISSUE TITLE
MOB-2: Meeting Notes: Week#3 Mobile Meeting#1

### ISSUE THREAD

**Issue by mustafa-cihan** [bounswe/bounswe2022group8#205]
### To Do

* Take notes during the meeting.
* Create the wiki page.
* Add links to Sidebar.

### Deadline

27.10.22 @23.00

### Additional Information

Reviewer: @serdarakol

**Comment by mustafa-cihan** [comment]
Created the mobile meeting #1 page and added It to the sidebar.

**Comment by ooodogodogodogo** [comment]
Checked, confirmed
