### ISSUE TITLE
GEN-27: Meeting Notes: Week#4 Meeting#4

### ISSUE THREAD

**Issue by mustafa-cihan** [bounswe/bounswe2022group8#207]
### To Do

* Take notes during the meeting.
* Create the wiki page.
* Add links to [Sidebar](https://github.com/bounswe/bounswe2022group8/wiki/_Sidebar/_edit) and [Homepage](https://github.com/bounswe/bounswe2022group8/wiki).

### Deadline

28.10.2022 @15.00

**Comment by mustafa-cihan** [comment]
Added general meeting 4.

**Comment by ooodogodogodogo** [comment]
Checked, confirmed
