### ISSUE TITLE
MOB-3: Connecting Mobile App with Backend

### ISSUE THREAD

**Issue by mustafa-cihan** [bounswe/bounswe2022group8#208]
### What's up?

With the completion of backend part of login, signup and logout, we have to connect backend to mobile app by providing api calls on user interface and solving some authorization issues on mobile app. 

### To Do

- [x] Configure backend tools to connect Flutter app with backend.
- [x] Test connection with sending requests and receiving responses.
- [x] Implement the client that sends requests.
- [x] Send requests corresponding to button. ex login button sends login request.

### Deadline

31.10.2022 @13.00

### Reviewers

@serdarakol @MustafaEmreErengul

**Comment by ooodogodogodogo** [comment]
Connections are done but 3 changes must be done in pages.
1- Forgot password button must be discarded
2- Login must be done with username
3- Signup page must include Confirn Password part.

@mustafa-cihan assigned to those changes. Deadline is 31.10.22 @13.00

**Comment by mustafa-cihan** [comment]
3 changes made.
1- Forgot password button is discarded
2- Login email changed to username.
3- Added confirm password

**Comment by ooodogodogodogo** [comment]
All tasks are done, pull request is waiting for merge.
