### ISSUE TITLE
BE-11: CI/CD Research and Implementation

### ISSUE THREAD

**Issue by BElifb** [bounswe/bounswe2022group8#209]
### What's up?

In the previous general meeting (and again in the backend meeting) we discussed that including some sort of CICD and automation would be beneficial for the development process. First step was to research which tool would be best suited to our needs. And also we wanted to automate the build and the testing process.

### To Do

* Research different CICD tools (namely Jenkins and Github Actions).
* Decide on a tool.
* Learn how to use the said tool, at least to the degree where it meets our needs.
* Implement/write the script for the project, including automated unit testing.
* Optionally, include automated format checking and dockerization.

### Deadline

11.11.2022 @23.59

### Reviewers

@KarahanS

**Comment by BElifb** [comment]
* Researched Jenkins and Github actions. Here are a few useful links if you're interested.
  * [Jenkins Full Course](https://www.youtube.com/watch?v=FX322RVNGj4)
  * [Github Actions Tutorial](https://www.youtube.com/watch?v=R8_veQiYBjI)
  * [Github Actions Documentation](https://docs.github.com/en/actions)
* Decided to use Github actions as it seems to fit our current needs and is also recommended by the instructor. As a bonus, we can also use it to automate other things around the repo , not just for CI/CD.

**Comment by KarahanS** [comment]
Reviewed the #215, made small additions on `README` and `docker-compose` file. It's ready to go now.
We can change the docker-compose file after our package visibility is set to public (at least for `bounswe`) by the lecturer hopefully. We can create a `hotfix` branch or something later on - so you can merge this one now.

**Comment by BElifb** [comment]
* Decided to separate testing workflow from build and dockerization.
* Created a workflow for automatically building and pushing docker images.
* Configured to store the docker images in the repo (Github Packages).
* Detailed information about implementation details and guide on how to use the mentioned services can be found on #215
