### ISSUE TITLE
BE-12: Integration Between Frontend and Backend

### ISSUE THREAD

**Issue by KarahanS** [bounswe/bounswe2022group8#211]
### What's up?

We have to enable the ```CORS``` for Django REST Framework to enable the communication between Frontend and Backend. One should simply follow the procedure provided [here](https://stackoverflow.com/questions/35760943/how-can-i-enable-cors-on-django-rest-framework).

### To Do

- [x] Configure `CORS` settings for Django Rest Framework.

### Deadline

29.10.12 @00.00

### Reviewers

@sinemKocoglu @kostanya @ooodogodogodogo

**Comment by KarahanS** [comment]
Necessary actions are taken, opened the [PR](https://github.com/bounswe/bounswe2022group8/pull/210).

**Comment by sinemKocoglu** [comment]
Thanks a lot for your help!
