### ISSUE TITLE
GEN-28: Name for application

### ISSUE THREAD

**Issue by mustafa-cihan** [bounswe/bounswe2022group8#212]
### What's up?

After nearly 9 months, we still don't have a name for our project. 

### To Do

- Suggest a name.
- Decide the project name.

### Deadline

30.10.2022 @22.00

**Comment by KarahanS** [comment]
I propose `ArtOnline` because it's like knight online. **nostalgia**

**Comment by mumcusena** [comment]
I propose `Artly`, it can be catchy 😃

**Comment by BElifb** [comment]
I propose `ARTmania`, because this the place for art !

**Comment by dundarmete** [comment]
I propose `creARTive`!

**Comment by KarahanS** [comment]
Rest of the folk, please either make a proposal or leave an emoji on one of the names to vote for them. Let's decide on a particular name and close this issue. @serdarakol @mustafa-cihan @ooodogodogodogo @simsekhebun @sinemKocoglu @kostanya @

**Comment by MustafaEmreErengul** [comment]
I am voting for `Artic`

**Comment by MustafaEmreErengul** [comment]
> I propose `ArtOnline` because it's like knight online. **nostalgia**
"Art online, hayat offline :)"

**Comment by sinemKocoglu** [comment]
> I am voting for `Artic`

It reminds me Arctic Monkeys:) I vote for it.

**Comment by BElifb** [comment]
`Artopia` could also be a contender, ideal place for art.

**Comment by BElifb** [comment]
> I propose `creARTive`!

I really like this one as well.

**Comment by serdarakol** [comment]
> Rest of the folk, please either make a proposal or leave an emoji on one of the names to vote for them. Let's decide on a particular name and close this issue. @serdarakol @mustafa-cihan @ooodogodogodogo @simsekhebun @sinemKocoglu @kostanya @MustafaEmreErengul

I vote for Artopia

**Comment by mustafa-cihan** [comment]
I also vote for `Artopia`.

**Comment by mustafa-cihan** [comment]
`Artopia` was chosen by democracy.
