### ISSUE TITLE
MOB-4: Creating a Homepage

### ISSUE THREAD

**Issue by ooodogodogodogo** [bounswe/bounswe2022group8#213]
### What's up?

We have created login and sign-up pages. We need to create a basic homepage and route login and sign-up to homepage. Also, we need to add a logout button on homepage.

### To Do

- [x] Create a Homepage
- [x] Route login and signup to homepage
- [x] Add logout button

### Deadline

29.10.2022 @12.00

### Additional Information

This functionality does not include sending requests and request handling.

### Reviewers

@ooodogodogodogo @MustafaEmreErengul

**Comment by mustafa-cihan** [comment]
Created the homepage. Filled it with some dummy posts. I also added the button so they can route the correct pages. You can edit onPress attribute of button to check response code and take the necessary actions.

**Comment by MustafaEmreErengul** [comment]
The homepage is created with the necessary features mentioned in the To Do part. The review of the functionalities are done, all of them works as expected. Closing the issue.
