### ISSUE TITLE
MOB-5: Adding error notifications on login and sign-up

### ISSUE THREAD

**Issue by ooodogodogodogo** [bounswe/bounswe2022group8#214]
### What's up?

We need to show some errors when user input is not matched with our login/signup criterias.

### To Do

- [x] Add a simple error notification on login
- [x] Add a simple error notification on signup

### Deadline

29.10.2022 @12.00

### Reviewers

@ooodogodogodogo

**Comment by mustafa-cihan** [comment]
Added simple text message to notify user. Currently error text is static. It will be changed with response body to give correct output to the user. This part can be done after sending requests and receiving responses. As for now, that is enough.

**Comment by mustafa-cihan** [comment]
As pull request is confirmed and merged, there are no reasons to keep this issue open.
