### ISSUE TITLE
Add Group Foto to README.md and Wiki Home

### ISSUE THREAD

**Issue by mumcusena** [bounswe/bounswe2022group8#22]
**To Do:** The picture which was taken during meeting 3 should be added to README.md and Wiki Home.

**Comment by mumcusena** [comment]
I added our group project to [README](https://github.com/bounswe/bounswe2022group8) and [Wiki home](https://github.com/bounswe/bounswe2022group8/wiki). @KarahanS can you please review it? If there is nothing to change you can close this issue.

**Comment by KarahanS** [comment]
Closed with issue #14.
