### ISSUE TITLE
MIL-3: Adding Individual Contributions Report

### ISSUE THREAD

**Issue by mustafa-cihan** [bounswe/bounswe2022group8#222]
### What's up?

As a part of  [Milestone I](https://github.com/bounswe/bounswe2022group8/issues/201) we need to add individual contribution report. 

### To Do

* Each member should add a subsection under the ‘Individual reports' section. These sections should be sorted alphabetically according to the surnames of team members.
* While preparing your individual report, provide the necessary hyperlinks and references to your work on GitHub.
* Add your contribution report to the [md file](https://github.com/bounswe/bounswe2022group8/blob/feature/MIL/Deliverables/CMPE451_Customer_Presentation_Milestone_1/Deliverables.md)

### Deadline

31.10.2022@23.59

### Additional Information

- [x] Sena Mumcu
- [x] Karahan Saritas
- [x] Serdar Akol
- [x] Elif Bayraktar
- [x] Mustafa Cihan
- [ ] Metehan Dundar
- [x] Furkan Keskin
- [x] Sinem Kocoglu
- [ ] Serhat Hebun Simsek
- [x] Dogukan Turksoy
- [x] Mustafa Emre Erengül

**Comment by KarahanS** [comment]
Milestone I Deliverables #201 is completed, closing the issue.
