### ISSUE TITLE
MIL-4: Last changes for Deployment before Milestone 1

### ISSUE THREAD

**Issue by ooodogodogodogo** [bounswe/bounswe2022group8#224]
### What's up?

We have deployed the app with @KarahanS. We had lots of issues and solved them with some changes. Here are the changes:

1- Added Allowed Hosts to production.py
2- Altered Dockerfile.production for frontend.
3- Changed hosts of frontend api calls.

### To Do

- [x] Push the changes to feature/MIL-4 and merge it.

### Deadline

1.01.22 @ 01.00

**Comment by KarahanS** [comment]
PR is merged and our app is deployed. No further action is required.
