### ISSUE TITLE
GEN-29: Update Use Case diagram

### ISSUE THREAD

**Issue by BElifb** [bounswe/bounswe2022group8#229]
### What's up?

We have changed a few things in the requirements. UML diagrams need to be updated in accordance with these changes.

#### Use Case
* [x] Check diagrams, to see what needs to be changed.
* [x] Make necessary changes.
* [x] Export and upload to repo. 

### Deadline

1.11.2022 @23.59

### Reviewers

@serdarakol @mumcusena

**Comment by BElifb** [comment]
Use Case diagram updated and uploaded to [wiki](https://github.com/bounswe/bounswe2022group8/wiki/Use-case-diagram)

**Comment by mumcusena** [comment]
* Reviewed the use case diagram, it reflects the current state of our application's requirements correctly.
