### ISSUE TITLE
GEN-30: Update the project plan

### ISSUE THREAD

**Issue by kostanya** [bounswe/bounswe2022group8#230]
### What's up?

_"It is not the plan that matters, but the planning."_ Michael Scott

### To Do

- [x] Update the project plan considering the process before Milestone I. 

### Deadline

01.11.2022 _@12.00_

### Reviewers

@mustafa-cihan

**Comment by kostanya** [comment]
Updated the project plan. Latest version can be found [here.](https://github.com/bounswe/bounswe2022group8/wiki/CmpE-451-Project-Plan)

**Comment by KarahanS** [comment]
That's great @kostanya but we decided to remove the `email confirmation` part from the requirements. As you see we don't send email to the users while they are trying to register to the application. Could you update that part?

**Comment by kostanya** [comment]
Must have overlooked. Updated. If there is any other section you think should be changed, please let me know.

**Comment by KarahanS** [comment]
Thanks for the update. No further action is taken, closing the issue.
