### ISSUE TITLE
GEN-31: Meeting Notes: Week #5 Meeting #5

### ISSUE THREAD

**Issue by kostanya** [bounswe/bounswe2022group8#235]
### To Do

* Take notes during the meeting.
* Create the wiki page.
* Add links to [Sidebar](https://github.com/bounswe/bounswe2022group8/wiki/_Sidebar/_edit) and [Homepage](https://github.com/bounswe/bounswe2022group8/wiki).

### Deadline

04.11.2022 _@23.55_

### Additional Information

Reviewer: @BElifb

**Comment by kostanya** [comment]
Added week 5 meeting 5 to the sidebar and homepage. Can be found [here.](https://github.com/bounswe/bounswe2022group8/wiki/Week-5-Meeting-Notes-5)

**Comment by KarahanS** [comment]
We have talked about two additional tasks:
1. Our label format should be fixed. We have labels like `Priority: High`, `Effort: Low` and labels like `documentation`, `backend` etc. I think we have to convert all labels to the former format. (like `Type: Documentation`, `Team: Backend`, `Status: Postponed`) 
2. We have to design several logos for our project and pick one of them.

I though we could assign those to @dundarmete if it's ok with him as well. What are your opinions on that?

**Comment by kostanya** [comment]
First point seems totally reasonable, we can easily do that. Logo design was mentioned but we haven't assigned it to anyone yet. There are two options: we can either assign it to one or a few people, or we can follow a voluntary system and choose the most liked logo.

**Comment by KarahanS** [comment]
Assigning to a few people seems like a luxury while there are lots of other things to do. I guess we are waiting for the response of @dundarmete at this point.

**Comment by dundarmete** [comment]
You can assign me to both of these tasks, no problem.

**Comment by kostanya** [comment]
Added mentioned tasks.
