### ISSUE TITLE
FE-9: Meeting Notes: Week #5 Frontend Meeting #2

### ISSUE THREAD

**Issue by kostanya** [bounswe/bounswe2022group8#236]
### To Do

* Take notes during the meeting.
* Create the wiki page.
* Add links to [Sidebar](https://github.com/bounswe/bounswe2022group8/wiki/_Sidebar/_edit).

### Deadline

09.11.2022 _@12.00_

### Additional Information

Reviewer: @sinemKocoglu

**Comment by kostanya** [comment]
Added week 5 frontend meeting 2 to the sidebar. Can be found [here.](https://github.com/bounswe/bounswe2022group8/wiki/Week-5-Frontend-Meeting-Notes-2)

**Comment by sinemKocoglu** [comment]
Reviewed. No action taken
