### ISSUE TITLE
MOB-5: Meeting Notes: Week#5 Mobile Meeting#2

### ISSUE THREAD

**Issue by mustafa-cihan** [bounswe/bounswe2022group8#237]
### What's up?

After the milestone presentation, we need evaluate our work. Take notes and make necessary changes to mobile app.

### To Do

* Take notes during the meeting.
* Create the wiki page.
* Add links to Sidebar.

### Deadline

03.11.2022 @06.00

### Reviewers

@MustafaEmreErengul , @ooodogodogodogo

**Comment by mustafa-cihan** [comment]
Added meeting note. Please review

**Comment by MustafaEmreErengul** [comment]
Meeting notes are reviewed and the corresponding actions are taken. Closing the issue.
