### ISSUE TITLE
BE-13: Meeting Notes: Week#5 Backend Meeting#2

### ISSUE THREAD

**Issue by BElifb** [bounswe/bounswe2022group8#240]
### To Do

* Take notes during the meeting.
* Create the [wiki page](https://github.com/bounswe/bounswe2022group8/wiki/Week-5--BE-Meeting-%232-(02.11.2022)).
* Add links to [Sidebar](https://github.com/bounswe/bounswe2022group8/wiki/_Sidebar/_edit) and [Homepage](https://github.com/bounswe/bounswe2022group8/wiki).

### Deadline

03.11.2022 @23.59

### Reviewer

@dundarmete

**Comment by BElifb** [comment]
* Created the [wiki page](https://github.com/bounswe/bounswe2022group8/wiki/Week-5--BE-Meeting-%232-(02.11.2022))
* Added to sidebar, I guess we're not adding subgroup meetings to homepage.

**Comment by KarahanS** [comment]
LGTM
