### ISSUE TITLE
FE-10: Profile Page

### ISSUE THREAD

**Issue by kostanya** [bounswe/bounswe2022group8#241]
### What's up?

As discussed in [Week #5 Frontend Meeting #2](https://github.com/bounswe/bounswe2022group8/wiki/Week-5-Frontend-Meeting-Notes-2) we need to design and implement a profile page.

### To Do

- [x] Carefully study the profile pages of art-related websites and take note of various design ideas.
- [x] Decide the main functionalities that should be on the page.
- [x] Create a basic and simple profile page design and layout.
- [x] Implement the basic design.
- [x] Improve the design and implement the improvements.

### Deadline

10.11.2022 _@23.59_

**Comment by sinemKocoglu** [comment]
I have added api call for profile info except profile image. I didn't test it because api endpoints are in different branch. I think it is more efficient to test it with backend team in ps session. Also, if we can provide api call to edit profile on settings page until ps, we can test it too.

**Comment by sinemKocoglu** [comment]
I have created the first design of art item page that when you click on images on profile page, it navigates to the art item page having art item and comments of it. It is created with static data for now. Design may also be improved by time.

**Comment by kostanya** [comment]
Improved @sinemKocoglu 's profile page skeleton as much as I could. The main changes I made are the following: changed the gallery grid system, made minor changes to the color palette, redesigned the bio and redesigned the whole page to be compatible with different screen sizes.

**Comment by kostanya** [comment]
The most important thing now is how the user interacts with the images in the profile. These interactions can be categorized under two main categories: hovering the images and clicking the images. 

- [ ]  When an image is hovered, comment and like numbers should appear.
- [ ] Clicking on an image should direct to a new page where one can comment, see the comments and like the image.

**Comment by kostanya** [comment]
Image redirection has been implemented, but the hover effect has not yet been implemented. After that we should close the issue.

**Comment by kostanya** [comment]
Hover effect is implemented, however only options button appears when an image is hovered not comment or like numbers. Also, slight opacity added for a better user experience. Cursors upon hovering are updated as well.

**Comment by sinemKocoglu** [comment]
Reviewed related pr's #375 , #374 .
