### ISSUE TITLE
MIL-7: Evaluation of Tools and Processes in Milestone 1 Group Review

### ISSUE THREAD

**Issue by mumcusena** [bounswe/bounswe2022group8#242]
### What's up?

Milestone 1 is a reflection on the work we have done thus far. Therefore we will add an 'Evaluation of Tools and Processes' to the Milestone 1 report to reflect on different software tools and development processes we have used.

- One member from each subteam should contribute to the evaluation. This way we can have an overarching evaluation for Milestone 1.  

### To Do

- [x] Evaluate your team's tools and development processes in Milestone [md](https://github.com/bounswe/bounswe2022group8/blob/master/Deliverables/CMPE451_Customer_Presentation_Milestone_1/Deliverables.md)

### Deadline

4.11.2022 @22.00

### Reviewers

@serdarakol @BElifb @kostanya

**Comment by ooodogodogodogo** [comment]
Evaluations for VSCode, Flutter and Android Studio are added for mobile part.

**Comment by KarahanS** [comment]
Let's reference the general issue #226.

**Comment by sinemKocoglu** [comment]
Evaluation for frontend tools which are VS code, Javascript, React.js, Node.js, Bootstrapt and Docker are added.

**Comment by mumcusena** [comment]
Evaluation for backend tools (VSCode, Django & Rest framework, Postman, PostgreSQL) added.

_Please review and add anything you see missing. @BElifb @mustafa-cihan @kostanya_

**Comment by mustafa-cihan** [comment]
@mumcusena I reviewed mobile tools. It is nice and clear.
@BElifb and @kostanya please review your teams tools. After that we can close the issue.

**Comment by kostanya** [comment]
I've just checked and I can say that frontend section looks fantastic.

**Comment by BElifb** [comment]
We could possibly mention that we had a hard time with authentication  (tokens to be specific). But this might not be the right place mention it. Other than that backend section looks superb!

**Comment by KarahanS** [comment]
Milestone I is completed, no further action is taken. Closing the issue.
