### ISSUE TITLE
BE-19: Implementation of Reset Password API (Forgot password & logged in)

### ISSUE THREAD

**Issue by BElifb** [bounswe/bounswe2022group8#254]
### What's up?

In the last [Backend Meeting](https://github.com/bounswe/bounswe2022group8/wiki/Week-5--BE-Meeting-%232-(02.11.2022)) we decided to implement an API for resetting a user's password when they have forgotten it and can not login. This API will send a link to user's saved e-mail. We will also implement a separate API for password update for logged in case.

### To Do

* [x] Research & learn how to send auto generated e-mails.
* [x] Implement the Reset Password APIs.
* [x] Document it with Swagger.
* [x] Create an API for password update through profile page (logged in case).

### Deadline

13.11.2022 @23.59

### Reviewers

@KarahanS @serdarakol

**Comment by KarahanS** [comment]
I opened PR #252 during the PS to update some of the error messages and so on. I didn't create an issue since it was a small thing and everyone was present already. Updated the name of this PR to `BE-19`.
Note: If you are working on a local branch called `feature/BE-18`, you can change its name with `git branch -m feature/BE-19`.

**Comment by BElifb** [comment]
* Researched sending email with django.
* Created 2 API's for password reset (without login/ forgot password case).
  * `http://127.0.0.1:8000/api/v1/auth/resetRequest/` 
    * Takes  {
   "email": "user_email@artopia.com"
 }, and sends an email with a one time password to user.
  * `http://127.0.0.1:8000/api/v1/auth/resetPassword/`
    * Takes  {
   "email": "user_email@artopia.com",
   "otp": "six_digit_otp_from_email",
   "new_password": "new_user_password"
 }, and changes user password to new_password.
  * Prepared detail documentation with examples,on Swagger
    * `http://localhost:8000/api/v1/swagger/schema/`
* I left detailed instructions on how to test it [here](https://github.com/bounswe/bounswe2022group8/pull/259#issue-1445392530)
*  I searched for different email providers with free SMTP, but couldn't find any. Let me know if you do.

**Comment by BElifb** [comment]
* Opened pull request #259

**Comment by BElifb** [comment]
* Btw Swagger didn't let me document (or I couldn't find how) different status = 400 error cases with seperate explanations. If interested you may check the API code itself.

**Comment by KarahanS** [comment]
Left a comment on the #259 about API name conventions.

**Comment by BElifb** [comment]
* Created another API for password update (through profile page/logged in).
  * `http://127.0.0.1:8000/api/v1/profile/me/password-reset/` 
    * Takes  {
   "new_password": "new_user_password"
 }, and updates user password.
  * User must be logged in (Token is checked).
  * Documentation can be found on Swagger page.
 #259

**Comment by KarahanS** [comment]
Merged - not further action is required.
