### ISSUE TITLE
Requirements: Specification of Non-Functional Requirements 

### ISSUE THREAD

**Issue by KarahanS** [bounswe/bounswe2022group8#26]
**To Do**: Specify the non-functional requirements. It's the first phase of the requirements engineering process and requirements may be updated or modified as we progress. Determine the necessary questions for the non-functional requirements. After determining them individually, hold a discussion about the requirements and make necessary adjustments as a group.

Non-functional requirements may be split into two subgroups. Each subgroup may include (but not limited to) the subtitles given below:
* System prop
   * Up time
   * Response time
   * Storage
   * Usability
   * Privacy
   * Security
   * Portability
   * Annotation
* Process requirements
   * IDE
   * Programming Language
   * Development medium
 
Process requirements will be determined at the development stage.
Deadline: 13.03.2022 @18.00

**Comment by mustafa-cihan** [comment]
Availability, accessibility, annotation, privacy, security, performance and portability are decided as non-functional requirement topics.
