### ISSUE TITLE
BE-20: Comment System

### ISSUE THREAD

**Issue by BElifb** [bounswe/bounswe2022group8#261]
### What's up?

In the last week's backend meeting we decided to go forward with comment system implementation.

### To Do

* [x] Research different python packages that can be used for comment system.
* [x] Implement the model(s) for comment.
* [x] Implement CRUD APIs for comments.
* [x] Document those with Swagger.

### Deadline

13.11.2022 @23.59

### Reviewers

@KarahanS @mumcusena

**Comment by BElifb** [comment]
* Researched and decided to use **django-mptt** for comments. This helps us with managing hierarchical data. Here's the [documentation](https://django-mptt.readthedocs.io/en/latest/overview.html). There are useful tags for managing data with django template tags (indentation etc.), but if it is not compatible with react we can always manually use the fields.
* Updated Comment model accordingly.
* Created 2 API endpoints with 5 APIs in total.
* Documented in detail with Swagger. Here's a preview.
![image](https://user-images.githubusercontent.com/100690512/201535382-cc475324-b3a1-4db3-b529-76224a01e0bc.png)

**Comment by BElifb** [comment]
* Created PR #262

**Comment by KarahanS** [comment]
Reviewed, made minor corrections and merged. Closing the issue.
