### ISSUE TITLE
Project Plan

### ISSUE THREAD

**Issue by busraoguzoglu** [bounswe/bounswe2022group8#263]
### What's up?

Please provide the original version of your project plan (not the pdf file) on the deliverables file.

### To Do

Provide the original version of project plan (from GanttProject). Contact via email for any questions.

### Deadline

11.15.2022 @23.59

**Comment by kostanya** [comment]
Tried to replace the pdf file with the .gan file, but it seems that .gan files are not supported in github.

**Comment by busraoguzoglu** [comment]
It is okay, pdf can stay then :) Just send me the original file via email. Thanks
