### ISSUE TITLE
BE-31: Meeting Notes: Week 7 Backend-Meeting #3

### ISSUE THREAD

**Issue by mumcusena** [bounswe/bounswe2022group8#264]
### To Do

* Take notes during the meeting.
* Create the [wiki page](https://github.com/bounswe/bounswe2022group8/wiki/_new)
* Add links to [Sidebar](https://github.com/bounswe/bounswe2022group8/wiki/_Sidebar/_edit) and [Homepage](https://github.com/bounswe/bounswe2022group8/wiki)

### Deadline

16.11.2022 @10.00

**Comment by mumcusena** [comment]
* added meeting notes to [wiki](https://github.com/bounswe/bounswe2022group8/wiki/Week-7-BE-Meeting-%233-(15.11.2022)) and to sidebar on wiki.
* Since this was a subgroup meeting I didn't added the notes to homepage. 

_Please review and close the issue if it is GTG_ 
_Reviewers: @BElifb, @KarahanS, @serdarakol_

**Comment by KarahanS** [comment]
Added art item related APIs. Also, I think we should write "implementation of related APIs" to @BElifb's task since it requires implementation as well.

**Comment by mumcusena** [comment]
I added "developing required APIs" to Elif's task. @KarahanS

**Comment by KarahanS** [comment]
Looks ok, thanks.
