### ISSUE TITLE
FE-13: Meeting Notes: Week #7 Meeting #3

### ISSUE THREAD

**Issue by kostanya** [bounswe/bounswe2022group8#265]
### To Do

* Take notes during the meeting.
* Create the wiki page.
* Add links to [Sidebar](https://github.com/bounswe/bounswe2022group8/wiki/_Sidebar/_edit).

### Deadline

16.11.2022 _@23.59_

### Additional Information

Reviewer: @sinemKocoglu

**Comment by kostanya** [comment]
Added week 5 frontend meeting 2 to the sidebar. Can be found [here.](https://github.com/bounswe/bounswe2022group8/wiki/Week-7-Frontend-Meeting-Notes-3)

**Comment by sinemKocoglu** [comment]
Reviewed. Thanks!
