### ISSUE TITLE
FE-14: Image Uploading

### ISSUE THREAD

**Issue by kostanya** [bounswe/bounswe2022group8#266]
### What's up?

As we implement an art related project, images are of great importance for us. So we need to create a user-friendly interface for image uploading and then connect to the backend. 

### To Do

- [x] Design and implement an interface for image uploading.
- [x] Figure out the Base 64 encoding/decoding in JS.
- [x] Figure out AWS S3 Bucket-to-Frontend communication. A useful [link](https://aws.plainenglish.io/using-node-js-to-display-images-in-a-private-aws-s3-bucket-4c043ed5c5d0).
- [x] Test the whole process by trying to change a profile picture.

### Deadline

22.11.2022 _@23.59_

**Comment by kostanya** [comment]
As of now, a registered user can successfully change their profile photo. But an interface for art item upload has not been designed yet. Also, optimizations for rendering speed may have to come in the future.

**Comment by sinemKocoglu** [comment]
Completed and shown in presentation. Thank you. Good design choice!
