### ISSUE TITLE
BE-22: [API] Implementation of Follow Action APIs

### ISSUE THREAD

**Issue by KarahanS** [bounswe/bounswe2022group8#272]
### What's up?

In our [Week 7 BE Meeting](https://github.com/bounswe/bounswe2022group8/wiki/Week-7-BE-Meeting-%233-(15.11.2022)), we decided to start working on the basic user actions including follow functionality. I'll be expanding the list of APIs provided below during the development.

### To Do

API endpoints to be implemented:
- [x] http://${host}:8000/api/v1/users/follow/\<id\>                                 `POST`    / Follow a user with the given id
- [x] http://${host}:8000/api/v1/users/unfollow/\<id\>                            `DELETE` / Unfollow a user with the given id
- [x] http://${host}:8000/api/v1/users/me/followers/                                 `GET` / Get list of followers (of the currently logged-in user)
- [x] http://${host}:8000/api/v1/users/me/followings/                                 `GET` / Get list of followed users (by the currently logged-in user)
- [x] http://${host}:8000/api/v1/users/\<id\>/followers/                          `GET` / Get the followers of the user with the given id
- [x] http://${host}:8000/api/v1/users/\<id\>/followings/                       `GET` / Get list of followed users by the user with the given id
- [x] http://${host}:8000/api/v1/artitems/me/followings/                       `GET` / Get list of art items belonging to the users followed by the currently logged-in user (that's a very helpful API to populate the main feed)

### Deadline

27.11.2022 @14:00

### Reviewers

@BElifb @serdarakol @mumcusena

**Comment by serdarakol** [comment]
I have reviewed and merged the PR #274. Everything looks fine and works as we have discussed.
