### ISSUE TITLE
GEN-33: Label Ordering

### ISSUE THREAD

**Issue by dundarmete** [bounswe/bounswe2022group8#273]
### What's up?

As the project grows we need other labels, to classify the issues.

### To Do

- [x] Editing the existing labels
- [x] If needed adding new ones.

### Deadline

19.11.2022 @23.59

### Reviewers

@KarahanS

**Comment by KarahanS** [comment]
While I was creating a PR, I encountered with these labels:
![sada](https://user-images.githubusercontent.com/44376034/202729479-4f792e05-f61d-4417-af0a-d5a9c630e522.png)

What are the meanings of High, Medium and Low in front of the Backend? Do they indicate priorities? We already have `Priority` labels for them. I've seen similar labels for other teams as well. Wouldn't it be better just to create labels like:
`Team: Backend`
`Team: Frontend`
`Team: Mobile`
Do these high, medium and low stuff have some other meanings that I don't understand?

**Comment by KarahanS** [comment]
Better now, thanks

**Comment by MustafaEmreErengul** [comment]
Since all to do items are completed, no further action is required. Closing the issue.
