### ISSUE TITLE
GEN-34: Annotation Research

### ISSUE THREAD

**Issue by dundarmete** [bounswe/bounswe2022group8#275]
### What's up?

Our project needs to research Annotation before implementing it.

### To Do

- [ ] Researching Annotations
- [ ] How we'll use them for semantic search
- [ ] Taking the first implementation steps in this direction

### Deadline

~~21.11.2022 @23.59~~
13.11.2022 @14.00

**Comment by KarahanS** [comment]
Deadline for the related action was 13.11.2022 @14:00 as stated in [Week 5 BE Meeting Notes](https://github.com/bounswe/bounswe2022group8/wiki/Week-5--BE-Meeting-%232-(02.11.2022)).

**Comment by KarahanS** [comment]
This task is cancelled as I started the implementation using [https://www.w3.org/TR/annotation-model/](WADM) documentation in #348. Unfortunately, this was a useless task :/
