### ISSUE TITLE
BE-27: [API] Account Deletion

### ISSUE THREAD

**Issue by KarahanS** [bounswe/bounswe2022group8#276]
### What's up?

A group of APIs or an API is to be implemented to enable users delete their accounts from the application.
Assignee: @serdarakol 
This task was given in the [Week 5 BE Meeting #2](https://github.com/bounswe/bounswe2022group8/wiki/Week-5--BE-Meeting-%232-(02.11.2022)) (02.11.2022). I noticed that the issue has not been opened afterwards - so I open the issue now.

### To Do

- [x] Profile deletion API(s) to be implemented.
- [x] Necessary documentation must be prepared using Swagger.
- [x] Functionality should be tested on development and production sites.

### Deadline

13.11.2022 @14.00

**Comment by KarahanS** [comment]
It's been 20 days since the task was given. Reminder to @serdarakol for necessary actions.

**Comment by serdarakol** [comment]
So sorry for missing the deadline. It will be ready latest by the Sunday meeting. Thank you for your understanding and patience.

**Comment by KarahanS** [comment]
BE-24 is taken by #293. Let's relabel it as BE-27.
