### ISSUE TITLE
BE-23: [API] Tag Managing

### ISSUE THREAD

**Issue by mumcusena** [bounswe/bounswe2022group8#277]
### What's up?

A group of API's to be implemented to allow moderator manage tags by creating new tags, deleting existing ones etc. 

### To Do

API endpoints to be implemented:
- [x] http://${host}:8000/api/v1/artitems/tags/<id>`GET`/ Get a tag with the given id
- [x] http://${host}:8000/api/v1/artitems/tags/<id>`DELETE`/ Delete a tag with the given id
- [x] http://${host}:8000/api/v1/artitems/tags/`POST`/ Create a new tag
- [x] http://${host}:8000/api/v1/artitems/tags/`GET`/ Get all tags in the db 
- [x] Necessary documentation must be prepared using Swagger.
- [x] Functionality should be tested on development and production sites.

### Deadline

22.11.2022 @16.00
_Deadline was postponed because of the busy schedule._

**Comment by KarahanS** [comment]
PR is merged, closing the issue. Thanks for the efforts.
