### ISSUE TITLE
MOB-7: Creating a profile page

### ISSUE THREAD

**Issue by MustafaEmreErengul** [bounswe/bounswe2022group8#281]
### What's up?

Each user who is registered to Artopia mobile app should have a personal profile page. In this profile page one should be able to see user's Art Items and Exhibitions. Also the user should be able to reach. Also this page should navigate to a new "settings page" that allow changes on profile like changing user's password and changing the profile photo.

### To Do

- [x] Implementing the upper profile header widget.
- [x] Implementing back and forward navigation pages.
- [x] Slidable gallery view for the art items
- [x] Adding Art Items tab.
- [x] Adding Exibitions tab.

### Deadline

29.11.2022 @14.00

### Additional Information

The implemented features might be static at the deadline. However they have to be active before 06.12.2022 @14.00

### Reviewers

@mustafa-cihan @ooodogodogodogo

**Comment by MustafaEmreErengul** [comment]
#280

**Comment by ooodogodogodogo** [comment]
All features are implemented as expected, closed.
