### ISSUE TITLE
MOB-8: Creating Art Item Pages

### ISSUE THREAD

**Issue by MustafaEmreErengul** [bounswe/bounswe2022group8#282]
### What's up?

Each item uploaded to Artopia mobile app should have an "art item page" that shows the uploaded size of the item (not a thumb nail like in the gallery view), all comments that are made to the art item and how the number of the like reactions that are given to this item.

### To Do

- [x] Implementing the full (original )size of the item.
- [x] Slidable side bar for the comments that are made to the art item.
- [x] An icon button for the number of the like reactions.

### Deadline

29.11.2022 @14.00

### Additional Information

The implemented features might be static at the deadline. However they have to be active before 06.12.2022 @14.00

### Reviewers

@MustafaEmreErengul

**Comment by mustafa-cihan** [comment]
Created static art item page and classes that related to art item.

**Comment by MustafaEmreErengul** [comment]
Since To Do list implementations are done. Closing the issue. Good work!
