### ISSUE TITLE
MOB-11: Uploading a new art item to the profile

### ISSUE THREAD

**Issue by MustafaEmreErengul** [bounswe/bounswe2022group8#285]
### What's up?

Each user that have profile should add a new art item to their profile by using an upload button which is located on the main navigation bar.

### To Do

- [x] Activating the upload art item button in the main navigation bar.
- [x] Creating a screen for uploading.
- [x] Title, description and tags should be addable.

### Deadline

29.11.2022 @14.00

### Additional Information

The implemented features might be static at the deadline. However they have to be active before 06.12.2022 @14.00

### Reviewers

@ooodogodogodogo

**Comment by ooodogodogodogo** [comment]
Reviewed and branch is merged.
