### ISSUE TITLE
GEN-35: Application Name and Logo

### ISSUE THREAD

**Issue by mumcusena** [bounswe/bounswe2022group8#290]
### What's up?

We have recently decided on our application logo and name. While updating the applications' frontends, we should also update our wiki home page and show our logo and app name under the 'Project Description' header. 

### To Do

- [x] Add the application logo to [wiki](https://github.com/bounswe/bounswe2022group8/wiki)
- [x] Add the application name to [wiki](https://github.com/bounswe/bounswe2022group8/wiki)
 

### Deadline

02.12.2022 @23.59

### Reviewers

@mumcusena

**Comment by KarahanS** [comment]
https://github.com/bounswe/bounswe2022group8/wiki/Conventions

**Comment by MustafaEmreErengul** [comment]
Our application name and logo are uploaded to our Wiki page now. I kindly request a review about it.

**Comment by dundarmete** [comment]
It looks fine issue can be closed.
