### ISSUE TITLE
MIL-10: Milestone 2 Requirements 

### ISSUE THREAD

**Issue by mumcusena** [bounswe/bounswe2022group8#299]
### What's up?

As a part of our [Milestone Group Review](#295), we should address the requirements we realized up until Milestone 2. 

### To Do

- [x] Review the project requirements
- [x] List all of the requirements we have realized until MIL-2

### Deadline

06.12.2022 @16.00

### Reviewers

@sinemKocoglu @kostanya @BElifb

**Comment by KarahanS** [comment]
Thanks! Added the list of requirements we satisfied in the tag description for #335. I included some additional requirements from the sections Portability, Accessibility and so on. Maybe you could add them as well.

**Comment by KarahanS** [comment]
No further action is taken.
