### ISSUE TITLE
Requirements: Questions on Requirements

### ISSUE THREAD

**Issue by KarahanS** [bounswe/bounswe2022group8#30]
**To Do**:  Fill the [Questions & Answers](https://github.com/bounswe/bounswe2022group8/wiki/Questions-&-Answers) section with our initial questions about the nature of the project and requirements phase. Some of the questions are planned to be resolved as we progress in the project. Others are planned to be resolved in the customer meetings.

**Comment by KarahanS** [comment]
Questions are added. Waiting for review and additional questions.

**Comment by KarahanS** [comment]
Changed the name of the section to **Questions & Answers**. Page can be found [here](https://github.com/bounswe/bounswe2022group8/wiki/Questions-&-Answers). Related to the issue #46, rephrased some of the questions and added new questions&answers based on our customer meeting. 
Waiting for additional questions.

**Comment by KarahanS** [comment]
Added q9, q10 and q11. Modified the answer of q2, q7 and q8 in order to clarify some details.

**Comment by kostanya** [comment]
We have received answers to our questions that are necessary to design diagrams. Thanks for covering the questions.
