### ISSUE TITLE
BE-28: [API] Art Item Like/Unlike

### ISSUE THREAD

**Issue by KarahanS** [bounswe/bounswe2022group8#302]
### What's up?

Users should be able to like or unlike an art item. Related art items must be implemented, tested properly and documented using Swagger.
Assignee: @serdarakol 

When was the task given: 15.11.2022 [Week 7 BE Meeting #3](https://github.com/bounswe/bounswe2022group8/wiki/Week-7-BE-Meeting-%233-(15.11.2022))
When was the deadline: 20.11.2022 (refer to the meeting notes)

### To Do

- [x] Like/Unlike art item API(s) to be implemented.
- [x] Necessary documentation must be prepared using Swagger.
- [x] Functionality should be tested on development and dockerized version.

### Deadline

We want to show this functionality in the milestone, therefore the new deadline is this Friday (02.12.2022). This deadline is sharp (as all deadlines actually) - deployed product must be be ready for the practice by the weekend.

### Additional Information

I use the work `unlike` intentionally - we don't have `dislike` feature. You can just like it or take back your like from it.
Let me provide some sort of a recipe as well:
1- User model should have a field (which can be called `likedArtItems`) that creates a many-to-many relationship between users and their liked art items (an art item can be liked by many users and a user can like many art items).
2- Add an integer field (number of likes) to the art item model. We'll increment it whenever someone likes it and decrement it if someone unlikes it.
3- Write the like and unlike APIs. They should take the id of the art item and make the necessary changes with currently logged-in user. No need to say that a user shouldn't be able to like an art item he already has liked, or unlike an art item he didn't like before. Also, he shouldn't be able to like his own art items. (You get the point, maybe there are some other edge cases as well)
4- Update the GET APIs related to art items, so that they return a boolean field which is `True` if the art item is liked by the user, otherwise `False`. That's important because frontend must be able to understand if an art item is liked by the user before. This way they will grey out the like button or maybe it will be invisible or something I don't know.
5- Document your APIs. There are already lots of examples in our repo.
6- Test the changes using docker as well. You'll need to update the database since you changed some of the models.

Furthermore, you can write APIs that return liked art items of the currently logged-in user (so that someone can refer to them easily - it's like a 'favourites' section), or return `n` most liked art items in the system (n can be given as a parameter). So, APIs can be extended to introduce new features - but essentials are the ones mentioned above.

**Attention**: This is just a recipe to guide you that I made up out of my mind 5 minutes ago - so don't take it granted. You can implement it in any way you want as long as it works properly.

### Reviewers

@mumcusena

**Comment by KarahanS** [comment]
Kindly reminder to @mumcusena to supervise (as agreed in the meeting) the procedure.

**Comment by serdarakol** [comment]
Sorry for missing the deadline, I am working on it. Thank you for your understanding and patience. It will be ready before sunday meeting

**Comment by KarahanS** [comment]
BE-25 was taken by #278. Let's relabel this one as BE-28.

**Comment by KarahanS** [comment]
PR is merged, task is completed. Thanks for the efforts.
