### ISSUE TITLE
FE-18: Follow Functionality

### ISSUE THREAD

**Issue by sinemKocoglu** [bounswe/bounswe2022group8#306]
### What's up?

As we discussed in last lab session, I will create necessary components related to follow and unfollow user and provide backend connection.

### To Do

- [x] Create profile page for other users
- [x] Create follow and unfollow buttons in user profiles.
- [x] Provide number of followers and followings from backend.
- [x] Provide backend connection for follow action.

### Deadline

17.12.2022 @23.59
Postponed due to health issues. It will be implemented until final milestone.

### Reviewers

@kostanya

**Comment by kostanya** [comment]
Done all the items listed above. See #360.

**Comment by sinemKocoglu** [comment]
Reviewed and merged pr directly by leaving comment. Completed. Thanks!
