### ISSUE TITLE
FE-19: Annotation

### ISSUE THREAD

**Issue by sinemKocoglu** [bounswe/bounswe2022group8#308]
### What's up?

As we discussed in the last lab session, we will implement showing text annotion on art items after completion of the art item page.

### To Do

- [x]  Provide text annotation on app by using @recogito/recogito-js .
- [x]  Provide image annotation on art item page @recogito/annotorious .
- [x]  After the progress in backend, meet with backend team and provide backend connection for both.

### Deadline

05.12.2022 @15.00
Postponed due to health issues and busy schedule. It will be provided until final milestone. Deadline will be assigned later.

**Comment by sinemKocoglu** [comment]
I have provided the libraries accordinly. Provided the text annotation on App.js because of usage of it but there are some issues related to it to be talked in the next meeting. Image annotation was provided in only art item page for only registered users for now. It may be implemented for exhibitions too later. Next actions will be taken according to the next meeting with backend team.

**Comment by KarahanS** [comment]
Related to #359 and #348

**Comment by sinemKocoglu** [comment]
Completed.
