### ISSUE TITLE
Adding system requirements 

### ISSUE THREAD

**Issue by sinemKocoglu** [bounswe/bounswe2022group8#33]
**To-Do** : Adding system requirements discussed and determined at the meeting to the [Requirements wiki page](https://github.com/bounswe/bounswe2022group8/wiki/Requirements) 

_Deadline : 14.03.2022 23.59_

**Comment by sinemKocoglu** [comment]
System requirements are added.
Please review and edit if there are any missing parts: @ooodogodogodogo and @simsekhebun

**Comment by ooodogodogodogo** [comment]
Reviewed, no action taken.

**Comment by simsekhebun** [comment]
Reviewed nothing seems to be missing, thanks!

**Comment by sinemKocoglu** [comment]
Requirements 1.2.4 Payment System is renamed as Bidding System because platform doesn't provide any functionality for payment system as decided in customer meeting.
1.2.4.1. Level of artist who can sell art item is stated.
1.2.4.2 is replaced. No payment system.
* 1.2.4.2  In offers page, offers of artists who are in level of 1,called registered users, are ordered in descending order.
is added.
1.2.5.1. is clarified by the definition of popularity.
1.2.8.3.1. Abilities of users are added level by level to the Level System.
