### ISSUE TITLE
FE-23: Unit Tests for Rendering

### ISSUE THREAD

**Issue by kostanya** [bounswe/bounswe2022group8#338]
### What's up?

Hello! As the frontend team we should write unit tests to make sure that our components are rendered correctly. 

### To Do

- [x] Write the necessary unit tests to make sure that our components are working correctly

### Deadline

08.12.2022 _@23.59_

### Reviewers

@kostanya and @sinemKocoglu

**Comment by sinemKocoglu** [comment]
Wrote 3 additional unit tests for 3 different components. Can be seen in the same branch and pr.

**Comment by sinemKocoglu** [comment]
Reviewed and merged related pr #339
