### ISSUE TITLE
Adding non-functional requirements: Security and Annotation

### ISSUE THREAD

**Issue by kostanya** [bounswe/bounswe2022group8#34]
**To-do:** 
- Adding security and annotation non-functional requirements to the [Requirements wiki page](https://github.com/bounswe/bounswe2022group8/wiki/Requirements).
- Make additions to the glossary if you see anything missing

**Deadline:** 14.03.2022

**Comment by kostanya** [comment]
The security and annotation requirements are added to [Requirements](https://github.com/bounswe/bounswe2022group8/wiki/Requirements). Please review and make adjustments in case needed @mumcusena  @mustafa-cihan  @BElifb.

**Comment by BElifb** [comment]
Good for first draft.
