### ISSUE TITLE
MIL-16: Standards

### ISSUE THREAD

**Issue by kostanya** [bounswe/bounswe2022group8#342]
### What's up?

As part of the Milestone 2 deliverables, we need to document what we have done throughout the project to comply with W3C standards.

### To Do

- [x] Explain the work we have completed towards the application of the W3C standards

### Deadline

08.12.2022 _@23.59_

**Comment by kostanya** [comment]
Filled in the Standards section of the Milestone 2 deliverables. Review is really needed for this one.

**Comment by KarahanS** [comment]
I think it looks fine, thank you for the efforts!
