### ISSUE TITLE
MOB-17: Backend Connections of uploading image and updating profile

### ISSUE THREAD

**Issue by ooodogodogodogo** [bounswe/bounswe2022group8#345]
### What's up?

We had the upload image and update profile pages. Now we should connect those pages with backend.

### To Do

- [x] Connect the upload image page. 
- [x] Connect the upload image page. 

### Deadline

02.12.2022 @11.59

### Reviewers

@mustafa-cihan @MustafaEmreErengul

**Comment by MustafaEmreErengul** [comment]
The mentioned to-do features are reviewed and approved. Good Work! No further actions required, closing the issue.
