### ISSUE TITLE
MOB-18: Fetching images from AWS S3

### ISSUE THREAD

**Issue by ooodogodogodogo** [bounswe/bounswe2022group8#346]
### What's up?

Backend team has uploaded images to S3. Now we should fetch those images from the S3 bucket.

### To Do

- [x]  Getting  credentials to connect AWS S3 from backend team.
- [x]  Fetching images from S3.

### Deadline

02.12.2022 @11.59

### Additional Information

AWS S3 url : https://cmpe451-production.s3.amazonaws.com
AWS Access Key and Secret key are shared with mobile team internally. Thanks to @KarahanS for sharing AWS credentials.

### Reviewers

@MustafaEmreErengul @mustafa-cihan @dundarmete

**Comment by MustafaEmreErengul** [comment]
The mentioned to-do features are reviewed and approved. Well Done! 
No further actions required, closing the issue.
