### ISSUE TITLE
MIL-17: Deployment

### ISSUE THREAD

**Issue by ooodogodogodogo** [bounswe/bounswe2022group8#347]
### What's up?

We completed the development before Milestone 2. Now we should deploy our frontend, backend and mobile apps.

### To Do

- [x] Deploy frontend.

- [x] Deploy backend.

- [x] Deploy mobile.

### Deadline

05.12.2022 @23.59

### Additional Information

You can check deployment instructions for [backend](https://github.com/bounswe/bounswe2022group8/tree/master/App/backend) and [frontend](https://github.com/bounswe/bounswe2022group8/tree/master/App/frontend) also deployed app for 
[mobile](https://github.com/bounswe/bounswe2022group8/tree/master/App/mobile)  .

### Reviewers

@KarahanS @kostanya

**Comment by KarahanS** [comment]
Product is deployed for pre-release v2. Closing the issue.
