### ISSUE TITLE
MIL-18: User Interface / User Experience

### ISSUE THREAD

**Issue by ooodogodogodogo** [bounswe/bounswe2022group8#349]
### What's up?

We should add the followings on the Milestone2: 

▪ For each user interface design, provide links to the code in the project repository
▪ Screenshots of all implemented Web and Mobile interfaces

### To Do

- [x] Adding UI/UX screenshots and code links of Mobile

- [x] Adding UI/UX screenshots and code links of Frontend

### Deadline

09.12.2022 @ 16.30

### Additional Information

You can find Mobile part of this issue [here](https://github.com/bounswe/bounswe2022group8/wiki/Mobile-User-Interfaces).

**Comment by sinemKocoglu** [comment]
Web part is available [here](https://github.com/bounswe/bounswe2022group8/wiki/Web-User-Interfaces) and added to the report.
