### ISSUE TITLE
Improving the Glossary

### ISSUE THREAD

**Issue by BElifb** [bounswe/bounswe2022group8#35]
I have added Art Item, Exhibition, Forum, Verified, Level, Interaction and popularity.
**To-do:**
* Revise the existing items in the [glossary](https://github.com/bounswe/bounswe2022group8/wiki/Requirements), make improvements if needed.
* Make additions  if you see anything missing.

**Deadline:**
 <del>29.03.2022 @23.59</del>
14.04.2022 @23.59 (extended)

**Comment by mustafa-cihan** [comment]
Added UI definition to glossary.

**Comment by simsekhebun** [comment]
Added comment and profile definitons to glossary

**Comment by KarahanS** [comment]
Modified and added new words to the glossary.
Switched from **User** and **Guest** to **User**, **Unregistered/Guest User**, and **Registered User**.
Added **Copyright**, **Semantic Search**, **Type**, **Description**, **Profile Page**, **Attendee**, **Exhibition organizer**, **Collaborator** and **Bid**.

**Comment by BElifb** [comment]
Updated **Bid** in the glossary and added **Seller**, **Bidder** and **For sale**.

**Comment by KarahanS** [comment]
Updated **Guest User**, **Registered User**, **Active User**, **Moderator**, **Reply** and **Discussion**. Removed **UserID**.

**Comment by KarahanS** [comment]
Added **Bookmark**, refer to #76 for detailed discussion.

**Comment by kostanya** [comment]
Added **Username, Password, Annotation, Notification, Transaction, Ticket, Message, Chat, Follower**.

**Comment by BElifb** [comment]
Added **participant** and slightly modified **exhibition organizer**.

**Comment by serdarakol** [comment]
added geotagging

**Comment by KarahanS** [comment]
In accord with our discussion, we decided that our glossary has taken its final form for first version of requirements. Closed the issue.
