### ISSUE TITLE
BE-32: User History

### ISSUE THREAD

**Issue by BElifb** [bounswe/bounswe2022group8#353]
### What's up?

As we know our application has recommendation and Level systems. In [Week 9 BE Meeting](https://github.com/bounswe/bounswe2022group8/wiki/Week-9--BE-Meeting-%234-(29.11.2022)) we decided to set up the necessary infrastructure for keeping track of user history. This way we can use this data to recommend new content to the user and for calculating the activity level.

### To Do

* [x] Research tools (like signals) to keep track of user activity.
* [x] Implement necessary model(s) to keep user data.
* [x] Create necessary signals.
* [x] Create mixin(s) to quickly add signals to existing views.
* [x] Update existing APIs with signals when necessary.

### Deadline

13.12.2022 @23.59

### Reviewers

@KarahanS @mumcusena @serdarakol

**Comment by BElifb** [comment]
* Created history as a separate app.
* Created the History model to keep track of different types of user activity.
* Created a signal (+ receiver) to activate creation of History instance when a page is visited (i.e. when related API is called).
* Couldn't create mixins as the related existing APIs were not class based. Instead created decorators, but since there is no way of trivially reaching the object of FBVs not using this right now. Will look more into later.
* Instead I added the signal code to the API views manually. This shouldn't be too much of a problem, since this won't be done in very many places.
* Connected the history to admin site.
* Created a receiver for the signal and connected.
* Tested the functionality using Postman and the Admin site, and we are getting history instances. 👍 
* Right now we are only tracking when a user **visits an ArtItem page** and **another User's profile**. We can make additions if need be.

**Comment by KarahanS** [comment]
Reviewed and approved. Left a small reminder related to exhibitions.

**Comment by BElifb** [comment]
* Added **number_of_views** field to ArtItem.
* Decided to add exhibition history later.
* PR is merged.
