### ISSUE TITLE
BE-35: Art Item Category

### ISSUE THREAD

**Issue by BElifb** [bounswe/bounswe2022group8#357]
### What's up?

We have decided to update category(type) field of art item to have limited predefined options. Since this will help us classify similarity of art items easily and also feels more fitting overall.

### To Do

* [x] Research & define categories for our app.
* [x] Create enumerated choices for art item category(type).
* [x] Update Art Item APIs if need be.

### Deadline

18.12.2022 @23.59

### Reviewers

@KarahanS @serdarakol

**Comment by BElifb** [comment]
* Created #358

**Comment by KarahanS** [comment]
Reviewed the PR, everything seems ok. Approved.

**Comment by BElifb** [comment]
PR is merged, closing the issue
