### ISSUE TITLE
Timetable for the second week

### ISSUE THREAD

**Issue by dundarmete** [bounswe/bounswe2022group8#36]
**To Do**: Do not forget to fill out the timetable for the second week. It is a weekly reminder :)

- [x] Serdar Akol
- [x] Karahan Sarıtaş
- [x] Sena Mumcu
- [x] Mustafa Cihan
- [x] Serhat Hebun Şimşek
- [x] Elif Bayraktar
- [x] Doğukan Türksoy
- [x] Furkan Keskin
- [x] Metehan Dündar
- [x] Sinem Koçoğlu

**Comment by serdarakol** [comment]
I saw sinem also submit hers personal weekly effort, hence closing the issue
