### ISSUE TITLE
FE-24: Like

### ISSUE THREAD

**Issue by kostanya** [bounswe/bounswe2022group8#362]
### What's up?

We need to design and implement _Like_ interface.

### To Do

- [x] Create the necessary interfaces for the like functionality.
- [x] Connect it to backend.

### Deadline

19.12.2022 _@23.59_

**Comment by kostanya** [comment]
Items mentioned above are implemented.

**Comment by sinemKocoglu** [comment]
Reviewed #374, everything is ok. Completed.
