### ISSUE TITLE
Adding non-functional requirements: Accessibility

### ISSUE THREAD

**Issue by mustafa-cihan** [bounswe/bounswe2022group8#37]
**To-do:** 
- Adding accessibility non-functional requirements to the [Requirements wiki page](https://github.com/bounswe/bounswe2022group8/wiki/Requirements).
- Make additions to the glossary if you see anything missing

**Deadline:** 14.03.2022

**Comment by mustafa-cihan** [comment]
Accessibility requirements are added.

**Comment by kostanya** [comment]
We have mentioned annotations twice under the non-functional tab. I think one is enough as they need to be as independent as possible. Other than that, great job.
