### ISSUE TITLE
FE-26: Delete Art Item

### ISSUE THREAD

**Issue by kostanya** [bounswe/bounswe2022group8#373]
### What's up?

Delete Art Item functionality and the related interfaces must be implemented.

### To Do

- [x] Create the necessary interface for the delete art item functionality.
- [x] Connect it to the backend.

### Deadline

23.12.2022 _@23.59_

**Comment by kostanya** [comment]
Items mentioned above are implemented.

**Comment by sinemKocoglu** [comment]
Revewed #375 on discord together with @kostanya. Everything is fine.  Thanks!
