### ISSUE TITLE
FE-28: Tags

### ISSUE THREAD

**Issue by kostanya** [bounswe/bounswe2022group8#378]
### What's up?

Necessary interfaces for tags should be implemented and connected to backend.

### To Do

- [x] Tag selection should be done with dropdowns.
- [x] An interface for search via tags should be added.
- [x] A draft interface for search results should be designed and implemented

### Deadline

24.12.2022 _@23.59_

**Comment by kostanya** [comment]
Above items are implemented. Now user can use tags below an art item for searching.

**Comment by sinemKocoglu** [comment]
Completed.
