### ISSUE TITLE
Adding Non-functional Requirements: Availability and Privacy

### ISSUE THREAD

**Issue by mumcusena** [bounswe/bounswe2022group8#38]
**To Do:**

- Adding availability and privacy non-functional requirements to the [Requirements wiki page](https://github.com/bounswe/bounswe2022group8/wiki/Requirements).
- Make additions to glossary if you see anything missing.

_Deadline: 14.03.2022 @23.59_

**Comment by mumcusena** [comment]
The availability and privacy requirements are added to [Requirements](https://github.com/bounswe/bounswe2022group8/wiki/Requirements). Please review and make adjustments in case needed @kostanya @mustafa-cihan  @BElifb.

**Comment by mustafa-cihan** [comment]
Fixed the typo. Nicely done.
