### ISSUE TITLE
FE-29: Online exhibitions

### ISSUE THREAD

**Issue by kostanya** [bounswe/bounswe2022group8#383]
### What's up?

We need to implement both online and offline exhibiton interfaces and connect them to backend.

### To Do

- [x] Create the necessary interfaces for online exhibitions on the profile page.
- [x] Create a page for online exhibitons.
- [x] Connect online exhibitions to backend.
- [x] Implement the necessary parts of the above for the _other's profile page_.

### Deadline

25.12.2022 _@23.59_

**Comment by sinemKocoglu** [comment]
Completed and merged related pr.
