### ISSUE TITLE
MOB-24: Like Functionality

### ISSUE THREAD

**Issue by mustafa-cihan** [bounswe/bounswe2022group8#399]
### What's up?

We need to make like button interactive.

### To Do

- [x] Make like button interactive
- [x] Change like icon when pressed

### Deadline

26.12.2022

### Reviewers

@ooodogodogodogo @MustafaEmreErengul

**Comment by mustafa-cihan** [comment]
@ooodogodogodogo changes made and pushed. Waiting for review

**Comment by MustafaEmreErengul** [comment]
Reviewed. It works as expected. Great!
