### ISSUE TITLE
Wiki: Favourite Github Repositories

### ISSUE THREAD

**Issue by KarahanS** [bounswe/bounswe2022group8#4]
**To Do**: Explore GitHub to discover some repositories. Document them by providing
their references and describing what you liked about them. Add your findings to [Favourite Github Repositories](https://github.com/bounswe/bounswe2022group8/wiki/Favourite-Github-Repositories).

- [x] Sena Mumcu
- [x] Karahan Saritas
- [x] Serdar Akol
- [x] Elif Bayraktar
- [x] Mustafa Cihan
- [x] Metehan Dundar
- [x] Furkan Keskin
- [x] Sinem Kocoglu
- [x] Serhat Hebun Simsek
- [x] Dogukan Turksoy

**Comment by mumcusena** [comment]
I added my favorite repository and with the use of Grammarly, I fixed some grammar mistakes in [Favourite Github Repositories](https://github.com/bounswe/bounswe2022group8/wiki/Favourite-Github-Repositories).
