### ISSUE TITLE
Scenario&Mockups: Write the Third Scenario

### ISSUE THREAD

**Issue by KarahanS** [bounswe/bounswe2022group8#40]
**To Do**: Write the third scenario which focuses on the concept of online gallery and collaboration between creators. As pointed out in the specification, a proper scenario shall include:
* The user and their persona (role)
* Preconditions – if any (such as: the user that has already logged in).
* Specific actions to achieve some desired goal (what the user wants to do). Describe
each step until the scenario is completed. Steps must be enumerated.
* Acceptance criteria (the conditions that describe a successful outcome for the action).

Third scenario is planned to depict the actions required for publishing an online gallery and adding another user as collaborator. It involves private message functionality.
Specific actions should be supported with visual material. 
_Deadline_: 23.03.2022 @12.00

**Comment by sinemKocoglu** [comment]
Actions and photos were added.
(?)s were removed with appropriate requirement numbers.

**Comment by KarahanS** [comment]
Added persona, story and preconditions. Updated the photos to highlight some keypoints and enrich the content of the homepage. Updated actions to give more insights. Review required.

**Comment by sinemKocoglu** [comment]
Reviewed, no action taken. Thanks.
