### ISSUE TITLE
MIL-24: Class Diagram

### ISSUE THREAD

**Issue by KarahanS** [bounswe/bounswe2022group8#419]
### What's up?

This is a sub-issue of #418.
We have to keep all of our artifacts up to date as the implementation stage is over. Class diagram is one of the most important software design document we have to update. Current class diagram can be found [here](https://github.com/bounswe/bounswe2022group8/wiki/Class-Diagram). Most recent version of the class diagram will be added soon. 

### To Do

- [x] Update the class diagram based on our models.
- [x] Attach the diagram in png format to the related [section](https://github.com/bounswe/bounswe2022group8/wiki/Class-Diagram).

### Deadline

02.01.2022 @19.00

### Reviewers

@BElifb

**Comment by KarahanS** [comment]
Class diagram is updated. Status report and the new diagram can be found [here](https://github.com/bounswe/bounswe2022group8/wiki/Class-Diagram).

**Comment by BElifb** [comment]
* Just when I was about to say did you share the link to edit the diagram, realized you created a readonly one.
* Thanks for all the efforts looks pretty good.

**Comment by KarahanS** [comment]
Reviewed, closing the issue.
