### ISSUE TITLE
MIL-26 User Manual 

### ISSUE THREAD

**Issue by serdarakol** [bounswe/bounswe2022group8#422]
### What's up?

writing the user manual documents for mobile application and web application of the project

### To Do

- [x] write user manual of mobile application
- [x] write user manual of web application

### Deadline

02.01.2023 @23.59

**Comment by serdarakol** [comment]
related to #418

**Comment by serdarakol** [comment]
web app user manual is avaliable [here](https://github.com/bounswe/bounswe2022group8/blob/master/Deliverables/CMPE451_Customer_Presentation_Milestone_3/web_app_user_manual.md)

**Comment by serdarakol** [comment]
mobile app user manual is [here](https://github.com/bounswe/bounswe2022group8/blob/master/Deliverables/CMPE451_Customer_Presentation_Milestone_3/mobile_app_user_manual.md)

**Comment by serdarakol** [comment]
review is needed. @KarahanS @ooodogodogodogo @BElifb @mumcusena

**Comment by erengulm** [comment]
Thanks Serdar! No further action is required. Closing the issue.
