### ISSUE TITLE
MIL-29: Status of the requirements

### ISSUE THREAD

**Issue by BElifb** [bounswe/bounswe2022group8#425]
### What's up?

As part of section b (progress based on teamwork) of Group Milestone report, we will provide a list of requirements being either not started, in progress, or completed. As stated in #418.

### To Do

* [x] Go through the initial requirements and mark them as  being either not started, in progress, or completed.
* [x] Either add to the milestone report or add to a separate wiki page and provide the link.

### Deadline

02.01.2023 @23.55

### Reviewers

@KarahanS @sinemKocoglu @ooodogodogodogo

**Comment by BElifb** [comment]
* Went through the requirements on [wiki page](https://github.com/bounswe/bounswe2022group8/wiki/Requirements) and marked them as (Completed), (In progress) and (Not started). Consulted with frontend and mobile teams on some items.

**Comment by mumcusena** [comment]
Hey, reviewed the requirements, I think we are GTG and you can close the issue.

**Comment by KarahanS** [comment]
Annotations in the *satisfied requirements* do not comply with the annotations in the *requirements*. Could you update them as well? Right now, it looks like we only satisfied two annotation related requirements - whereas we satisfied a majority of them according to our requirements.
