### ISSUE TITLE
MIL-30: Status of The Annotations in Mobile Application

### ISSUE THREAD

**Issue by mustafa-cihan** [bounswe/bounswe2022group8#426]
### What's up?

As a part of milestone 3, we need to explain the status of the annotations in application as stated in #418..  

### To Do

- [x] Summarize annotations functionality in mobile.
- [x] Add summary to report. 

### Deadline

02.01.2023

### Reviewers

@mustafa

**Comment by mustafa-cihan** [comment]
@MustafaEmreErengul please review mobile annotations in group review deliverable.

**Comment by MustafaEmreErengul** [comment]
Reviewed and appreciated. No further actions is required. Closing the issue.
