### ISSUE TITLE
MIL-32: Use Case Diagram Update

### ISSUE THREAD

**Issue by BElifb** [bounswe/bounswe2022group8#428]
### What's up?

As stated in #418, a part of Project Artifacts, Use Case Diagram should be updated.

### To Do

* [x] Update the diagram in lucidchart.
* [x] Upload to github.

### Deadline

02.01.2023 @23.55

### Reviewers

@mumcusena @KarahanS

**Comment by BElifb** [comment]
* Updated the use case diagram.
* Exported and uploaded the new version to [wiki page](https://github.com/bounswe/bounswe2022group8/wiki/Use-case-diagram)

**Comment by KarahanS** [comment]
Reviewed the document, thank you for the efforts. Some corrections I had in mind:
* We can't annotate comments unfortunately. It was a little bit buggy on the frontend - therefore we decided not to deal with it given the limited amount of time, I think it should be marked as 'not completed' in the requirements as well.
* Maybe we can enrich the use case action "Add items to an exhibition" by adding two extending features: "Add items from gallery" and "Add items via uploading".
* Also, I think we should add a feature like "View art items by tag", which means getting all the art items based on the tags of another art item.
* One little note: Red arrow of the feature "See the annotations made by the other users", blocks some of the text. That'd be great if you could carry that arrow to a little bit left.

**Comment by BElifb** [comment]
* Made the mentioned minor corrections and enhancements.
* Didn't add _View art items by tag_ as it already existed as an extension of search.
@KarahanS

**Comment by KarahanS** [comment]
Approved the changes, no further action is required.
