### ISSUE TITLE
MIL-33:Deployment

### ISSUE THREAD

**Issue by ooodogodogodogo** [bounswe/bounswe2022group8#430]
### What's up?

Deployment of frontend,mobile, backend and annotations.

### To Do

- [x] Deploy frontend.

- [x] Deploy backend.

- [x] Deploy annotations.

- [x] Deploy android.

### Deadline

27.12.22 @12.00

### Reviewers

@KarahanS @kostanya

**Comment by erengulm** [comment]
Reviewed and appreciated. Good work! No further actions is required. Closing the issue.
