### ISSUE TITLE
MIL-34:System Manual of Mobile and Frontend

### ISSUE THREAD

**Issue by ooodogodogodogo** [bounswe/bounswe2022group8#431]
### What's up?

Since @kostanya was not available, I have completed system manuals for mobile and frontend.

### To Do

- [x] System Manual of Frontend

- [x] System Manual of Mobile

### Deadline

02.01.2023 @23.00

### Additional Information

You can find link [here](https://github.com/bounswe/bounswe2022group8/wiki/System-Manual)

### Reviewers

@KarahanS  @kostanya @MustafaEmreErengul

**Comment by MustafaEmreErengul** [comment]
Reviewed and appreciated. No further actions is required. Closing the issue.
