### ISSUE TITLE
MIL-35: Status of Deliverables

### ISSUE THREAD

**Issue by ooodogodogodogo** [bounswe/bounswe2022group8#432]
### What's up?

Complete List and Status of Deliverables for Milestone 3.  

### To Do

- [x] Creating list and status of deliverables 

### Deadline

02.01.23 @23.00

### Additional Information

#418

### Reviewers

@MustafaEmreErengul @mustafa-cihan

**Comment by MustafaEmreErengul** [comment]
Reviewed and appreciated. No further actions is required. Closing the issue.
