### ISSUE TITLE
MIL-36: Reflections to the Final Milestone Demo

### ISSUE THREAD

**Issue by MustafaEmreErengul** [bounswe/bounswe2022group8#433]
### What's up?

Summarizing the things we did on Final Milestone demo day and briefly explaining what were the weak and strong sides of our presentation. 

### To Do

- [x] Writing our group's reflection about the Final Milestone Demo to the Final Milestone Report.

### Deadline

02.01.2022 @23.59

### Reviewers

@ooodogodogodogo @mustafa-cihan

**Comment by MustafaEmreErengul** [comment]
#418

**Comment by erengulm** [comment]
No further actions is required. Closing the issue.
