### ISSUE TITLE
MIL-37: Art Follower User Scenario 

### ISSUE THREAD

**Issue by MustafaEmreErengul** [bounswe/bounswe2022group8#434]
### What's up?

Since we completed and finalized our product, our user scenarios must be up-to-date with our current project status. So some changes should be done on our user scenarios. So it is better to differentiate the scenarios we made in Cmpe352 and Cmpe451 to see the changes clearly. 

### To Do

- [x] Creating the last version of the Art Follower User Scenario and keeping the older version to see the changes.

### Deadline

02.01.2022 @23.59

### Reviewers

@ooodogodogodogo @mustafa-cihan

**Comment by MustafaEmreErengul** [comment]
#418

**Comment by erengulm** [comment]
No further actions is required. Closing the issue.
