### ISSUE TITLE
MOB-26: Visiting Another User's Profile

### ISSUE THREAD

**Issue by MustafaEmreErengul** [bounswe/bounswe2022group8#435]
### What's up?

As a user of Artopia, one can reach other users' profile and see their all art contributions and their profile informations. (Name, Surname, Bio, Location, etc.) This page have a bit more restricted view from the user's own profile.

### To Do

- [x] A new type of profile page should be implemented.
- [x] By clicking username or profile thumbnails one should be directed to related profile page

### Deadline

27.12.2022 @13.00 

### Reviewers

@ooodogodogodogo @mustafa-cihan

**Comment by mustafa-cihan** [comment]
@MustafaEmreErengul Thank you for your effort.
