### ISSUE TITLE
MIL-38: Adding Mobile UI to Document

### ISSUE THREAD

**Issue by mustafa-cihan** [bounswe/bounswe2022group8#436]
### What's up?

As part of deliverable document we need to show each mobile page in document.

### To Do

- [x] Take a screenshot of each page
- [x] Add them to deliverable document.

### Deadline

02.01.2023

### Reviewers

@MustafaEmreErengul

**Comment by mustafa-cihan** [comment]
@MustafaEmreErengul @dundarmete I added pages to document. Please review and add if anything is missing

**Comment by MustafaEmreErengul** [comment]
Reviewed and appreciated. Good work! Nothing is missing. Closing the issue.
