### ISSUE TITLE
MOB-27: Following and Unfollowing Functionality

### ISSUE THREAD

**Issue by MustafaEmreErengul** [bounswe/bounswe2022group8#438]
### What's up?

As a user of Artopia, one can follow or unfollow a user by simply clicking a button in the related user's profile page. This change should also be viewed from followers/following page in the profiles.

### To Do

- [x] A follow unfollow button should be implemented.
- [x] Sudden and fast increase/decrease in the followers/following numbers should be provided. (before the backend request)

### Deadline

27.12.2022 @13.00

### Reviewers

@ooodogodogodogo @mustafa-cihan

**Comment by mustafa-cihan** [comment]
@MustafaEmreErengul works fine. closing.
