### ISSUE TITLE
MOB-28: Search Page and Searching Functionality

### ISSUE THREAD

**Issue by MustafaEmreErengul** [bounswe/bounswe2022group8#439]
### What's up?

As a user of Artopia, one can search for other users' username or other users' art item from a separate search page which is located on the bottom navigation bar. The art item search will be based on the keywords that an art item headline or description includes. The username search will be based on the character similarity. The results of both searches will be shown in listed view.

### To Do

- [x] Search Page including two different search option button should be implemented.
- [x] Username Search functionality should be implemented.
- [x] Art Item Search functionality should be implemented.
### Deadline

27.12.2022 @13.00 

### Reviewers

@ooodogodogodogo @mustafa-cihan

**Comment by mustafa-cihan** [comment]
@MustafaEmreErengul Reviewed. No further action required. Thanks
