### ISSUE TITLE
Scenarios & Mockups: Second scenario 

### ISSUE THREAD

**Issue by BElifb** [bounswe/bounswe2022group8#44]
Prepare the second scenario which focuses on the features of logging in, adding a new art item and selling it.
**To Do:**  
* Write about the user and their persona (role).
* Decide on preconditions – if any (such as: the user that has already logged in).
* Finalize and enumerate specific actions to achieve the desired goal (what the user wants to do). Describe
each step until the scenario is completed.
* Decide on acceptance criteria (the conditions that describe a successful outcome for the action).
* Prepare the visuals for the steps  described above.
* Put together all of the above in the designated [wiki page](https://github.com/bounswe/bounswe2022group8/wiki/Scenario-2).

**Main Steps of the Second Scenario** are
* Logging in
* Entering Add Art Item page
* Adding the art item with specifications
* Returning to personal page
* Receiving a notification about an offer
* Accepting the offer

**Deadline:**  
23.03.2022 @12.00

**Comment by BElifb** [comment]
Added persona, preconditions and acceptance criteria. Acceptance criteria requires review @kostanya @dundarmete

**Comment by kostanya** [comment]
Acceptance criteria look pretty good. Great job.

**Comment by kostanya** [comment]
Added notification and offer related frames, reorganized the log in screen frame with the help of @dundarmete and lastly changed the ratios of all the frames in our scenario so that they have identical templates.

**Comment by BElifb** [comment]
Created Adding Art Item frame

**Comment by BElifb** [comment]
Matched Acceptance criteria with requirements. [Requirements](https://github.com/bounswe/bounswe2022group8/wiki/Requirements) need detailing especially about Art Item Addition, Payment&Bidding system and Notifications. Not making any changes currently, until some group decisions are made.

**Comment by kostanya** [comment]
Everything looks neat.
