### ISSUE TITLE
Meeting Notes: Week #4 Meeting #6

### ISSUE THREAD

**Issue by KarahanS** [bounswe/bounswe2022group8#46]
**To Do**: Add the meeting notes for week-4 meeting-6 to the sidebar menu and homepage menu. Add the questions and answers gathered during the customer meeting. 

_Deadline:_ 27.03.2022 @20.00

**Comment by KarahanS** [comment]
Created the meeting notes page and connected necessary link. Meeting notes can be found [here](https://github.com/bounswe/bounswe2022group8/wiki/Week-4-Meeting-%236---Customer-Meeting-I). Review required in case anything missing from our customer meeting.

**Comment by kostanya** [comment]
Summarizes everything we spoke quite clearly. Thanks for the effort.
