### ISSUE TITLE
Software Design: Use Case Diagram

### ISSUE THREAD

**Issue by KarahanS** [bounswe/bounswe2022group8#47]
**To Do**: Design the use case diagram that shows the interaction between the users and the functionalities they may perform. [Lucidchart](https://lucid.app/documents) is used to work on the diagram in a collaborative manner. Please refer to the link of the working place available in our Discord.  As discussed in the [Meeting - 7](https://github.com/bounswe/bounswe2022group8/wiki/Week-5-Meeting-%237), everyone should be contributing to the diagram. Please comment down your contributions.
After completing the diagram, it shall be exported and putted into the related wiki page.

Deadline: 03.04.2022 @23.59

**Comment by KarahanS** [comment]
Created following **actors**:
* Level 0 - Guest User
* Level 1 - Registered User 
* Level 2 - Active User
* Moderator

I've created following **actions**:
* functionalities for guest user
* sign-in and sign-up
* search and filtering functionalities
* viewing a profile page
* viewing a publicly visible art item
* viewing a private art item
* getting most popular artworks on our homepage
* login for registered user
* following, viewing private art item
* making an offer for an art item
* commenting/ viewing private art items
* applying for verified account
* feature of getting recommendations based on activity
* deleting an art item from your gallery

desperately waiting for your contributions

**Comment by BElifb** [comment]
Reviewed the current state of the diagram. Made the following changes:
* Made additions to the selling functionality about receiving offers and notifications.
*  Modified the schema and made additions to the exhibition functionality. (not complete)
*  Made some notes about the things we may want to add, such as open for sale option in the adding item stage.

**Comment by KarahanS** [comment]
* Specified **Search Engine**, **Registration System**, **Copyright Protection System**, **Bidding System**, **Exhibition System**.
* Modified exhibition system in accord with your annotations on the chart. Please review.
* Modified copyright system. Added the "selecting the 'option for sale'" action and made it required by adding an _includes_ relation.


Some questions about recent additions:
* Should we send mail to each user when moderator adds a new type to the system? Is it necessary? Or why not sending a notification rather then sending an e-mail?
* Should a user be able to delete a comment made by another user to his art item? In our meetings, it was one of our questions we didn't give a precise decision yet.

**Comment by BElifb** [comment]
* I had forgotten that we decided to make "option to sale" privileged, looks great.
* Added some more notifications and the confirmation of **sale complete** for both parties.
*  Added receive & accept/decline invitation for participation in the exhibition.
*  I think we should consider separating single user vs collaborative exhibitions, to possibly avoid complexity.
*  Also a fixed time for the offers could be easier.  

About the questions;
*  I think a notification suffices, but both are okay.
*  My only concern is whether it would complicate visibility settings or not.
@KarahanS

**Comment by mumcusena** [comment]
Reviewed the current state of the diagram and made the following changes:

- added new actions to the copyright protection system
- included an action for getting an application about account verification and extended it to two new actions.

with the help of @kostanya and @mustafa-cihan

**Comment by kostanya** [comment]
Updated bidding system and decided that:

- The system shall automatically mark the art item as sold as soon as the offer is accepted.
-  In case of any transaction problem, the person who has the problem should send a ticket to the admin.

with @KarahanS and @mustafa-cihan .

**Comment by mustafa-cihan** [comment]
Reviewed the current state of the diagram with @mumcusena  and @KarahanS. Made the following changes:

- Fixed the issue in Level 1 users follows a user action.
- View an art item action is revisited and made required changes.
- Reviewed the bidding system.
- Reviewed the exhibition system. Ticket sending action is added.

**Comment by KarahanS** [comment]
Reviewed the use case diagram online with:
@kostanya 
@serdarakol  
@BElifb 
@mumcusena 
@simsekhebun
@mustafa-cihan 
@sinemKocoglu 

* Modified the exhibition system in order to correct some mistakes.
* Added report action for inappropriate content.
* Replaced _search_ action with _semantic search_.

After our online session. I created _Filter_ action and linked all the filtering options to the filter with **generalization** relationship. Also linked _participating as a collaborator_ and _participating as an organizer_ to _participating in an exhibition_ with **generalization** relationship. Asked a question about this on [Slack](https://app.slack.com/client/T033R4AS4CF/C03509V7ZPC). We should update it according to the answer.
One last review is required to finalize our work.

**Comment by KarahanS** [comment]
Updated _Search_ use case to provide two extend use cases, namely _Lexical Search_ and _Semantic Search_.

**Comment by KarahanS** [comment]
In accordance with our discussion, we decided that first version of our requirements and therefore use case has taken its final form. Closed the issue.
