### ISSUE TITLE
Meeting Notes: Week 5 Meeting #7

### ISSUE THREAD

**Issue by simsekhebun** [bounswe/bounswe2022group8#48]
**To Do**: Adding the meeting notes for week 5 and linking the page to the sidebar menu and homepage menu.

_Deadline:_ 02.04.2022 23:59

**Comment by simsekhebun** [comment]
Created the meeting notes page and linked it to the sidebar. Review required.

**Comment by kostanya** [comment]
Great coverage of such a long meeting. Edited some typos.
