### ISSUE TITLE
Software Design: Sequence Diagram

### ISSUE THREAD

**Issue by KarahanS** [bounswe/bounswe2022group8#50]
**To Do**: Design the sequence diagram in order to show the object interactions in the system arranged in a time sequence.  [Lucidchart](https://lucid.app/documents) is used to work on the diagram in a collaborative manner. Please refer to the link of the working place available in our Discord channel. As discussed in the [Meeting - 7](https://github.com/bounswe/bounswe2022group8/wiki/Week-5-Meeting-%237), everyone should be contributing to the diagram. Please comment down your contributions.
Refer to the use case and class diagrams mentioned in #47 and #49 during the design stage.
After completing the diagram, it shall be exported and putted into the related wiki page.

**Checklist:**
 - [x] Elif Bayraktar: Bid for an art item
 - [x] Serdar Akol: Share an art item
 - [x] Sena Mumcu: Sign in
 - [x] Karahan Sarıtaş: Comment on an art item
 - [x] Mustafa Cihan: Reset password
 - [x] Serhat Hebun Şimşek: Send a copyright ticket
 - [x] Doğukan Türksoy: Sign up
 - [x] Furkan Keskin: Follow a user
 - [x] Metehan Dündar: Send private message to a user
 - [x] Sinem Koçoğlu: Organize an exhibition

**Strict Deadline**: <del>10.04.2022</del> 14.04.2022 @19.00

**Comment by KarahanS** [comment]
Designed _Commenting on an Art Item_ sequence diagram, it is available at the link provided in Discord channel.

**Comment by sinemKocoglu** [comment]
Sequence diagram for _Holding an Exhibition_ is available now in Lucidchart. Because it is necessary, some functions are added in Exhibition class in the class diagram.

**Comment by mumcusena** [comment]
Designed _Signing In_ sequence diagram, it is available now in Lucidchart link shared privately with the team members.

**Comment by mustafa-cihan** [comment]
Designed Resetting Password sequence diagram, it is available in Lucidchart.

**Comment by kostanya** [comment]
Designed _Following a user_ sequence diagram, it is available in Lucidchart. Required functions and fields are added to _Registered User Class_ and _NotificationType_ in the class diagram.

**Comment by serdarakol** [comment]
Sequence diagram for sharing an art item is now available on our lucid.app project. I kindly request for reviews if I missed something.

**Comment by serdarakol** [comment]
I have reviewed most of sequence diagrams, We, @mumcusena @mustafa-cihan and I discussed about the alternative box usage and made necessary changes.

**Comment by serdarakol** [comment]
I have reviewed @BElifb 's sequence diagram and made a small change for consistency between sequence diagram.
add(bid: Bid) ==> changed to inster(Bid) further more @BElifb please add a status code for returning value of the insert function
not only ok but maybe also StatusCode=200.
For making a convention further information is discussed on discord

**Comment by simsekhebun** [comment]
Reviewed the sequence diagrams and finished sending a copyright ticket diagram

**Comment by BElifb** [comment]
> I have reviewed @BElifb 's sequence diagram and made a small change for consistency between sequence diagram. add(bid: Bid) ==> changed to inster(Bid) further more @BElifb please add a status code for returning value of the insert function not only ok but maybe also StatusCode=200. For making a convention further information is discussed on discord

As the professor stated in slack "You can indicate the database transactions with natural language.", I chose to do so. There's also such an instance in page #39 of the relevant slides. But I can change it if that's the group's will.

**Comment by BElifb** [comment]
* Don't forget to update the class diagram, if you make any changes in return types of functions while fixing what's stated above.

**Comment by ooodogodogodogo** [comment]
Designed "Editing a Comment" rather than "Sign Up", according to the team's decision.

**Comment by KarahanS** [comment]
> There are also some functions in the diagrams that are called from and returned to completely different classes.

Made little modifications on **Sequence Diagram: Resetting Password** to avoid this problem. Could you please review @mustafa-cihan?

**Comment by KarahanS** [comment]
You can find sequence diagrams [here](https://github.com/bounswe/bounswe2022group8/wiki/Sequence-Diagrams).
