### ISSUE TITLE
Meeting Notes: Week 5 Meeting #9

### ISSUE THREAD

**Issue by kostanya** [bounswe/bounswe2022group8#52]
**To Do:** Add meeting notes of week 5 meeting 9 to the wiki page mentioning attendees, action, and discussion items.

_Deadline:_ 06.04.2022 @23.59

**Comment by KarahanS** [comment]
Reviewed the [meeting notes](https://github.com/bounswe/bounswe2022group8/wiki/Week-5-Meeting-Notes-%239). Thanks for the effort.
