### ISSUE TITLE
Requirements Elicitation: Classification of User Classes

### ISSUE THREAD

**Issue by KarahanS** [bounswe/bounswe2022group8#53]
**To Do**: As the last phase of the requirements elicitation, [Requirements](https://github.com/bounswe/bounswe2022group8/wiki/Requirements) must be revised and validated in accordance with our software design. Tasks for the classification of user classes:
* Update the [glossary](https://github.com/bounswe/bounswe2022group8/wiki/Requirements#glossary) to include _User_, _RegisteredUser_, _GuestUser_, _ActiveUser_ and _Moderator_.
* Update the [User Requirements](https://github.com/bounswe/bounswe2022group8/wiki/Requirements#11-user-requirements) in order to include different functionalities for different _User_ classes listed above.

*Deadline:*
10.04.2022 @19.59

**Comment by KarahanS** [comment]
Overall, switched from "user" to "registered user" and "active user" in the requirements. Additionally, made the following changes:
* Added ```1.1.1.6``` to allow users change their passwords from settings (not only from login page).
* Updated ```1.1.1.7``` to include that deletion of an account also deletes the content/interaction made by that account.
* Added ```1.1.1.1.1.``` to include confirmation email for registration.
* Added ```1.1.2.4.``` to allows guest users get most popular artworks to the homepage (however not recommendations or artworks shared by followed accounts).
* Added ```1.1.2.5.``` to allow guest users use search engine.
* Added ```1.1.3.1. ``` to indicate the existence of a profile page. Then listed the related functionalities below.
* Modified ```1.1.3.5.``` to include the visibility option.
* Changed the definition of **discussion** and **reply** in the glossary. Removed **userID** since it is not referenced in the requirements.
* Modified ```1.2.8.``` level system. Listed functionalities provided for different levels, level by level.

Some of the article numbers have changed. Refer to #55, #59 and #61.
Please make a **critical review** of the changes before closing the issue. Comment down if there is any problem/recommendation.

**Comment by sinemKocoglu** [comment]
There is an inconsistency in terms of 1.2.8.3.3.
In use case diagram and sequence diagram are designed that registered user shall hold an exhibition.
In requirements 1.2.8.3.3. and 1.1.6.1 stated that active user shall hold an exhibition.
I updated requirements according to diagrams.

**Comment by KarahanS** [comment]
Great catch, thank you for the review.
