### ISSUE TITLE
Requirements Elicitation: User Interaction

### ISSUE THREAD

**Issue by KarahanS** [bounswe/bounswe2022group8#54]
**To Do**: As the last phase of the requirements elicitation, [Requirements](https://github.com/bounswe/bounswe2022group8/wiki/Requirements) must be revised and validated in accordance with our software design. Tasks for the user interaction:
* Update the _User Interaction_ section of the [User Requirements](https://github.com/bounswe/bounswe2022group8/wiki/Requirements#11-user-requirements) in order to include different functionalities discussed in the meetings including (but not limited to):
> Unfollow a followed user
Reply to a comment (reply will be regarded as another comment)
Like a comment
Block a user (more discussion required)

* Update the [glossary](https://github.com/bounswe/bounswe2022group8/wiki/Requirements#glossary) if necessary.

*Deadline:*
10.04.2022 @19.59

**Comment by serdarakol** [comment]
Reviewed the requirements. I see some of the requierements includes more than one abilities. such as 1.1.4.1 includes both follow and unfollow. or there are some requirements that needs more explanations. attending an exhibition offline ?
