### ISSUE TITLE
Scenario&Mockups: Acceptance Criteria Review for Scenario I

### ISSUE THREAD

**Issue by KarahanS** [bounswe/bounswe2022group8#55]
**To Do**:  Requirements elicitation phase may introduce new requirements, or modify the existing ones. Layout of the [requirements](https://github.com/bounswe/bounswe2022group8/wiki/Requirements) may change, therefore article numbers may change. Review for acceptance criteria of the [first scenario](https://github.com/bounswe/bounswe2022group8/wiki/Scenario:-Art-Follower-User) is required. Please comment down below the changes you made if any.

- [x] @serdarakol 
- [ ] @simsekhebun 
- [ ] @KarahanS 

*Deadline:*
14.04.2022 @23.59

**Comment by serdarakol** [comment]
On the mockup, we should clear the ambuiguity of username gmail pasword. it should be consistent with requirement doc.

**Comment by serdarakol** [comment]
accepting criterias are updated. some related requierements are also changed
