### ISSUE TITLE
Requirements Elicitation: Search Engine

### ISSUE THREAD

**Issue by mumcusena** [bounswe/bounswe2022group8#58]
*To Do:* As the last phase of the requirements elicitation, [Requirements](https://github.com/bounswe/bounswe2022group8/wiki/Requirements) about Search Engine must be revised and validated in accordance with our software design

* Update the Search Engine section of the [System Requirements](https://github.com/bounswe/bounswe2022group8/wiki/Requirements#12-system-requirements) in order to include different functionalities discussed in the meetings.

* Update the [glossary](https://github.com/bounswe/bounswe2022group8/wiki/Requirements#glossary) if necessary.

_Deadline:
 10.04.2022 @19.59_

**Comment by mumcusena** [comment]
* Updated the [system requirements](https://github.com/bounswe/bounswe2022group8/wiki/Requirements#12-system-requirements) by adding the requirements 1.2.2.3, 1.2.2.4 and 1.2.2.5.
* Added "Title" to the glossary.

**Please review my additions to the requirements.** @serdarakol @mustafa-cihan @BElifb

**Comment by serdarakol** [comment]
I have reviewed the your contribution @mumcusena, I think searching by tag and searching by title is different occasions thats why I separated it into two requirements. 
* 1.2.2.5. The system shall support searching for art items by their title.
* 1.2.2.6. The system shall support searching for art items by their tags.

**Comment by ooodogodogodogo** [comment]
Reviewed, closed.
