### ISSUE TITLE
Scenario&Mockups: Acceptance Criteria Review for Scenario 2

### ISSUE THREAD

**Issue by mumcusena** [bounswe/bounswe2022group8#59]
**To Do**:  Requirements elicitation phase may introduce new requirements, or modify the existing ones. The layout of the [requirements](https://github.com/bounswe/bounswe2022group8/wiki/Requirements) may change, therefore article numbers may change. A review of the acceptance criteria of the [second scenario](https://github.com/bounswe/bounswe2022group8/wiki/Scenario-2) is required. Please comment down below the changes you made if any.

- [x] @mumcusena 
- [x] @kostanya  
- [x] @BElifb  

*Deadline:*
14.04.2022 @23.59

**Comment by mumcusena** [comment]
* Changed the requirement 1.2.9.1 to 1.1.5.1, because during requirements elicitations the mentioned requirement was changed.

**Comment by BElifb** [comment]
* Updated acceptance criteria in accordance with the new bidding system.
* Added Requirements 1.2.4.1, 1.2.4.2, 1.2.4.4 through 1.2.4.9 and 1.2.4.12. 
*  Added active user precondition.
* Highlighted the criteria that is directly related, left others as normal.

**Comment by kostanya** [comment]
- Changed the requirement 1.1.1.3 to 1.1.1.4 as it is updated.
- Updated requirements 1.1.3.6, 1.1.3.7 and 1.1.5.1 as their definitions are revised.
- Transformed the requirement 1.2.1 to 1.2.1.4 as our notification system is updated.
- Added the requirement 1.2.1.7 .
- Deleted 1.2.4 (payment system) as it does not exist anymore.

**Comment by KarahanS** [comment]
Thank you for the reviews. No additional action taken. Closed the issue.
