### ISSUE TITLE
Scenario&Mockups: Acceptance Criteria Review for Scenario 3

### ISSUE THREAD

**Issue by sinemKocoglu** [bounswe/bounswe2022group8#61]
**To Do:** Requirements elicitation phase may introduce new [requirements](https://github.com/bounswe/bounswe2022group8/wiki/Requirements), or modify the existing ones. The layout of the requirements may change, therefore article numbers may change. A review of the acceptance criteria of the [third scenario](https://github.com/bounswe/bounswe2022group8/wiki/Scenario-3) is required. Please comment down below the changes you made if any.

- [ ] @ooodogodogodogo 
- [ ] @dundarmete 
- [ ] @mustafa-cihan 
- [x] @sinemKocoglu 

Deadline:
_14.04.2022 @23.59_

**Comment by sinemKocoglu** [comment]
Existing requirements are updated according to current requirements.
1.1.6.4 , 1.1.6.7. and 1.1.6.8 are added to both requirements for Exhibition and acceptance criteria.

**Comment by sinemKocoglu** [comment]
Updated after changes made in issue #68 .

**Comment by KarahanS** [comment]
Made a quick review. Thank you for the effort @sinemKocoglu.
