### ISSUE TITLE
Requirements Elicitation: Activity History

### ISSUE THREAD

**Issue by simsekhebun** [bounswe/bounswe2022group8#62]
*To Do:* As the last phase of the requirements elicitation, [Requirements](https://github.com/bounswe/bounswe2022group8/wiki/Requirements) about activity history must be revised and validated in accordance with our software design.

* Update the [Requirements](https://github.com/bounswe/bounswe2022group8/wiki/Requirements) to include activity history and related glossary items.

* Update the [glossary](https://github.com/bounswe/bounswe2022group8/wiki/Requirements#glossary) to include Activity History and other glossary items if necessary.

_Deadline: 10.04.2022 @20.00_

**Comment by simsekhebun** [comment]
* Modified 1.2.3.1. slightly.
*  Added Activity History to [glossary](https://github.com/bounswe/bounswe2022group8/wiki/Requirements#glossary)

**Comment by KarahanS** [comment]
Reviewed the _Activity History_ section. I believe, more details should be provided such as:
* What does _activity history_ include? We've left some loose ends here, but options can be: 
     *  which art items user commented on
     * which art items user liked
     *  which art items under which user liked comments
     * which users user follows
     * which exhibitions user attended
   
Let's discuss it in order to finalize the _Activity History_ section.

**Comment by KarahanS** [comment]
Specified the details about the _Activity History_ while expanding the _Recommendation System_ subsection. Please refer to #69 for more detail.
