### ISSUE TITLE
Milestone1: Work Summary

### ISSUE THREAD

**Issue by BElifb** [bounswe/bounswe2022group8#65]
This is a sub-issue for the Milestone I Report #73.
As stated in _Assignment: Milestone Group Deliverable_ a summary of work done by each team member (in tabular format) must be added. 

**To Do:**
*  Create a summary of work done by you **(in tabular format)** until Milestone1.
*  Include URIs for relevant issues and Wiki pages.
*  You may include the currents status of your summary in you personal Timesheet page in wiki, to help with coherence. 

 **Checklist:**
 - [x] Elif Bayraktar
 - [x] Serdar Akol
 - [x] Sena Mumcu
 - [x] Karahan Sarıtaş
 - [x] Mustafa Cihan
 - [x] Serhat Hebun Şimşek
 - [x] Doğukan Türksoy
 - [x] Furkan Keskin
 - [x] Metehan Dündar
 - [x] Sinem Koçoğlu 

**Deadline:** 12.04.2022 @13.59

**Additional Information:**  
* You may refer to the relevant Discord channel for more detailed information about the task and examples.

**Comment by BElifb** [comment]
* Created my personal work summary. Added a copy to [timesheet page](https://github.com/bounswe/bounswe2022group8/wiki/Timesheet-Elif).
* Converting to pdf on hold until tomorrow.

**Comment by KarahanS** [comment]
* Converted my work summary to tabular form with links and issues.

**Comment by KarahanS** [comment]
Work summaries can be found [here](https://github.com/bounswe/bounswe2022group8/wiki/Work-Summary-by-Each-Member).
