### ISSUE TITLE
Requirements Elicitation: Notification and E-mail

### ISSUE THREAD

**Issue by kostanya** [bounswe/bounswe2022group8#66]
**To-Do:** As the last phase of the requirement elicitation, [requirements](https://github.com/bounswe/bounswe2022group8/wiki/Requirements) about notification system and e-mail related parts must be revised and updated in accordance with our most recent software design.

-  Add more details about notifications and e-mail to the [requirements](https://github.com/bounswe/bounswe2022group8/wiki/Requirements).
-  Update the [glossary](https://github.com/bounswe/bounswe2022group8/wiki/Requirements#glossary) if necessary.

Reviewer : @kostanya 
_Deadline_: 14.04.2022 @22.00

**Comment by sinemKocoglu** [comment]
Following requirements are added under  _Notification_ : 
* 1.2.1.2. Users added by an exhibition organizer as a collaborator on the exhibition shall be notified with an invitation.
* 1.2.1.3. Users holding an exhibition shall be notified when the collaborators add a new art item to the exhibition.
* 1.2.1.4. Seller shall be notified about offers they receive for the art items.
* 1.2.1.5. Bidder shall be notified when the seller accepts the given offer.
* 1.2.1.6. Bidder shall be notified when the seller declines the given offer.
* 1.2.1.7. Users making an offer on an art item shall be notified when the art item receives a new offer.
* 1.2.1.8. Moderator shall be notified when a ticket about a problem or copyright is submitted by an active user.
* 1.2.1.9  Users shall be notified when an error is occured during an action.

**Comment by kostanya** [comment]
Following requirements are added under _Notification_:
- 1.2.1.10. Users shall be notified when they receive a follow request.
- 1.2.1.11. Users shall be notified when their follow request is accepted.
- 1.2.1.12. Users shall not be notified when their follow request is rejected.

Thank you @sinemKocoglu for your valuable contributions. It is quite comprehensive.
