### ISSUE TITLE
Class Diagram: DB handler

### ISSUE THREAD

**Issue by kostanya** [bounswe/bounswe2022group8#67]
In [customer meeting](https://github.com/bounswe/bounswe2022group8/wiki/Week6---Meeting-%2310-(06.04.2022)-(PS)) we decided to add a basic data base handler for our class diagram so that our sequence diagrams would make more sense.

**To-Do**: Create Data Base Handler in the class-diagram.

- Use templates for methods to avoid unnecessary repetition.

_Deadline:_ 12.04.2022 @13.59

**Comment by serdarakol** [comment]
In the meeting which is held on 12.04.2022, we decided not  to include a database handler.
