### ISSUE TITLE
Requirements Elicitation: Exhibition

### ISSUE THREAD

**Issue by sinemKocoglu** [bounswe/bounswe2022group8#68]
**To Do**: As the last phase of the requirements elicitation, [Requirements](https://github.com/bounswe/bounswe2022group8/wiki/Requirements) must be revised and validated in accordance with our software design. Tasks for the exhibition:
* Update the _Exhibition_ section of the [User Requirements](https://github.com/bounswe/bounswe2022group8/wiki/Requirements#11-user-requirements) in order to include missing functionalities according to diagrams and mockups.
* Update the [glossary](https://github.com/bounswe/bounswe2022group8/wiki/Requirements#glossary) if necessary.

*Deadline:*
15.04.2022 @23.59

**Comment by sinemKocoglu** [comment]
1.1.6.7. and 1.1.6.8. are added to exhibition requirements. 
1.1.6.1. is updated that "Active User" is replaced with "Registered User".

Definition of "Tag" is updated in glossary that it can be used also for the exhibition.

**Comment by sinemKocoglu** [comment]
#61

**Comment by KarahanS** [comment]
Reviewed, thank you for the effort.

**Comment by BElifb** [comment]
* I am confused as to whether 1.1.6.3. refers to attending or participation.
* If it is the prior, hadn't we decided to limit attending the exhibition to registered users?
* There is no mention of the approval process of art items, which we decided on and put in the use-case diagram.

**Comment by KarahanS** [comment]
* ```1.1.6.3.``` refers to participation. For attending, we have ```1.1.4.9```.
* Corrected the word **User** with **Registered User**.
* Added ```1.1.6.10```
> 1.1.6.10. Exhibition organizers shall confirm or reject proposed art items by the collaborators in order to open add them to the exhibition.

**Comment by BElifb** [comment]
* Updated 1.1.6.2. to include addition of organizers.
* Updated 1.1.6.3 to imply attending.
* Added 1.1.6.10 and 1.1.6.11 to reflect approval process.
* Added **participant** to the glossary to bring clarity an updated 1.1.6.4 accordingly.
