### ISSUE TITLE
Requirements Elicitation: Recommendation System

### ISSUE THREAD

**Issue by KarahanS** [bounswe/bounswe2022group8#69]
To Do: As the last phase of the requirements elicitation, [Requirements](https://github.com/bounswe/bounswe2022group8/wiki/Requirements) must be revised and validated in accordance with our software design. Tasks for the user interaction:

Update the _Recommendation_ section of the [System Requirements](https://github.com/bounswe/bounswe2022group8/wiki/Requirements) to give more detail about **Activity history** and recommendations types our application is supposed to do.
* Specify the activities that will be stored in the activity history of a user (also related to #62)
* Specify the content of the recommendations.

Update the [glossary](https://github.com/bounswe/bounswe2022group8/wiki/Requirements#glossary) if necessary.

Reviewer: @serdarakol 
Deadline: 15.04.2022 @19.59

**Comment by KarahanS** [comment]
* Added ```1.2.3.2.``` to specify the contents of the activity history.
* Added ```1.2.3.3.``` to indicate that our platform may (_should_) keep track of viewed art items by the user without any interaction. 
* Added a reference to ```1.2.3.4.``` in order to refer to the geotagging mentioned before. (Should we add the geotag to the glossary?)
* Added ```1.2.3.5.``` to indicate that physical exhibition recommendations can be made based on location history. (Should we also recommend online exhibitions? How can we recommend online exhibitions based on location history?)
* Added ```1.2.3.6``` to indicate that art items can be recommended based on activity history.
* Added ```1.2.3.7.``` to indicate that users can be recommended based on activity history. 

Please review carefully.

**Comment by serdarakol** [comment]
I have reviewed your changes. They look fine. Health to your hands :) 
Answer to the first question. yes I think we should add geotagging to the glossary. I am on it.
answer to the second questions. Yes we shall also recommend online exhibitions based on their activity history, not necessarily just based on the location history. Activity hisory includes all the things mentioned on the same section
I have add this below
* 1.2.3.6. The platform shall recommend online exhibitions according to the users’ interests based on their activity.
Geotagging: Geotagging is the process of appending geographic coordinates to media based on the location of a mobile device. Geotags can be applied to photos, videos, websites, text messages, and QR codes, and could also include time stamps or other contextual information.
