### ISSUE TITLE
Creating RAM (Responsibility assignment matrix)

### ISSUE THREAD

**Issue by serdarakol** [bounswe/bounswe2022group8#72]
This is a sub-issue for the Milestone I Report #73.
Doğukan, Hebun, Sena and I, we have held a meeting on 11.04.2022
we have worked on the RAM. Further development might be needed. We are waiting for all members to write their work summaries.

**Comment by mumcusena** [comment]
* I added entries to RAM for myself, @KarahanS, @dundarmete, @mustafa-cihan. Please review the RAM until today's meeting.

_Reviewers: @ooodogodogodogo , @serdarakol , @simsekhebun_

**Comment by ooodogodogodogo** [comment]
All entries are filled. Issue can be closed after a quick review by @serdarakol @mumcusena @simsekhebun

**Comment by dundarmete** [comment]
Thanks for your contribution @mumcusena .

**Comment by serdarakol** [comment]
They look all fine. We can present it to the team before submitting it.  Closing the issue
