### ISSUE TITLE
Milestone I Report: List and Status of Deliverables & Evaluation 

### ISSUE THREAD

**Issue by KarahanS** [bounswe/bounswe2022group8#74]
This is a sub-issue of Milestone I Report #73.
**To Do**: As a part of our milestone report, we have to 
* List and status of deliverables (4)
* Evaluation of the status of deliverables and its impact on your project plan (5)

Corresponding actions will be taken, please refer to the Google Docs link provided in our Discord channel.
Reviewer: @serdarakol 
Deadline: 15.04.2022 @19.00

**Comment by KarahanS** [comment]
Created a table with _Deliverable_, _Status_, _Update Frequency_ and _Description_ fields.
Added following deliverables:
* Github Issues
* Github Wiki
* Meeting Notes
* Requirements
* User Scenario & Mockups
* Design Diagrams
* Communication Plan
* Project Plan
* RAM
* Milestone report I 

Under the table, you can also view the evaluation of the status of deliverables. 
Review required.

**Comment by serdarakol** [comment]
I have reviewed and corrected some small grammer mistakes

**Comment by KarahanS** [comment]
Thanks for the review.
