### ISSUE TITLE
Non-Functional Requirements: Capacity

### ISSUE THREAD

**Issue by kostanya** [bounswe/bounswe2022group8#75]
After [weekly meeting 11](https://github.com/bounswe/bounswe2022group8/wiki/Week-6-Meeting-Notes-%2311), we decided to add _capacity_ as a new non-functional requirement since our application will require a lot of size related limitations such as memory limit of a photo to be added to the system by users. 

**To-Do:** Create _capacity_ title under non-functional requirements and add subtitles.
Reviewer: @mumcusena

**Comment by BElifb** [comment]
* Updated 2.8.1 as **photo per art item**
* Added 2.8.2, limiting the number of photos per art item.
* Please review and report any objections.

**Comment by mumcusena** [comment]
The requirements 2.8.1 and 2.8.2 are written correctly in terms of verifiability, consistency, and unambiguity. They are also consistent with the discussions we made as a team during weekly meetings and also with customer meetings.
