### ISSUE TITLE
Requirements Elicitation: Annotation as a User Requirement

### ISSUE THREAD

**Issue by KarahanS** [bounswe/bounswe2022group8#76]
**To Do**: As the last phase of the requirements elicitation, [Requirements](https://github.com/bounswe/bounswe2022group8/wiki/Requirements) must be revised and validated in accordance with our software design. We have _Annotation_ already present as a _System Requirements_. However, we have to explain the features of annotation under the _User Requirements_ in more detail. Tasks for the annotation:

* Add _Annotation_ subsection to the _User Requirements_ and list the entities that can be annotated using text or image annotation.
* Update the [glossary](https://github.com/bounswe/bounswe2022group8/wiki/Requirements#glossary) if necessary.

Reviewer: @sinemKocoglu  
Deadline: 15.04.2022 @19.59

**Comment by KarahanS** [comment]
Created ```1.1.7. Annotations``` and added following articles:
> * 1.1.7.1. Registered users shall be able to bookmark art items, online/offline exhibitions and comments.
> * 1.1.7.2. Registered users shall be able to annotate the text content with semantic tags, text or image. Text may be a URL that serves as a hyperlink.   
 >      * 1.1.7.2.1. Registered users shall be able to annotate content in the comments/replies. 
>     * 1.1.7.2.2 Registered users shall be able to annotate content in the descriptions of the art items.
 >    * 1.1.7.2.3 Registered users shall be able to annotate content in the titles of the art items.
  >  * 1.1.7.2.4. Registered users shall be able to annotate content in the descriptions of the online/offline exhibitions.
> * 1.1.7.3. Registered users shall be able to annotate the image content with semantics tags, text or image.
 >   * 1.1.7.3.1. Registered users shall be able to annotate the art items in the platform.  

Please review carefully.

**Comment by sinemKocoglu** [comment]
Writing description for exhibitions is not mentioned in any other requirements, third scenario and mockup. Therefore, I am not sure if 1.1.7.2.4 is ok or not. Others are great.

**Comment by KarahanS** [comment]
Thank you for the review. I've added description and title functionality for the exhibitions. We have already talked about them in our meetings but didn't add them to the requirements page. Sorry for not pointing that out. 
```1.1.6.9. Exhibition organizers shall be able to set title and description for the exhibition.```

**Comment by sinemKocoglu** [comment]
Then, I added 
- +setDescription(description:String):void 

funtion to sequence diagram for "Holding an Exhibition" and Exhibition class in class diagram.

**Comment by KarahanS** [comment]
Also added
* -title:String
* +setTitle(title:String):void

to the exhibition.
Now, there shouldn't be any missing point left.

**Comment by serdarakol** [comment]
@KarahanS I think, we should be clear about, what bookmarking an artitem, an exhibition or a comment, is. Further elaboration or glossary is needed.

**Comment by sinemKocoglu** [comment]
- setTitle(title:String):void 

is also added to sequence diagram.

**Comment by KarahanS** [comment]
Added **Bookmark** to the glossary. Thanks for the reminder, I agree that it's important to add it to the glossary to eradicate confusion.
> Bookmark: Bookmarking is recording the address (URL) of a webpage to enable quick access in the future. Bookmarking an art item, exhibition or comment is storing the URLs of related entities for later reference.

Btw, for a concrete idea of URL of a comment, you can check the syntax of this URL:
> https://stackoverflow.com/questions/69517878/space-complexity-of-first-non-repeating-character-algorithm/69517941#comment122875786_69517878

This is simply a URL that redirects you to one of the comments under the related post. Probably, comment is associated with its unique identification in the URL (not sure). But this is same idea we can apply in the future. (And probably 69517878 is the ID of the question, it's attached to the ID of the comment - clever idea to ensure uniqueness)

**Comment by serdarakol** [comment]
Looks perfect! Closing the issue.
