### ISSUE TITLE
Milestone Subissue: Writing Executive Summary (Project Description and Project Status)

### ISSUE THREAD

**Issue by serdarakol** [bounswe/bounswe2022group8#77]
this is subissue of [Milestone I Report #73](https://github.com/bounswe/bounswe2022group8/issues/73 )writing the Executive Summary (Project Description and Project Status) for milestone report.  
reviewer: @dundarmete

**Comment by serdarakol** [comment]
I have wrote the Executive summary: 
project descirption, project status (also a diagram #78), moving forward to seciton of the milestone report, 
@dundarmete you can review it, any other review is also welcome

**Comment by kostanya** [comment]
Great job. You have conveyed everything we have done in the past weeks in a pleasant, fluent and comprehensive way. Just added some missing words that you overlooked. Thanks for the effort.

**Comment by KarahanS** [comment]
Reviewed, corrected minor grammar mistakes. Thanks for the effort.

**Comment by dundarmete** [comment]
I reviewed the document that was shared in discord. It seems perfect.
