### ISSUE TITLE
Milestone I Report: Evaluation of Tools and Processes

### ISSUE THREAD

**Issue by kostanya** [bounswe/bounswe2022group8#79]
This is a sub-issue of Milestone I Report https://github.com/bounswe/bounswe2022group8/issues/73.
**To-Do:** As a part of our milestone report, we have to

- Explain each program, each communication method we used, and why we used them.

Corresponding actions will be taken, please refer to the Google Docs link provided in our Discord channel.
Deadline: 15.04.2022 @19.00

**Comment by KarahanS** [comment]
Great!
