### ISSUE TITLE
Milestone1: Project Plan

### ISSUE THREAD

**Issue by BElifb** [bounswe/bounswe2022group8#80]
This is a sub-issue for the Milestone I Report #73.
As decided in the meetings, we are supposed to detail the project plan and create the corresponding tables.

**To Do:**
*  Decide on an appropriate software to create the Gantt chart.
*  Write down the tasks.
* Specify the dates and durations.
* Specify the preconditions.
* Specify the resources. 
*  Create the List and the Gantt chart. 

**Deadline:** 14.04.2022 @23.59

**Additional Information:**  
* You may refer to the relevant Discord channel for more detailed information.

**Comment by BElifb** [comment]
* After much deliberation we decided on using **Project Libre**.
* **Spoiler alert**: this might have been a cursed decision.

**Comment by KarahanS** [comment]
Added following tasks, durations for each and resources:
> Creating personal wiki pages
Creating personal timesheets
Creating Discord channel for communication
Creating communication plan
Research on Git
Research on Favourite Github Repositories
Customizing issues
Creating Markdown Guide
Research on Art Community Platforms
Customizing Group 8 Wiki page
Taking meeting notes and adding to wiki
Research on project management tools
Writing Elevator Pitch page
Attending Problem Sessions
Attending Weekly Meetings
 
Requirements
Searching and comparing similar projects in terms of requirements
Adding user requirements
Adding system requirements
Adding non-functional requirements
Creating glossary
Creating Q&A page
Attending Customer Meetings
Reviewing requirements


</body>
</html>

**Comment by sinemKocoglu** [comment]
Dates and predecessors of Implementation part are added.

**Comment by kostanya** [comment]
Added following tasks, durations for each and resources:
>Research before pre-implementation
Research on programming languages
Research on API's
Research on Testing and Debugging
Research on UI tools
Research on Databases and servers
Research on Cloud Service Providers
Deciding the subgroups
Research on Cmpe451 subjects
Research on clean coding
Creating API's
Milestone 2

>Pre-Implementation
Revise requirements, diagrams and project plan
Designing initial backendskeleton
Designing initial frontend skeleton
Designing initial android skeleton
Setting-up the server


</body>
</html>

**Comment by BElifb** [comment]
Added the following tasks, along with durations time and predecessors:

	Scenarios&Mockups		
	Designing Mockup Templates		
	Designing Scenario Steps		
	Designing Mockups for Scenario #1	
	Designing Mockups for Scenario #2		
	Designing Mockups for Scenario #3	
	Creating Scenario  #1: Art Follower		
	Creating Scenario  #2: Artist	
	Creating Scenario  #3: Collaboration		
						
	Diagrams	
	Research on Design Diagrams		
	Creating Class Diagram
	Creating Sequence Diagrams		
	Creating Use Case Diagram	
	Reviewing Class Diagram		
	Reviewing Use Case Diagram	
	Reviewing Sequence Diagrams		
						
	Milestone 1	
	Creating RAM	6 days		
	Creating Proejct Plan	
	Writing project description and status		
	Writing deliverable status and evaluation		
	Writing evaluation of tools and processes		
	Writing a summary of work done 
	Collecting all items in submission pdf  		
	Reviewing requirements for Milestone1

**Comment by BElifb** [comment]
* Added my part of the resources.
* Using only specifying the lead convention as discussed.

**Comment by KarahanS** [comment]
* Added my part of the resources.
* Put the tasks in chronological order.

**Comment by KarahanS** [comment]
Completed, it can be examined [here](https://github.com/bounswe/bounswe2022group8/wiki/Milestone-1-Report).
