### ISSUE TITLE
Testing Template

### ISSUE THREAD

**Issue by BElifb** [bounswe/bounswe2022group8#85]
### What's up?

Just testing the template.

### To Do

* Create issue.
* See if you can delete it.

### Checklist

- [x] Elif Bayraktar
- [ ] Serdar Akol
- [ ] Sena Mumcu
- [ ] Karahan Sarıtaş
- [ ] Mustafa Cihan
- [ ] Serhat Hebun Şimşek
- [ ] Doğukan Türksoy
- [ ] Furkan Keskin
- [ ] Metehan Dündar
- [ ] Sinem Koçoğlu

### Deadline

22.04.2022 @23.59

### Reviewers

@uskudarli

**Comment by suzan-uskudarli** [comment]
I can detete your issue if you want. Let me know if you want me to delete it. @BElifb 

Alas, we can close it as:

issue template is verified with this test issue.

**Comment by BElifb** [comment]
I am doing the latter. Thank you so much for your time and attention. @suzan-uskudarli

**Comment by BElifb** [comment]
Issue template is verified with this test issue.
