### ISSUE TITLE
Practice App Research: Research on AWS EC2

### ISSUE THREAD

**Issue by KarahanS** [bounswe/bounswe2022group8#87]
### What's up?

As a part of our Practice App assignment, we have to create an _AWS EC2 instance_ and deploy our application to our server using the docker image. 

### To Do

* Each member should perform an individual research on AWS EC2 and become familiar with the concept. Please check the boxes below after making your research to let the others know.
- [ ] @ooodogodogodogo 
- [x] @serdarakol 
- [ ] @kostanya 
- [x] @BElifb 
- [ ] @simsekhebun 
- [x] @KarahanS 
- [x] @sinemKocoglu 
- [x] @mumcusena 
- [x] @mustafa-cihan 
- [ ] @dundarmete 

* Members assigned to the issue must perform the following tasks:
- [x] Create a wiki page related to the _Research on AWS EC2_.
- [x] Contribute to the wiki page. Your contributions may include text, images, links to educational materials etc. Try to answer some basic questions such as:
   * What is Amazon EC2? Why is it necessary for our application?
   * How can a developer deploy the application to the server?
   * How can an end user reach to the application after deployment? 
- [x] Attach the wiki page to the sidebar.

### Deadline

_Deadline: 01.05.2022 @20.00_

### Additional Information

For our application, we will be using [AWS Free Tier](https://aws.amazon.com/free/). Also, please have a look at the [AWS Educate](https://aws.amazon.com/education/awseducate/) which may become useful for learning.

### Reviewers

Reviewer for the research and documentation: @KarahanS

**Comment by KarahanS** [comment]
Created the wiki page over [here](https://github.com/bounswe/bounswe2022group8/wiki/Research-on-Amazon-Web-Services-EC2). Attached it to the wiki sidebar. Added a definition, some terminology and useful links for setting up an AWS EC2 Instance.

**Comment by BElifb** [comment]
* Added some resources about AWS Elastic Beanstalk.
* I think it could be a good match for what we've been looking for.

**Comment by sinemKocoglu** [comment]
Resources 

- Deploying a Web Application on Amazon EC2
- A developer experience for deploying a full-stack web application

are added.

**Comment by mumcusena** [comment]
* Added a video tutorial of EC2 for beginners which I think is a good place to start. 
* Added a brief definition of EC2.

**Comment by KarahanS** [comment]
Research procedure is done. No action is taken.
