### ISSUE TITLE
Practice App Research: Research on Docker

### ISSUE THREAD

**Issue by KarahanS** [bounswe/bounswe2022group8#88]
### What's up?

As a part of our Practice App assignment, after completing the implementation we have to dockerize our application and test that each member is able to deploy it on their personal development environment.

### To Do

Each member should perform an individual research on Docker and become familiar with the concept. Please check the boxes below after making your research to let the others know.
- [ ] @ooodogodogodogo 
- [ ] @serdarakol 
- [ ] @kostanya 
- [x] @BElifb 
- [x] @simsekhebun 
- [ ] @KarahanS 
- [ ] @sinemKocoglu 
- [x] @mumcusena 
- [x] @mustafa-cihan 
- [ ] @dundarmete 

* Members assigned to the issue must perform the following tasks:
- [x] Create a wiki page related to the _Research on Docker_.
- [ ] Contribute to the wiki page. You contributions may include text, images, links to educational materials etc. Try to answer some basic questions such as:
   * What is Docker? What is a Docker image and why is it necessary?
   * How to get started with Docker?
- [x] Attach the wiki page to the sidebar.

### Deadline

_Deadline: 01.05.2022 @20.00_

### Reviewers

Reviewer for the research and documentation: @BElifb

**Comment by BElifb** [comment]
* Created research on docker page, added it to sidebar.
* Added some useful links and visuals.

**Comment by mumcusena** [comment]
* Added a brief definition of Docker and container. 
* Added a link to a video tutorial on Docker for beginners.

**Comment by KarahanS** [comment]
Research procedure is done. No action is taken.

**Comment by KarahanS** [comment]
* Added basic instructions to dockerize an application including:
   * How to write a Dockerfile.
   * How to build the image.
   * How to run the container.
