### ISSUE TITLE
Practice App Research: Research on Postman

### ISSUE THREAD

**Issue by KarahanS** [bounswe/bounswe2022group8#89]
### What's up?

As a part of our Practice App assignment, we have to test our APIs using [Postman](https://www.postman.com/), HTTP Get or similar tools. For now, we decided to continue with Postman.  

### To Do

* Each member should perform an individual research on Postman and become familiar with the concept. Please check the boxes below after making your research to let the others know.
- [ ] @ooodogodogodogo 
- [x] @serdarakol 
- [x] @kostanya 
- [ ] @BElifb 
- [ ] @simsekhebun 
- [x] @KarahanS 
- [ ] @sinemKocoglu 
- [ ] @mumcusena 
- [x] @mustafa-cihan 
- [ ] @dundarmete 

* Members assigned to the issue must perform the following tasks:
- [x] Create a wiki page related to the _Research on Postman_.
- [x] Contribute to the wiki page. You contributions may include text, images, links to educational materials etc. Try to answer some basic questions such as:
   * What is Postman? 
   * How can one test an API using Postman?
- [x] Attach the wiki page to the sidebar.

### Deadline

_Deadline: 01.05.2022 @20.00_

### Reviewers

Reviewer for the research and documentation: @kostanya

**Comment by mustafa-cihan** [comment]
Created the [wiki page](https://github.com/bounswe/bounswe2022group8/wiki/Research-On-Postman). Attached it to the wiki sidebar. Added some resources

**Comment by kostanya** [comment]
Added _API Testing with Postman_ and provided a link to _Postman Docs_.

**Comment by serdarakol** [comment]
I did my researches regarding the topic. I ve used them extensively when testing my endpoint

**Comment by KarahanS** [comment]
Research procedure is done. No action is taken.
