### ISSUE TITLE
Practice App: Initial Configurations for the App

### ISSUE THREAD

**Issue by KarahanS** [bounswe/bounswe2022group8#92]
### What's up?

In our meeting [#13](https://github.com/bounswe/bounswe2022group8/wiki/Week-9-Meeting-%2313), we decided to continue with [Django](https://www.djangoproject.com/) to build our practice app and REST API. In meeting [#14](https://github.com/bounswe/bounswe2022group8/wiki/Week-10-Meeting-%2314) we distributed some endpoints among the participants of the meeting. Now, we have to build our Django application with a proper project structure.

### To Do

* Each member shall learn the basics of the Django and Django Rest Framework in order to be able to contribute to the project.
* Configuration steps include: 
- [x] Open the [Practice App](https://github.com/bounswe/bounswe2022group8/tree/dev/Practice%20App) folder in the ```dev``` branch and create a Python [virtual environment](https://docs.python.org/3/tutorial/venv.html) directory.
- [x] Expand the content of the .gitignore file to include environment folders, IDE specific directories etc.
- [x] Install Django and Django Rest Framework. 
- [x] Create a ```requirements.txt``` file to document the libraries used.
- [x] Create a Django project using ```django-admin startproject django_app```.
- [x] Create a startup project using ```python manage.py startapp api```. We will be collecting our views, tests, models and urls in the **api** folder.
- [x] Create some initial urls and views.
---
* Anyone should perform the following steps to set up the project:
   1) If you haven't done it yet, please clone the repository to your local and switch to ```dev``` branch.
   2) Open your preferred IDE (VS Code is strongly recommended) and create a virtual environment within the "practice app" folder. You can use the command below to create a virtual environment with the name ```env``` in the Windows powershell:
   ``` 
   python -m venv env
   ```
    * Please create your virtual environment with the name ```env```. If you insist on creating with another name for some unknown reason, please add that name to the [.gitignore](https://github.com/bounswe/bounswe2022group8/blob/dev/Practice%20App/.gitignore) file. Do not push your virtual environment folder to the repository. Don't forget to update the .gitignore before creating your virtual environment if you are going with a different name. Otherwise git won't notice it and you will see your virtual environment in the "unstaged files" area. 
    3) Activate your virtual environment:
    ```
    env\Scripts\activate
    ```
   * If this command doesn't work, please just google how to activate a virtual environment. There may be different commands for different shells & operating systems.
   4) Make sure that your Python interpreter is the one in the virtual environment. In VS Code, sometimes it doesn't change it automatically, you can change it from the "Select Interpreter" tab. 
   5) Install the necessary python packages listed in the ```requirements.txt``` folder:
  ```
  pip install -r requirements.txt
  ```
  * Most probably, ```requirements.txt``` will be updated as we need some packages throughout the development. 
   6) You can run the application using this command:
   ```
   python manage.py runserver
   ```
  It uses port ```8000```, please go to ```http://127.0.0.1:8000/```. Don't worry if you encounter with a page that displays some garbage, redirect to ```http://127.0.0.1:8000/api``` or ```http://127.0.0.1:8000/admin```. Second is a default route provided by Django. It has a simple html page.
   

### Deadline

_Deadline:_ _11.05.2022 @21.00_

### Additional Information

There are a lot to learn, but in order to make a start, I recommend you to watch these videos:
* [Django REST Framework Oversimplified](https://www.youtube.com/watch?v=cJveiktaOSQ): Creates a route, a model, a view and a serializer for the model. As the name suggests, it's a very simplified representation of the idea.
* [Django Tutorial by Corey Schafer](https://www.youtube.com/playlist?list=PL-osiE80TeTtoQCKZ03TU5fNfx2UY6U4p): It'd be nice to watch the first couple of videos. He builds the application from scratch one by one and explains the concepts like routes, database migration and templates. Notice that what he shows is not REST API. But it can be helpful to understand what's going on with Django.
* [Build a Django REST API with the Django Rest Framework. Complete Tutorial.](https://www.youtube.com/watch?v=c708Nf0cHrs): Extremely long video, checked first half hour to become familiar with [Django Rest Framework](https://www.django-rest-framework.org/). Planning to watch some other parts as well.
* [Django REST Framework - Build an API From Scratch](https://www.youtube.com/watch?v=i5JykvxUk_A&t=293s): Develops and API that uses database. I haven't watched it yet, but it seems very helpful for our project.
* [Python Django Tutorial: Full-Featured Web App Part 5 - Database and Migrations](https://www.youtube.com/watch?v=aHC3uTkT9r8&list=PL-osiE80TeTtoQCKZ03TU5fNfx2UY6U4p&index=5): Great video on migrations, how to create a model and migrate it.
---
Please do some research on Django and try to understand what's going on in the application. Let me share some sort of a structure one has to follow in order to develop his API endpoint.
* For each API endpoint, we will be adding new views to the "views" folder under the "api" folder. We have to return responses in JSON format since we are dealing with a REST API. Right now, there is only one file named "views.py". It includes three functions, two of which returns ```HttpResponse```. We have to return ```JsonResponse``` object, third function complies with what we want. (Notice that it's just a dummy function, it doesn't do anything important. I created all these functions to see if it works properly.).
* Let's say you want to create an API about weather. Then you have to create a file with a name similar to ```view_WeatherAPI.py```. Then you have to write your functions for ```GET```, ```POST```, etc. 
* Then you have to go to the "urls.py" within the "api" folder and add the path of your view. You have to provide the related function as a parameter to the ```path()``` function.
* Then you have to write some tests using ```django.test``` package. To do so, create a file like ```test_WeatherAPI.py``` within the "tests" folder and implement your unittest. 
* To run the tests you can use the command below:
   ```
   python manage.py test api/tests
   ```
  This command runs all the tests under the tests folder. If you want to run a single test, please modify the last parameter of 
   the command.

Please notice that the steps above are not enough for an API that uses the database and has a little bit of a front-end for the end user. I listed those just to give you a rough idea about what has to be done. We have to use database as well since we well be creating API endpoints related to our project.
* In the ```models.py```, we have to create models (entities) for our database. Then we can use the ORM of the Django. Please check the [documentation](https://docs.djangoproject.com/en/4.0/topics/db/queries/) for details. 
* We have to create a "templates" folder to include our html files for frontend. "templates" folder will be in the "api" directory.

### Reviewers

Literally @everyone.
Issue will be closed after we make sure that everyone in the team is on the same ground.

**Comment by BElifb** [comment]
* Updated requirements
* Added gitignore to the outer directory to match the main, think we should update main and merge to dev.
* Redirected homapage to api/
* Created models for myUser, Tag, Comment, ArtItem 
* Added them to the admin panel
* You may run `python manage.py createsuperuser` to create an admin, and to log into the admin site and see the tables.
* Created serializers for ArtItem and Tag
* Pull request at [#93 ](https://github.com/bounswe/bounswe2022group8/pull/93#issue-1231759586)

**Comment by BElifb** [comment]
* myUser is not complete, just needed to create it for others' sake.

**Comment by KarahanS** [comment]
Implementation is completed.
