### ISSUE TITLE
Practice App: Creating Models

### ISSUE THREAD

**Issue by KarahanS** [bounswe/bounswe2022group8#96]
### What's up?

We have designed our ER Diagrams as documented in #94. Now corresponding models must be created. Corresponding serializers are also going to be created. Please refer to #100 for details.

### To Do

Following actions must be taken:

- [x] Create models:
   - [x] Create ```user``` model that extends the default ```User``` model provided by Django.
   - [x] Create ```comment``` model.
   - [x] Create ```tag``` model.
   - [x] Create ```art item``` model.
   - [x] Create ```follow``` model.
- [x] Make migrations and apply these migrations.
- [x] Register the models within the ```admin.py```. Login as an admin and check if tables are listed properly.

### Deadline

_Deadline: 14.05.2022 @22.00_

### Additional Information

**Contributors**: 
* @BElifb 
* @KarahanS

**Comment by KarahanS** [comment]
Reviewed pull request #93 and merged it do the ```dev``` branch. [Serializers.py](https://github.com/bounswe/bounswe2022group8/blob/dev/Practice%20App/api/serializers.py) will be updated as we develop our APIs.

**Comment by BElifb** [comment]
* Created models, serializers, updated some things and migrated. More details at [#92](https://github.com/bounswe/bounswe2022group8/issues/92#issuecomment-1123001022)

**Comment by BElifb** [comment]
* Went over pull request [#97](https://github.com/bounswe/bounswe2022group8/pull/97#issue-1232674940) changes and issues, here's the related [comment](https://github.com/bounswe/bounswe2022group8/pull/97#issuecomment-1124207877).

**Comment by KarahanS** [comment]
* Thanks for the review. Responded to your comment [here](https://github.com/bounswe/bounswe2022group8/pull/97#issuecomment-1124239178).

**Comment by BElifb** [comment]
* Updated structure image fields.
* Added default images.
* Removed media from .gitignore to keep images.
*  [commit](https://github.com/bounswe/bounswe2022group8/pull/97/commits/87bf8f73b1017a987838d0a7985c624c4d1cbac2)
* Tested the default image.
* Tested the fact that django in fact changes image file names in case of contradiction. (You may see it in media folder)

**Comment by KarahanS** [comment]
* Added a ```username()``` method to the ```myUserSerializer``` in order to fetch the **id** of a user in JSON format.
* Added _created_at_ field to the **Follow** model.
Please refer to #99 for details.

**Comment by serdarakol** [comment]
The models.py file suffices the tasks and requirements of our application.For milestone 2 it seems it is finalized. If further development is needed. one can open this issue. Closing the issue
